package wombatstable

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"math/big"

	"github.com/KyberNetwork/kyberswap-dex-lib/pkg/msgpencode"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PoolSimulator) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 6 {
		err = msgp.ArrayError{Wanted: 6, Got: zb0001}
		return
	}
	err = z.Pool.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "amp")
			return
		}
		z.amp = nil
	} else {
		{
			var zb0002 []byte
			zb0002, err = dc.ReadBytes(msgpencode.EncodeInt(z.amp))
			if err != nil {
				err = msgp.WrapError(err, "amp")
				return
			}
			z.amp = msgpencode.DecodeInt(zb0002)
		}
	}
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err, "lpTokenBalances")
		return
	}
	if z.lpTokenBalances == nil {
		z.lpTokenBalances = make(map[string]*big.Int, zb0003)
	} else if len(z.lpTokenBalances) > 0 {
		for key := range z.lpTokenBalances {
			delete(z.lpTokenBalances, key)
		}
	}
	for zb0003 > 0 {
		zb0003--
		var za0001 string
		var za0002 *big.Int
		za0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "lpTokenBalances")
			return
		}
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, "lpTokenBalances", za0001)
				return
			}
			za0002 = nil
		} else {
			{
				var zb0004 []byte
				zb0004, err = dc.ReadBytes(msgpencode.EncodeInt(za0002))
				if err != nil {
					err = msgp.WrapError(err, "lpTokenBalances", za0001)
					return
				}
				za0002 = msgpencode.DecodeInt(zb0004)
			}
		}
		z.lpTokenBalances[za0001] = za0002
	}
	var zb0005 uint32
	zb0005, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err, "tokenInfo")
		return
	}
	if z.tokenInfo == nil {
		z.tokenInfo = make(map[string]tokenInfo, zb0005)
	} else if len(z.tokenInfo) > 0 {
		for key := range z.tokenInfo {
			delete(z.tokenInfo, key)
		}
	}
	for zb0005 > 0 {
		zb0005--
		var za0003 string
		var za0004 tokenInfo
		za0003, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo")
			return
		}
		err = za0004.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo", za0003)
			return
		}
		z.tokenInfo[za0003] = za0004
	}
	z.vault, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "vault")
		return
	}
	var zb0006 uint32
	zb0006, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err, "wrappers")
		return
	}
	if z.wrappers == nil {
		z.wrappers = make(map[string]string, zb0006)
	} else if len(z.wrappers) > 0 {
		for key := range z.wrappers {
			delete(z.wrappers, key)
		}
	}
	for zb0006 > 0 {
		zb0006--
		var za0005 string
		var za0006 string
		za0005, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "wrappers")
			return
		}
		za0006, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, "wrappers", za0005)
			return
		}
		z.wrappers[za0005] = za0006
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PoolSimulator) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 6
	err = en.Append(0x96)
	if err != nil {
		return
	}
	err = z.Pool.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if z.amp == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(msgpencode.EncodeInt(z.amp))
		if err != nil {
			err = msgp.WrapError(err, "amp")
			return
		}
	}
	err = en.WriteMapHeader(uint32(len(z.lpTokenBalances)))
	if err != nil {
		err = msgp.WrapError(err, "lpTokenBalances")
		return
	}
	for za0001, za0002 := range z.lpTokenBalances {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "lpTokenBalances")
			return
		}
		if za0002 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = en.WriteBytes(msgpencode.EncodeInt(za0002))
			if err != nil {
				err = msgp.WrapError(err, "lpTokenBalances", za0001)
				return
			}
		}
	}
	err = en.WriteMapHeader(uint32(len(z.tokenInfo)))
	if err != nil {
		err = msgp.WrapError(err, "tokenInfo")
		return
	}
	for za0003, za0004 := range z.tokenInfo {
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo")
			return
		}
		err = za0004.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo", za0003)
			return
		}
	}
	err = en.WriteString(z.vault)
	if err != nil {
		err = msgp.WrapError(err, "vault")
		return
	}
	err = en.WriteMapHeader(uint32(len(z.wrappers)))
	if err != nil {
		err = msgp.WrapError(err, "wrappers")
		return
	}
	for za0005, za0006 := range z.wrappers {
		err = en.WriteString(za0005)
		if err != nil {
			err = msgp.WrapError(err, "wrappers")
			return
		}
		err = en.WriteString(za0006)
		if err != nil {
			err = msgp.WrapError(err, "wrappers", za0005)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PoolSimulator) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 6
	o = append(o, 0x96)
	o, err = z.Pool.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if z.amp == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, msgpencode.EncodeInt(z.amp))
	}
	o = msgp.AppendMapHeader(o, uint32(len(z.lpTokenBalances)))
	for za0001, za0002 := range z.lpTokenBalances {
		o = msgp.AppendString(o, za0001)
		if za0002 == nil {
			o = msgp.AppendNil(o)
		} else {
			o = msgp.AppendBytes(o, msgpencode.EncodeInt(za0002))
		}
	}
	o = msgp.AppendMapHeader(o, uint32(len(z.tokenInfo)))
	for za0003, za0004 := range z.tokenInfo {
		o = msgp.AppendString(o, za0003)
		o, err = za0004.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo", za0003)
			return
		}
	}
	o = msgp.AppendString(o, z.vault)
	o = msgp.AppendMapHeader(o, uint32(len(z.wrappers)))
	for za0005, za0006 := range z.wrappers {
		o = msgp.AppendString(o, za0005)
		o = msgp.AppendString(o, za0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PoolSimulator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 6 {
		err = msgp.ArrayError{Wanted: 6, Got: zb0001}
		return
	}
	bts, err = z.Pool.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.amp = nil
	} else {
		{
			var zb0002 []byte
			zb0002, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(z.amp))
			if err != nil {
				err = msgp.WrapError(err, "amp")
				return
			}
			z.amp = msgpencode.DecodeInt(zb0002)
		}
	}
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "lpTokenBalances")
		return
	}
	if z.lpTokenBalances == nil {
		z.lpTokenBalances = make(map[string]*big.Int, zb0003)
	} else if len(z.lpTokenBalances) > 0 {
		for key := range z.lpTokenBalances {
			delete(z.lpTokenBalances, key)
		}
	}
	for zb0003 > 0 {
		var za0001 string
		var za0002 *big.Int
		zb0003--
		za0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "lpTokenBalances")
			return
		}
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			za0002 = nil
		} else {
			{
				var zb0004 []byte
				zb0004, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(za0002))
				if err != nil {
					err = msgp.WrapError(err, "lpTokenBalances", za0001)
					return
				}
				za0002 = msgpencode.DecodeInt(zb0004)
			}
		}
		z.lpTokenBalances[za0001] = za0002
	}
	var zb0005 uint32
	zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "tokenInfo")
		return
	}
	if z.tokenInfo == nil {
		z.tokenInfo = make(map[string]tokenInfo, zb0005)
	} else if len(z.tokenInfo) > 0 {
		for key := range z.tokenInfo {
			delete(z.tokenInfo, key)
		}
	}
	for zb0005 > 0 {
		var za0003 string
		var za0004 tokenInfo
		zb0005--
		za0003, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo")
			return
		}
		bts, err = za0004.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "tokenInfo", za0003)
			return
		}
		z.tokenInfo[za0003] = za0004
	}
	z.vault, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "vault")
		return
	}
	var zb0006 uint32
	zb0006, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "wrappers")
		return
	}
	if z.wrappers == nil {
		z.wrappers = make(map[string]string, zb0006)
	} else if len(z.wrappers) > 0 {
		for key := range z.wrappers {
			delete(z.wrappers, key)
		}
	}
	for zb0006 > 0 {
		var za0005 string
		var za0006 string
		zb0006--
		za0005, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "wrappers")
			return
		}
		za0006, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, "wrappers", za0005)
			return
		}
		z.wrappers[za0005] = za0006
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PoolSimulator) Msgsize() (s int) {
	s = 1 + z.Pool.Msgsize()
	if z.amp == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(z.amp))
	}
	s += msgp.MapHeaderSize
	if z.lpTokenBalances != nil {
		for za0001, za0002 := range z.lpTokenBalances {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			if za0002 == nil {
				s += msgp.NilSize
			} else {
				s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(za0002))
			}
		}
	}
	s += msgp.MapHeaderSize
	if z.tokenInfo != nil {
		for za0003, za0004 := range z.tokenInfo {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + za0004.Msgsize()
		}
	}
	s += msgp.StringPrefixSize + len(z.vault) + msgp.MapHeaderSize
	if z.wrappers != nil {
		for za0005, za0006 := range z.wrappers {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.StringPrefixSize + len(za0006)
		}
	}
	return
}
