package shared

const (
	HOOKS_BEFORE_INITIALIZE_OFFSET = iota
	HOOKS_AFTER_INITIALIZE_OFFSET
	HOOKS_BEFORE_MINT_OFFSET
	HOOKS_AFTER_MINT_OFFSET
	HOOKS_BEFORE_BURN_OFFSET
	HOOKS_AFTER_BURN_OFFSET
	HOOKS_BEFORE_SWAP_OFFSET
	HOOKS_AFTER_SWAP_OFFSET
	HOOKS_BEFORE_DONATE_OFFSET
	HOOKS_AFTER_DONATE_OFFSET
	HOOKS_BEFORE_SWAP_RETURNS_DELTA_OFFSET
	HOOKS_AFTER_SWAP_RETURNS_DELTA_OFFSET
	HOOKS_AFTER_MINT_RETURNS_DELTA_OFFSET
	HOOKS_AFTER_BURN_RETURNS_DELTA_OFFSET
)

func hasOffsetEnabled(data []byte, bitOffset int) bool {
	offset := bitOffset / 8
	bitInByte := uint(bitOffset % 8)

	bit := (data[offset] >> bitInByte) & 0x01
	return bit == 1
}

func HasSwapPermissions(parameters []byte) bool {
	return hasOffsetEnabled(parameters, HOOKS_BEFORE_SWAP_OFFSET) || hasOffsetEnabled(parameters, HOOKS_AFTER_SWAP_OFFSET)
}
