env: &env "pre-release"
pprof: false
http:
  bindAddress: ":8080"
  mode: release #(debug,release,test)
  prefix: /arbitrum
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainId: &chainId 42161
  chainName: &chainName arbitrum
  rpc: "https://arbitrum.kyberengineering.io"
  rpcTimeout: 100ms
  multicallAddress: "0xcA11bde05977b3631167028862bE2a173976CA11"
  executorAddress: &executorAddress "0x6E4141d33021b52C91c28608403db4A0FFB50Ec6"
  routerAddress: &routerAddress "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5"
  whitelistedTokenSet: &whitelistedTokenSet
    0x1622bf67e6e5747b81866fe0b85178a93c7f86e3: true
    0x912ce59144191c1204e64559fe8253a0e49e6548: true
    0xfa5ed56a203466cbbc2430a43c66b9d8723528e7: true
    0x82af49447d8a07e3bd95bd0d56f35241523fbab1: true
    0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9: true
    0xda10009cbd5d07dd0cecc66161fc93d7c9000da1: true
    0xff970a61a04b1ca14834a43f5de4533ebddb5cc8: true
    0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f: true
    0xfea7a6a0b346362bf88a9e4a88416b77a57d6c2a: true
    0x5979d7b546e38e414f7e9822514be443a4800529: true
    0xe4dddfe67e7164b0fe14e218d80dc4c08edc01cb: true
    0x3f56e0c36d275367b8c502090edf38289b3dea0d: true
    0x316772cfec9a3e976fde42c3ba21f5a13aaaff12: true
    0x13ad51ed4f1b7e9dc168d8a00cb3f4ddd85efa60: true
    0xf97f4df75117a78c1a5a0dbb814af92458539fb4: true
    0xaf88d065e77c8cc2239327c5edb3a432268e5831: true
    0x88dfaaabaf06f3a41d2606ea98bc8eda109abebb: true
    0x17fc002b466eec40dae837fc4be5c67993ddbd6f: true
    0x894134a25a5fac1c2c26f1d8fbf05111a3cb9487: true
    0xb448ec505c924944ca8b2c55ef05c299ee0781df: true
    0x9cfb13e6c11054ac9fcb92ba89644f30775436e4: true
    0xabd587f2607542723b17f14d00d99b987c29b074: true
    0x6694340fc020c5e6b96567843da2df01b2ce1eb6: true
    0x178412e79c25968a32e89b11f63b33f733770c2a: true
    0xd85e038593d7a098614721eae955ec2022b9b91b: true
    0x95ab45875cffdba1e5f451b950bc2e42c0053f39: true
    0x8ca32924f0ea617680ac8b9f43a919911bc59690: true
    0xe80772eaf6e2e18b651f160bc9158b2a5cafca65: true
    0x5d3a1ff2b6bab83b63cd9ad0787074081a52ef34: true
  blacklistedPoolSet: &blacklistedPoolSet
    0x7b07164ecfaf0f0d85dfc062bc205a4674c75aa0: true
    0x1506b54a1c0ea1b2f4a84866ec5776f7f6e7f0b1: true
  availableSources: &availableSources
    - "ramses"
    - "curve"
    - "gmx"
    - "fraxswap"
    - "synapse"
    - "camelot"
    - "arbi-dex"
    - "iziswap"
    - "smardex"
    - "kyberswap"
    - "kyberswap-static"
    - "sushiswap"
    - "swapr"
    - "pancake"
    - "sparta-dex"
    - "mmf"
    - "arbswap-amm"
    - "crowdswap-v2"
    - "balancer-v2-weighted"
    - "balancer-v2-stable"
    - "balancer-v2-composable-stable"
    - "balancer-v3-weighted"
    - "balancer-v3-stable"
    - "balancer-v3-eclp"
    - "mummy-finance"
    - "gyroscope-2clp"
    - "gyroscope-3clp"
    - "gyroscope-eclp"
    - "curve-stable-plain"
    - "uniswap"
    - "curve-stable-ng"
    - "kyberswap-limit-order-v2"
    - "curve-tricrypto-ng"
    - "curve-stable-meta-ng"
    - "curve-lending"
    - "uniswapv3"
    - "chronos-v3"
    - "arbidex-v3"
    - "pancake-v3"
    - "mmf-v3"
    - "camelot-v3"
    - "zyberswap-v3"
    - "solidly-v3"
    - "traderjoe-v21"
    - "traderjoe-v20"
    - "pancake-stable"
    - "ramses-v2"
    - "thick"
    - "sushiswap-v3"
    - "e3"
    - "dackie-v2"
    - "woofi-v2"
    - "dackie-v3"
    - "swaap-v2"
    - "dodo-classical"
    - "dodo-dpp"
    - "dodo-dsp"
    - "dodo-dvm"
    - "chronos"
    - "degen-express"
    - "traderjoe-v22"
    - "woofi-v3"
    - "integral"
    - "fluid-vault-t1"
    - "fluid-dex-t1"
    - "bebop"
    - "dexalot"
    - "clipper"
    - "deltaswap-v1"
    - "maverick-v2"
    - "pmm-1"
    - "lo1inch"
    - "etherfi-ebtc"
    - "uniswap-v4"
    - "sky-psm"
    - "overnight-usdp"
    - "pmm-2"
    - "mimswap"
    - "native-v3"
    - "erc4626"
  excludedSourcesByClient: &excludedSourcesByClient
  featureFlags:
  maxThresholdAmountInUSD: &maxThresholdAmountInUSD 100000000
  getBestPoolsOptions: &getBestPoolsOptions
    directPoolsCount: 100
    whitelistPoolsCount: 500
    tokenInPoolsCount: 200
    tokenOutPoolCount: 200
    amplifiedTvlDirectPoolsCount: 50
    amplifiedTvlWhitelistPoolsCount: 200
    amplifiedTvlTokenInPoolsCount: 100
    amplifiedTvlTokenOutPoolCount: 100
    amountInThreshold: 10000
  dexUseAEVM: &dexUseAEVM
    maverick-v2: true
    uniswap-v4: true
  useAEVM: &useAEVM false
  alphaFeeConfig: &alphaFeeConfig
    reductionConfig:
      reductionFactorInBps:
        uniswap-v4-kem: 9000
        uniswap-v4-fairflow: 9000
        pmm-1: 5000
        pmm-2: 5000
      maxThresholdPercentageInBps: 8000
      minDifferentThresholdUSD: 0.005
      minDifferentThresholdBps: 20
      defaultAlphaFeePercentageBps: 100
    ttl: 600s
  aggregatorTransactionTopic: &aggregatorTransactionTopic "routeSummary"
  liquidityScoreInputFileName: &liquidityScoreInputFileName "./scores.csv"
  liquidityTradesDataFileName: &liquidityTradesDataFileName "./trade_data.txt"
  logError: &logError false
  setsNeededTobeIndexed: &setsNeededTobeIndexed
    whitelist-whitelist: true
    whitelist-token: false
    token-whitelist: false
    direct: false
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: debug
  enableConsole: true
  enableJSONFormat: true
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
pregenRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolEventRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
kafka:
  enable: false
  addresses: "localhost:9092"
  useAuthentication: false
  username:
  password:
  prefix: *chainName
  separator: "."
featureFlags:
  useOptimizedSPFA: false
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
reloadConfig:
  httpUrl:
  interval: 10s
  serviceName: "aggregator"
  chainID: *chainId
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
encoder:
  chainId: *chainId
  routerAddress: *routerAddress
  executorAddress: *executorAddress
  executorV2Address: 0x36C3253C0F1f76F0831a2B187CEA2679F95BC7BE
  opPrivateKey:
  psWallet: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
  isPositiveSlippageEnabled: true
  minimumPSThreshold: 1000000
  executorAddressByClientID:
  partnerPositiveSlippageInfo:
    tritium-research:
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      randomReturnAmountInflation: 0.00006
    llamaswap:
      receiver:
      percent:
      feeMode:
      feeSharingAddress:
    kyberswap:
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      feeReferralAddress: 0xb826162fbeb7c631d1bfb5fbff8b77442432b826
    kyberswap-earn:
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      feeReferralAddress: 0xb826162fbeb7c631d1bfb5fbff8b77442432b826
    unibot-tg:
      receiver: 0x0000000000000000000000000000000000000001
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
    bitgetswap:
      receiver: 0x0000000000000000000000000000000000000003
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      feeReferralAddress:
    app_safe_global:
      receiver:
      feeSharingAddress: 0x55602F3057be52BFB6F98fFE799CFDec58Af5130
useCase:
  getRoute:
    chainId: *chainId
    routerAddress: *routerAddress
    availableSources: *availableSources
    excludedSourcesByClient: *excludedSourcesByClient
    defaultPoolsIndex: composite
    salt: &salt
    aggregator:
      whitelistedTokenSet: *whitelistedTokenSet
      getBestPoolsOptions: *getBestPoolsOptions
      finderOptions:
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsInFallbackRoute: 5
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: *maxThresholdAmountInUSD
        isHillClimbEnabled: false
        hillClimbDistributionPercent: 1
        hillClimbIteration: 2
        hillClimbMinPartUSD: 500
        isPathGeneratorEnabled: false
        useAEVMRemoteFinder: &useAEVMRemoteFinder false
        remoteUseAEVMPool: false
        localUseAEVMPool: false
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30s
        - amount: 2
          ttl: 10s
        - amount: 5
          ttl: 10s
        - amount: 10
          ttl: 10s
        - amount: 11
          ttl: 30s
        - amount: 15
          ttl: 10s
        - amount: 20
          ttl: 10s
        - amount: 22
          ttl: 30s
        - amount: 25
          ttl: 10s
        - amount: 30
          ttl: 10s
        - amount: 33
          ttl: 30s
        - amount: 35
          ttl: 10s
        - amount: 40
          ttl: 10s
        - amount: 44
          ttl: 30s
        - amount: 45
          ttl: 10s
        - amount: 50
          ttl: 10s
        - amount: 55
          ttl: 30s
        - amount: 60
          ttl: 10s
        - amount: 66
          ttl: 30s
        - amount: 70
          ttl: 10s
        - amount: 77
          ttl: 30s
        - amount: 80
          ttl: 10s
        - amount: 88
          ttl: 30s
        - amount: 90
          ttl: 10s
        - amount: 99
          ttl: 30s
        - amount: 100
          ttl: 10s
        - amount: 500
          ttl: 10s
        - amount: 1000
          ttl: 10s
        - amount: 10000
          ttl: 10s
        - amount: 100000
          ttl: 10s
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10s
        - amountUSDLowerBound: 101
          ttl: 10s
        - amountUSDLowerBound: 500
          ttl: 10s
        - amountUSDLowerBound: 1001
          ttl: 10s
        - amountUSDLowerBound: 2000
          ttl: 10s
        - amountUSDLowerBound: 5000
          ttl: 10s
        - amountUSDLowerBound: 10000
          ttl: 10s
      ttlByAmountRange:
        - amountLowerBound: "0"
          ttl: 30s
        - amountLowerBound: "2e17"
          ttl: 20s
        - amountLowerBound: "1e18"
          ttl: 10s
      priceImpactThreshold: 0.005
      shrinkFuncName: "round"
      shrinkDecimalBase: 10
      shrinkFuncPowExp: 0.7
      shrinkFuncLogPercent: 1.01
      enableNewCacheKeyGenerator: false
      shrinkAmountInConfigs:
        - shrinkFuncName: "logarithm"
          shrinkFuncConstant: 1.1
        - shrinkFuncName: "logarithm"
          shrinkFuncConstant: 1.3
        - shrinkFuncName: "logarithm"
          shrinkFuncConstant: 1.5
      shrinkAmountInThreshold: 100000
      minAmountInUSD: 0.9
    safetyQuoteConfig:
      excludeOneSwapEnable: true
      factor:
        Default: 0
        Converter: 0
        StrictlyStable: 0
        Stable: 0.5
        Correlated: 1.5
        LowSlippage: 3
        NormalSlippage: 10
        HighSlippage: 50
      whitelistedClient:
    alphaFeeConfig: *alphaFeeConfig
  getCustomRoute:
    aggregator:
      finderOptions:
        maxHops: 5
  buildRoute:
    chainId: *chainId
    forceSourceByIp:
      '47_130_37_231': tritium-research
      '52_74_71_138': tritium-research
    validateChecksumBySource:
      'tritium-research': true
    salt: *salt
    rfq:
      kyberswap-limit-order-v2:
        handler: limit-order
        properties:
          chainID: *chainId
          limitOrderHTTPUrl: http://limit-order.pre-release-patch1-cluster.gke.production.internal
      swaap-v2:
        handler: swaap-v2
        properties:
          http:
            api_key:
            base_url: "https://api.swaap.finance"
            timeout: 10s
            retry_count: 3
      hashflow-v3:
        handler: hashflow-v3
        properties:
          http:
            api_key:
            base_url: "https://api.hashflow.com"
            source: kyber
            timeout: 3s
            retry_count: 3
      bebop:
        handler: bebop
        properties:
          http:
            name:
            authorization:
            base_url: "https://api.bebop.xyz/pmm/arbitrum"
            timeout: 10s
            retry_count: 3
      dexalot:
        handler: dexalot
        properties:
          http:
            api_key:
            upscale_percent:
            base_url: "https://api.dexalot.com"
            timeout: 10s
            retry_count: 3
      clipper:
        handler: clipper
        properties:
          http:
            basic_auth_key:
            base_url: "https://api.clipper.exchange"
            timeout: 10s
            retry_count: 3
      pmm-1:
        handler: mx-trading
        properties:
          router: 0x111111125421ca6dc452d289314280a0f8842a65
          http:
            base_url: "http://ec2-13-212-180-71.ap-southeast-1.compute.amazonaws.com:6061"
            timeout: 10s
            retry_count: 3
      uniswap-v4-kem:
        handler: uniswap-v4-kem
        properties:
          maxAmountInFactor: 1.2
          expiry: 180000000000 # 3m
          signerPrivateKey:
      uniswap-v4-fairflow:
        handler: uniswap-v4-fairflow
        properties:
          maxAmountInFactor: 1.2
          expiry: 180000000000 # 3m
          signerPrivateKey:
      pmm-2:
        handler: onebit
        properties:
          http:
            base_url: "https://kyber-arbi.myeth.top"
            timeout: 10s
            retry_count: 3
    faultyPools:
      minSlippageThreshold: 1000
      whitelistedTokenSet: *whitelistedTokenSet
      expireTime: 15m
      slippageConfigByGroup:
        stable:
          buffer: 1
          minThreshold: 50
        correlated:
          buffer: 5
          minThreshold: 100
        default:
          buffer: 50
          minThreshold: 500
    rfqAcceptableSlippageFraction: 1000
    faultyPoolDetectorDisabled: false
    publisher:
      aggregatorTransactionTopic: *aggregatorTransactionTopic
    alphaFeeConfig: *alphaFeeConfig
    clientRefCode:
      bitgetswap: bitget

  poolFactory:
    chainId: *chainId
    useAEVM: *useAEVM
    dexUseAEVM: *dexUseAEVM
  poolManager:
    availableSources: *availableSources
    blacklistedPoolSet: *blacklistedPoolSet
    blackListRenewalInterval: 30s
    faultyPoolsRenewalInterval: 5s
    capacity: 1000000
    poolRenewalInterval: 3s
    featureFlags:
    useAEVMRemoteFinder: *useAEVMRemoteFinder
    faultyPoolsExpireThreshold: 3s
  indexPools:
    whitelistedTokenSet: *whitelistedTokenSet
    chunkSize: 3000
    maxGoroutines: 0
    enableRankByNative: false
    maxDirectIndexLenForZeroTvl: 10
  trackExecutor:
    subgraphURL: https://api.studio.thegraph.com/query/101985/kyberswap-aggregator-arbitrum/version/latest
    startBlock: 334152409
  tradeDataGenerator:
    exportFailedTrade: false
    failedFileName: "./failed_trade_data.txt"
    chainName: *chainName
    whitelistedTokenSet: *whitelistedTokenSet
    blacklistedPoolSet: *blacklistedPoolSet
    chunkSize: 1000
    useAEVM: *useAEVM
    dexUseAEVM:
    minDataPointNumber: 6
    maxDataPointNumber: 12
    setsNeededTobeIndexed: *setsNeededTobeIndexed
    maxTokensLen: 6
    availableSources: *availableSources
    logError: *logError
    poolHasManyTokensDefaultScore: 1000
  updateLiquidityScore:
    meanType: "geometric"
    getBestPoolsOptions: *getBestPoolsOptions
job:
  indexPools:
    forceScanAllEveryNth: 10
    interval: 2s
    poolEvent:
      consumerConfig:
        prefix: *chainName
        stream: "pool_events"
        group: "router_indexPools"
        key: "message"
        block: 300ms
        count: 100
        bufferSize: 20
        ackBufferSize: 10
      batchRate: 700ms
      batchSize: 100
      retryInterval: 5s
  updateSuggestedGasPrice:
    interval: 15s
  trackExecutorBalance:
    interval: 1h
  liquidityScoreIndexPools:
    env: *env
    batchSize: 200
    interval: 1h
    successedFileName: *liquidityTradesDataFileName
    liquidityScoreInputFileName: *liquidityScoreInputFileName
    liquidityScoreCalcScript: "./cmd/liquidityscore/main.py"
    targetFactorEntropy: 0.995
    logError: *logError
    poolEvent:
      consumerConfig:
        prefix: *chainName
        stream: "pool_events"
        group: "router_liqIndexPools"
        key: "message"
        block: 300ms
        count: 200
        bufferSize: 20
        ackBufferSize: 10
      batchRate: 700ms
      batchSize: 100
      retryInterval: 5s
  updateL1Fee:
    interval: 2s
repository:
  gas:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 5000
      maxCost: 500
      bufferItems: 64
      suggestedGasPrice:
        cost: 1
        ttl: 2m
  pool:
    redis:
      prefix: *chainName
      maxFaultyPoolSize: 500
    ristretto:
      numCounters: 40000
      maxCost: 4000
      bufferItems: 64
      faultyPools:
        cost: 1
        ttl: 5s
      faultyIndexPools:
        cost: 1
        ttl: 30m
  onchainprice:
    grpc:
      base_url: onchain-price.pre-release-cluster.gke.production.internal:80
      timeout: 300ms
      insecure: true
      client_id: router-service
    ristretto:
      numCounters: 20000
      maxCost: 2000
      bufferItems: 64
      price:
        cost: 1
        ttl: 1m
  poolService:
    baseUrl: "0.0.0.0:10443"
    insecure: true
    timeout: 100ms
    chainId: *chainId
  token:
    redis:
      prefix: *chainName
    ristretto:
      chainId: *chainId
      whitelistedTokenSet: *whitelistedTokenSet
      token:
        numCounters: 20000
        maxCost: 2000
        bufferItems: 64
        cost: 1
        ttl: 1800s
      tokenInfo:
        numCounters: 20000
        maxCost: 2000
        bufferItems: 64
        cost: 1
        ttl: 1800s
    http:
      timeout: 5s
      baseUrl: "http://token-catalog-api.pre-release-cluster.gke.production.internal:80"
  poolRank:
    redis:
      prefix: *chainName
    setsNeededTobeIndexed: *setsNeededTobeIndexed
  route:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 10000
      maxCost: 1000
      bufferItems: 64
      prefix: *chainName
      route:
        cost: 1
        ttl: 10s
  blackjack:
    grpcClient:
      baseURL: blackjack.core-cluster.gke.production.internal:80
      insecure: true
      timeout: 100ms
  erc20balanceslot:
    redis:
      prefix: *chainName
  alphaFee:
    redis:
      prefix: *chainName
      separator: ":"
      ttl: 600s
validator:
  slippageValidatorConfig:
    slippageToleranceGte: 0
    slippageToleranceLte: 5000
  buildRouteParams:
    blacklistedRecipientSet:
  getRouteEncodeParams:
    blacklistedRecipientSet:
aevmEnabled: false
aevm:
  serverUrl: "localhost:8246"
  publishingPoolsUrls:
  retryOnTimeOutMs: 500
  findRouteRetryOnTimeOutMs: 1000
  maxRetry: 3
  rpc: "http://localhost:8545"
  simulationWallet: "0x19767032471665df0fd7f6160381a103ece6261a"
  useHoldersListAsFallback: false
  tokenHoldersRedis:
    addresses:
    masterName: ""
    dbNumber: 0
    password: ""
    prefix: *chainName
    readTimeout: 3s
    writeTimeout: 3s
    readOnly: false
    routeRandomly: false
  cachedHoldersListTTLSec: 30
  predefinedBalanceSlots:
bundledRouteEnabled: false
