env: "production"
pprof: false
http:
  bindAddress: ":8080"
  mode: release #(debug,release,test)
  prefix: /ethereum
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainId: &chainId 1
  chainName: &chainName ethereum
  rpc: "https://ethereum.kyberengineering.io"
  multicallAddress: "0xcA11bde05977b3631167028862bE2a173976CA11"
  executorAddress: &executorAddress "0xf081470f5C6FBCCF48cC4e5B82Dd926409DcdD67"
  routerAddress: &routerAddress "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5"
  whitelistedTokenSet: &whitelistedTokenSet
    0xf951e335afb289353dc249e82926178eac7ded78: true # swETH
    0xb50721bcf8d664c30412cfbc6cf7a15145234ad1: true # ARB
    0x1a7e4e63778b4f12a199c062f3efdd288afcbce8: true # EURA
    0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2: true # WETH
    0xdac17f958d2ee523a2206206994597c13d831ec7: true # USDT
    0x6b175474e89094c44da98b954eedeac495271d0f: true # DAI
    0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48: true # USDC
    0x2260fac5e5542a773aa44fbcfedf7c193bc2c599: true # WBTC
    0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202: true # KNC
    0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0: true # wstETH
    0xae7ab96520de3a18e5e111b5eaab095312d7fe84: true # stETH
    0x467719ad09025fcc6cf6f8311755809d45a5e5f3: true # AXL
    0x06b44daa59abd49ac739879bd43a422ed1bd4f7a: true # dBSGG
    0x853d955acef822db058eb8505911ed77f175b99e: true # FRAX
    0xac3e018457b222d93114458476f3e3416abbe38f: true # sfrxETH
    0xae78736cd615f374d3085123a210448e74fc6393: true # rETH
    0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9: true # AAVE
    0xbe9895146f7af43049ca1c1ae358b0541ea49704: true # cbETH
    0x455e53cbb86018ac2b8092fdcd39d8444affc3f6: true # POL
    0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0: true # MATIC
    0xa35b1b31ce002fbf2058d22f30f95d405200a15b: true # ETHx
    0x5de8ab7e27f6e7a1fff3e5b337584aa43961beef: true # SDEX
    0x83f20f44975d03b1b09e64809b757c47f942beea: true # sDAI
    0xe07f9d810a48ab5c3c914ba3ca53af14e4491e8a: true # GYD
    0xf939e0a03fb07f59a73314e73794be0e57ac1b4e: true # crvUSD
    0x79c58f70905f734641735bc61e45c19dd9ad60bc: true # USDC-DAI-USDT
    0x95d8bf2f57cf973251972b496dc6b1d9c6b5bce3: true # BLUE
    0x4c9edd5852cd905f086c759e8383e09bff1e68b3: true # USDe
    0x35fa164735182de50811e8e2e824cfb9b6118ac2: true # eETH
    0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee: true # weETH
    0x808507121b80c02388fad14726482e061b8da827: true # PENDLE
    0x73a15fed60bf67631dc6cd7bc5b6e8da8190acf5: true # USD0
    0xa1290d69c65a6fe4df752f95823fae25cb99e5a7: true # rsETH
    0x7a56e1c57c7475ccf742a1832b028f0456652f97: true # SolvBTC
    0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2: true # MKR
    0x57e114b691db790c35207b2e685d4a43181e6061: true # ENA
    0x56072c95faa701256059aa122697b133aded9279: true # SKY
    0xdc035d45d973e3ec169d2276ddab16f1e407384f: true # USDS
  blacklistedPoolSet: &blacklistedPoolSet
    0x3dabc75ffd70695852da101b0c0d018781320551: true
    0xf6a8e47daeeddcce297e7541523e27df2f167bf3: true
  availableSources: &availableSources
    - "mkr-sky"
    - "dai-usds"
    - "ambient"
    - "balancer-v1"
    - "balancer-v2-composable-stable"
    - "balancer-v2-stable"
    - "balancer-v2-weighted"
    - "bancor-v3"
    - "bedrock-unieth"
    - "blueprint"
    - "crowdswap-v2"
    - "curve"
    - "curve-stable-meta-ng"
    - "curve-stable-ng"
    - "curve-stable-plain"
    - "curve-tricrypto-ng"
    - "curve-twocrypto-ng"
    - "defiswap"
    - "dodo-classical"
    - "dodo-dpp"
    - "dodo-dsp"
    - "dodo-dvm"
    - "ethena-susde"
    - "etherfi-eeth"
    - "etherfi-weeth"
    - "fraxswap"
    - "gyroscope-2clp"
    - "gyroscope-3clp"
    - "gyroscope-eclp"
    - "kyber-pmm"
    - "kyberswap"
    - "kyberswap-limit-order-v2"
    - "kyberswap-static"
    - "lido"
    - "lido-steth"
    - "maker-psm"
    - "maker-savingsdai"
    - "maverick-v1"
    - "pancake"
    - "pancake-v3"
    - "pol-matic"
    - "puffer-pufeth"
    - "renzo-ezeth"
    - "rocketpool-reth"
    - "shibaswap"
    - "smardex"
    - "integral"
    - "solidly-v2"
    - "solidly-v3"
    - "sushiswap"
    - "sushiswap-v3"
    - "swaap-v2"
    - "swell-rsweth"
    - "swell-sweth"
    - "synapse"
    - "traderjoe-v21"
    - "uniswap"
    - "uniswapv3"
    - "verse"
    - "wagmi"
    - "wombat"
    - "maverick-v2"
    - "lite-psm"
    - "fluid-vault-t1"
    - "fluid-dex-t1"
    - "usd0pp"
    - "hashflow-v3"
    - "bancor-v21"
    - "native-v1"
    - "bebop"
    - "wbeth"
    - "oeth"
    - "primeeth"
    - "staderethx"
    - "uniswap-v1"
    - "frxeth"
    - "meth"
    - "clipper"
    - "deltaswap-v1"
    - "sfrxeth"
    - "sfrxeth-convertor"
    - "ondo-usdy"
    - "ringswap"
    - "etherfi-vampire"
    - "mx-trading"
    - "lo1inch"
  excludedSourcesByClient: &excludedSourcesByClient
  featureFlags:
    isAEVMEnabled: false
    isLiquidityScoreEnable: true
    isRouteCachedEnable: false
  maxThresholdAmountInUSD: &maxThresholdAmountInUSD 100000000
  getBestPoolsOptions: &getBestPoolsOptions
    directPoolsCount: 100
    whitelistPoolsCount: 500
    tokenInPoolsCount: 200
    tokenOutPoolCount: 200
    amplifiedTvlDirectPoolsCount: 50
    amplifiedTvlWhitelistPoolsCount: 200
    amplifiedTvlTokenInPoolsCount: 100
    amplifiedTvlTokenOutPoolCount: 100
    amountInThreshold: 10000
  useAEVM: &useAEVM false
  dexUseAEVM: &dexUseAEVM
    uniswap: false
    uniswapv3: false
    liquiditybook-v20: false
    liquiditybook-v21: false
    ambient: true
    maverick-v2: true
  alphaFeeConfig: &alphaFeeConfig
    reductionConfig:
      reductionFactorInBps:
        kyber-pmm: 5000
      maxThresholdPercentageInBps: 9900
      minDifferentThresholdUSD: 0.01
      minDifferentThresholdBps: 1000
      defaultAlphaFeePercentageBps: 0.1651
    ttl: 600s
  aggregatorTransactionTopic: &aggregatorTransactionTopic "routeSummary"

log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password:
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
pregenRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolEventRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
kafka:
  enable: true
  addresses: "localhost:9092"
  useAuthentication: false
  username:
  password:
  prefix: *chainName
  separator: "."
ddAgentHost: ""
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
reloadConfig:
  httpUrl:
  interval: 10s
  serviceName: "aggregator"
  chainID: *chainId
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
encoder:
  chainId: *chainId
  executorAddress: *executorAddress
  routerAddress: *routerAddress
  isPositiveSlippageEnabled: true
  minimumPSThreshold: 1000000
  executorAddressByClientID:
    unibot-tg: 0x1BC5cF80f308518f000dDE4c8f8139268aA014DB
    llamaswap: *executorAddress
    kyberswap: *executorAddress
    kyberswap-earn: *executorAddress
  partnerPositiveSlippageInfo:
    tritium-research:
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      randomReturnAmountInflation: 0.0006
    llamaswap:
      receiver:
      percent:
      feeMode:
      feeSharingAddress:
    kyberswap:
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      feeReferralAddress: 0xb826162fbeb7c631d1bfb5fbff8b77442432b826
    kyberswap-earn:
      feeSharingAddress: 0x4f82e73edb06d29ff62c91ec8f5ff06571bdeb29
      feeReferralAddress: 0xb826162fbeb7c631d1bfb5fbff8b77442432b826
useCase:
  getRoute:
    chainId: *chainId
    routerAddress: *routerAddress
    availableSources: *availableSources
    excludedSourcesByClient: *excludedSourcesByClient
    defaultPoolsIndex: composite
    salt: &salt
    aggregator:
      whitelistedTokenSet: *whitelistedTokenSet
      getBestPoolsOptions: *getBestPoolsOptions
      dexUseAEVM: *dexUseAEVM
      finderOptions: &finderOptions
        type: retry
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsInFallbackRoute: 5
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: *maxThresholdAmountInUSD
        fullAmountGeneratePathsPrice: 44999
        isHillClimbEnabled: false
        hillClimbDistributionPercent: 1
        hillClimbIteration: 2
        hillClimbMinPartUSD: 500
        isPathGeneratorEnabled: false
        useAEVMRemoteFinder: &useAEVMRemoteFinder false
        remoteUseAEVMPool: false
        localUseAEVMPool: false
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30s
        - amount: 2
          ttl: 10s
        - amount: 5
          ttl: 10s
        - amount: 10
          ttl: 10s
        - amount: 11
          ttl: 30s
        - amount: 15
          ttl: 10s
        - amount: 20
          ttl: 10s
        - amount: 22
          ttl: 30s
        - amount: 25
          ttl: 10s
        - amount: 30
          ttl: 10s
        - amount: 33
          ttl: 30s
        - amount: 35
          ttl: 10s
        - amount: 40
          ttl: 10s
        - amount: 44
          ttl: 30s
        - amount: 45
          ttl: 10s
        - amount: 50
          ttl: 10s
        - amount: 55
          ttl: 30s
        - amount: 60
          ttl: 10s
        - amount: 66
          ttl: 30s
        - amount: 70
          ttl: 10s
        - amount: 77
          ttl: 30s
        - amount: 80
          ttl: 10s
        - amount: 88
          ttl: 30s
        - amount: 90
          ttl: 10s
        - amount: 99
          ttl: 30s
        - amount: 100
          ttl: 10s
        - amount: 500
          ttl: 10s
        - amount: 1000
          ttl: 10s
        - amount: 10000
          ttl: 10s
        - amount: 100000
          ttl: 10s
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10s
        - amountUSDLowerBound: 5
          ttl: 10s
        - amountUSDLowerBound: 21
          ttl: 10s
        - amountUSDLowerBound: 101
          ttl: 10s
        - amountUSDLowerBound: 500
          ttl: 10s
        - amountUSDLowerBound: 1001
          ttl: 10s
        - amountUSDLowerBound: 2000
          ttl: 10s
        - amountUSDLowerBound: 5000
          ttl: 10s
        - amountUSDLowerBound: 10000
          ttl: 10s
      ttlByAmountRange:
        - amountLowerBound: "0"
          ttl: 10s
      priceImpactThreshold: 0.005
      shrinkFuncName: "decimal"
      shrinkDecimalBase: 8
      shrinkFuncPowExp: 0.7
      shrinkFuncLogPercent: 1.01
      enableNewCacheKeyGenerator: false
      shrinkAmountInConfigs:
        - shrinkFuncName: "logarithm"
          shrinkFuncConstant: 1.3
        - shrinkFuncName: "logarithm"
          shrinkFuncConstant: 1.5
        - shrinkFuncName: "logarithm"
          shrinkFuncConstant: 1.8
      shrinkAmountInThreshold: 100000
      minAmountInUSD: 0.9
    safetyQuoteConfig:
      excludeOneSwapEnable: true
      tokenGroupConfig:
      factor:
        Default: 0
        Converter: 0
        StrictlyStable: 0
        Stable: 0.5
        Correlated: 1.5
        LowSlippage: 3
        NormalSlippage: 10
        HighSlippage: 50
      whitelistedClient:
    alphaFeeConfig: *alphaFeeConfig
  getCustomRoute:
    aggregator:
      finderOptions:
        maxHops: 5
  buildRoute:
    chainId: *chainId
    salt: *salt
    rfq:
      kyber-pmm:
        handler: kyber-pmm
        properties:
          http:
            base_url: "https://kyberswap.knreserve.com"
            timeout: 5s
            retry_count: 3
          rfq_contract_address: "0x7A819Fa46734a49D0112796f9377E024c350FB26"
      kyberswap-limit-order-v2:
        handler: limit-order
        properties:
          chainID: *chainId
          limitOrderHTTPUrl: http://limit-order.pre-release-patch1-cluster.gke.production.internal
      swaap-v2:
        handler: swaap-v2
        properties:
          http:
            api_key:
            base_url: "https://api.swaap.finance"
            timeout: 5s
            retry_count: 3
      hashflow-v3:
        handler: hashflow-v3
        properties:
          http:
            api_key:
            base_url: "https://api.hashflow.com"
            source: kyber
            timeout: 3s
            retry_count: 3
          excludeMarketMakers:
            - mm22
      native-v1:
        handler: native-v1
        properties:
          http:
            api_key:
            base_url: "https://newapi.native.org"
            timeout: 5s
            retry_count: 3
      bebop:
        handler: bebop
        properties:
          http:
            name:
            authorization:
            base_url: "https://api.bebop.xyz/pmm/ethereum"
            timeout: 10s
            retry_count: 3
      clipper:
        handler: clipper
        properties:
          http:
            basic_auth_key:
            base_url: "https://api.clipper.exchange"
            timeout: 10s
            retry_count: 3
      mx-trading:
        handler: mx-trading
        properties:
          router: 0x111111125421ca6dc452d289314280a0f8842a65
          http:
            base_url: "https://lht6f850if.execute-api.ap-southeast-1.amazonaws.com"
            timeout: 10s
            retry_count: 3
    faultyPools:
      minSlippageThreshold: 1000
      whitelistedTokenSet: *whitelistedTokenSet
    rfqAcceptableSlippageFraction: 1000
    faultyPoolDetectorDisabled: false
    publisher:
      aggregatorTransactionTopic: *aggregatorTransactionTopic
    alphaFeeConfig: *alphaFeeConfig

  poolFactory:
    chainId: *chainId
    useAEVM: *useAEVM
    dexUseAEVM: *dexUseAEVM
    addressesByDex:
      uniswap:
        router-address: 0x7a250d5630b4cf539739df2c5dacb4c659f2488d
      uniswapv3:
        router-address: 0xe592427a0aece92de3edee1f18e0157c05861564
  poolManager:
    blacklistedPoolSet: *blacklistedPoolSet
    blackListRenewalInterval: 30s
    faultyPoolsRenewalInterval: 5s
    capacity: 1000000
    poolRenewalInterval: 12s
    featureFlags:
    useAEVMRemoteFinder: *useAEVMRemoteFinder
    faultyPoolsExpireThreshold: 3s
    stallingPMMThreshold: 30s
  indexPools:
    whitelistedTokenSet: *whitelistedTokenSet
    chunkSize: 3000
    maxGoroutines: 0
    enableRankByNative: false
    maxDirectIndexLenForZeroTvl: 10
  generateBestPaths:
    getBestPoolsOptions: *getBestPoolsOptions
    spfaFinderOptions: *finderOptions
    whitelistedTokens: *whitelistedTokenSet
    availableSources: *availableSources
    blacklistedPools:
    configGeneratorDataTtl: 12h
    pathGeneratorDataTtl: 2h
    maintainingInterval: 360s
    chainId: *chainId
  trackExecutor:
    subgraphURL: https://api.studio.thegraph.com/query/101985/kyberswap-aggregator-ethereum/version/latest
  tradeDataGenerator:
    whitelistedTokenSet: *whitelistedTokenSet
    blacklistedPoolSet: *blacklistedPoolSet
    chunkSize: 200
    useAEVM: *useAEVM
    dexUseAEVM: *dexUseAEVM
    minDataPointNumber: 6
    maxDataPointNumber: 12
    availableSources: *availableSources
  updateLiquidityScore:
    inputFileName: "./scores.csv"
    meanType: "geometric"
    getBestPoolsOptions: *getBestPoolsOptions
job:
  indexPools:
    forceScanAllEveryNth: 10
    interval: 2s
    poolEvent:
      consumerConfig:
        prefix: *chainName
        stream: "pool_events"
        group: "router_indexPools"
        key: "message"
        block: 300ms
        count: 100
        bufferSize: 20
        ackBufferSize: 10
      batchRate: 700ms
      batchSize: 100
      retryInterval: 5s
  updateSuggestedGasPrice:
    interval: 15s
  trackExecutorBalance:
    interval: 1h
  generateBestPaths:
    interval: 360s
  liquidityScoreIndexPools:
    batchSize: 200
    interval: 1h
    successedFileName: "./trade_data.txt"
    failedFileName: "./failed_trade_data.txt"
    liquidityScoreCalcScript: "./cmd/liquidityscore/main.py"
    exportFailedTrade: false
repository:
  gas:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 5000
      maxCost: 500
      bufferItems: 64
      suggestedGasPrice:
        cost: 1
        ttl: 15s
  pool:
    redis:
      prefix: *chainName
      maxFaultyPoolSize: 500
    ristretto:
      numCounters: 40000
      maxCost: 4000
      bufferItems: 64
      faultyPools:
        cost: 1
        ttl: 5s
      faultyIndexPools:
        cost: 1
        ttl: 30m
  onchainprice:
    grpc:
      base_url: onchain-price.pre-release-cluster.gke.production.internal:80
      timeout: 300ms
      insecure: true
      client_id: router-service
    ristretto:
      numCounters: 20000
      maxCost: 2000
      bufferItems: 64
      price:
        cost: 1
        ttl: 1m
  poolService:
    baseUrl: "0.0.0.0:10443"
    insecure: true
    timeout: 100ms
    chainId: *chainId
  token:
    redis:
      prefix: *chainName
    goCache:
      expiration: -1
      cleanupInterval: -1
      chainId: *chainId
    http:
      timeout: 5s
      baseUrl: "http://token-catalog-api.pre-release-cluster.gke.production.internal:80"
  poolRank:
    redis:
      prefix: *chainName
  route:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 10000
      maxCost: 1000
      bufferItems: 64
      prefix: *chainName
      route:
        cost: 1
        ttl: 10s
  blackjack:
    grpcClient:
      baseURL: blackjack.core-cluster.gke.production.internal:80
      insecure: true
      timeout: 100ms
  erc20balanceslot:
    redis:
      prefix: *chainName
  alphaFee:
    redis:
      prefix: *chainName
      separator: ":"
      ttl: 600s
validator:
  slippageValidatorConfig:
    slippageToleranceGte: 0
    slippageToleranceLte: 5000
  buildRouteParams:
    blacklistedRecipientSet:
  getRouteEncodeParams:
    blacklistedRecipientSet:
aevmEnabled: false
aevm:
  serverUrl: "localhost:8246"
  publishingPoolsUrls:
  retryOnTimeOutMs: 500
  findRouteRetryOnTimeOutMs: 1000
  maxRetry: 3
  rpc: "http://localhost:8545"
  simulationWallet: "0x19767032471665df0fd7f6160381a103ece6261a"
  useHoldersListAsFallback: false
  tokenHoldersRedis:
    addresses:
    masterName: ""
    dbNumber: 0
    password: ""
    prefix: *chainName
    readTimeout: 3s
    writeTimeout: 3s
    readOnly: false
    routeRandomly: false
  cachedHoldersListTTLSec: 30
  predefinedBalanceSlots:
    # LIDO token
    0x5a98fcbea516cf06857215779fd812ca3bef1b32:
      token: 0x5a98fcbea516cf06857215779fd812ca3bef1b32
      wallet: 0x19767032471665df0fd7f6160381a103ece6261a
      found: true
      balanceSlot: 0x1d92366e0eb8047c54dfd3b4dbea0f8e23e5b021de7fe643c5e1b27c1a169cf0
      # the first 128 bits is balance = 0x0000ffffffffffffffffffffffffffff (which is large enough)
      # the last 128 bits is block number at which balance is changed
      preferredValue: 0x0000ffffffffffffffffffffffffffff000000000000000000000000010c766a
      extraOverrides:
        # balance history length, must be > 0
        0x5a7df2e997858d39f2aef4861e79c3133f8533d36ea28b6a66fa8b4914908a5a: 0x0000000000000000000000000000000000000000000000000000000000000001
bundledRouteEnabled: false
