env: "develop"
http:
  bindAddress: ":8080"
  mode: release #(debug,release,test)
  prefix: /aurora
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainID: 1313161554
  dataFolder: internal/pkg/data/chain/aurora
  publicRPC: "https://mainnet.aurora.dev"
  rpcs:
    # - "https://aurora.kyberswap.com/v1/mainnet/geth?appId=test-daniel"
    - "https://mainnet.aurora.dev"
  rpc: "https://mainnet.aurora.dev"
  address:
    multicall: '0xBF69a56D35B8d6f5A8e0e96B245a72F735751e54'
    gasToken: '0xc9bdeed33cd01541e1eed10f90519d2c06fe3feb'
    executorAddress: '0x41684b361557E9282E0373CA51260D9331e518C9'
    routerAddress: '0x00555513Acf282B42882420E5e5bA87b44D8fA6E'
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
enableDexes: &enableDexes
  - kyberswap
  - kyberswap-static
#  - kyberswapv2
  - trisolaris
  - wannaswap
  - nearpad
  # - rose
  - dodo
  - curve
cachePoints:
  - amount: 1
    ttl: 30
  - amount: 2
    ttl: 10
  - amount: 5
    ttl: 10
  - amount: 10
    ttl: 10
  - amount: 11
    ttl: 30
  - amount: 15
    ttl: 10
  - amount: 20
    ttl: 10
  - amount: 22
    ttl: 30
  - amount: 25
    ttl: 10
  - amount: 30
    ttl: 10
  - amount: 33
    ttl: 30
  - amount: 35
    ttl: 10
  - amount: 40
    ttl: 10
  - amount: 44
    ttl: 30
  - amount: 45
    ttl: 10
  - amount: 50
    ttl: 10
  - amount: 55
    ttl: 30
  - amount: 60
    ttl: 10
  - amount: 66
    ttl: 30
  - amount: 70
    ttl: 10
  - amount: 77
    ttl: 30
  - amount: 80
    ttl: 10
  - amount: 88
    ttl: 30
  - amount: 90
    ttl: 10
  - amount: 99
    ttl: 30
  - amount: 100
    ttl: 30
  - amount: 500
    ttl: 10
  - amount: 1000
    ttl: 30
  - amount: 10000
    ttl: 30
  - amount: 100000
    ttl: 30
cacheRanges:
  - fromUSD: 0
    toUSD: 100
    ttl: 10
  - fromUSD: 101
    toUSD: 500
    ttl: 10
  - fromUSD: 500
    toUSD: 1000
    ttl: 10
  - fromUSD: 1001
    toUSD: 2000
    ttl: 15
  - fromUSD: 2000
    toUSD: 5000
    ttl: 15
  - fromUSD: 5000
    toUSD: 10000
    ttl: 15
  - fromUSD: 10000
    toUSD: -1
    ttl: 15
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: "aurora"
  readTimeout: 3s
  writeTimeout: 3s
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: "aurora"
  readTimeout: 3s
  writeTimeout: 3s
ddAgentHost: ""
featureFlags:
  useOptimizedSPFA: false
enableGRPC: false
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
tokenCatalog:
  httpUrl: ""
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: 1313161554
whitelistedTokens:
  - name: "Aurora"
    symbol: "AURORA"
    address: "0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79"
    decimals: 18
    cgkId: "aurora"
  - name: "Near"
    symbol: "NEAR"
    address: "0xC42C30aC6Cc15faC9bD938618BcaA1a1FaE8501d"
    decimals: 24
    cgkId: "near"
  - name: "Wrapped Ether"
    symbol: "WETH"
    address: "0xC9BdeEd33CD01541e1eeD10f90519d2C06Fe3feB"
    decimals: 18
    cgkId: "ethereum"
  - name: "Tether USD"
    symbol: "USDT"
    address: "0x4988a896b1227218e4A686fdE5EabdcAbd91571f"
    decimals: 6
    cgkId: "tether"
  - name: "Dai Stablecoin"
    symbol: "DAI"
    address: "0xe3520349F477A5F6EB06107066048508498A291b"
    decimals: 18
    cgkId: "dai"
  - name: "USD Coin"
    symbol: "USDC"
    address: "0xB12BFcA5A55806AaF64E99521918A4bf0fC40802"
    decimals: 6
    cgkId: "usd-coin"
  - name: "Wrapped BTC"
    symbol: "WBTC"
    address: "0xF4eB217Ba2454613b15dBdea6e5f22276410e89e"
    decimals: 8
    cgkId: "bitcoin"
  - name: "NearPad"
    symbol: "PAD"
    address: "0x885f8CF6E45bdd3fdcDc644efdcd0AC93880c781"
    decimals: 18
    cgkId: "nearpad"
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
blacklistedPools:
encoder:
  chainId: 1313161554
  executorAddress:
  routerAddress:
useCase:
  poolFactory:
  cacheRoute:
  getRoute:
    chainID: 1313161554
    gasTokenAddress: 0xc9bdeed33cd01541e1eed10f90519d2c06fe3feb
    routerAddress:
    availableSources:
      - kyberswap
      - kyberswap-static
      - trisolaris
      - wannaswap
      - nearpad
      - dodo
      - curve
    ammAggregator:
      getBestPoolsOptions:
        directPoolsCount: 100
        whitelistPoolsCount: 500
        tokenInPoolsCount: 200
        tokenOutPoolCount: 200
        amplifiedTvlDirectPoolsCount: 50
        amplifiedTvlWhitelistPoolsCount: 200
        amplifiedTvlTokenInPoolsCount: 100
        amplifiedTvlTokenOutPoolCount: 100
      finderOptions:
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: 100000000
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30
        - amount: 2
          ttl: 10
        - amount: 5
          ttl: 10
        - amount: 10
          ttl: 10
        - amount: 11
          ttl: 30
        - amount: 15
          ttl: 10
        - amount: 20
          ttl: 10
        - amount: 22
          ttl: 30
        - amount: 25
          ttl: 10
        - amount: 30
          ttl: 10
        - amount: 33
          ttl: 30
        - amount: 35
          ttl: 10
        - amount: 40
          ttl: 10
        - amount: 44
          ttl: 30
        - amount: 45
          ttl: 10
        - amount: 50
          ttl: 10
        - amount: 55
          ttl: 30
        - amount: 60
          ttl: 10
        - amount: 66
          ttl: 30
        - amount: 70
          ttl: 10
        - amount: 77
          ttl: 30
        - amount: 80
          ttl: 10
        - amount: 88
          ttl: 30
        - amount: 90
          ttl: 10
        - amount: 99
          ttl: 30
        - amount: 100
          ttl: 10
        - amount: 500
          ttl: 10
        - amount: 1000
          ttl: 10
        - amount: 10000
          ttl: 10
        - amount: 100000
          ttl: 10
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10
        - amountUSDLowerBound: 101
          ttl: 10
        - amountUSDLowerBound: 500
          ttl: 10
        - amountUSDLowerBound: 1001
          ttl: 10
        - amountUSDLowerBound: 2000
          ttl: 10
        - amountUSDLowerBound: 5000
          ttl: 10
        - amountUSDLowerBound: 10000
          ttl: 10
      priceImpactThreshold: 0.005
      shrinkFuncName: "round"
      shrinkFuncPowExp: 0.7
    poolFactory:
      chainID: 1313161554
  indexPools:
    whitelistedTokenSet:
    chunkSize: 3000
job:
  indexPools:
    interval: 2s
  updateSuggestedGasPrice:
    interval: 2s
repository:
  gas:
    redis:
      prefix: aurora
  pool:
    redis:
      prefix: aurora
  price:
    redis:
      prefix: aurora
  token:
    redis:
      prefix: aurora
    goCache:
      expiration: -1
      cleanupInterval: -1
  poolRank:
    redis:
      prefix: aurora
  route:
    redisCache:
      prefix: aurora
      localCacheSize: 1000
      localCacheTtl: 30s
