env: "develop"
http:
  bindAddress: ":8080"
  mode: release #(debug,release,test)
  prefix: /bsc
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainID: 56
  dataFolder: internal/pkg/data/chain/bsc
  publicRPC: "https://bsc-dataseed.binance.org"
  rpcs:
    - "https://bscrpc.com"
  address:
    multicall: '0xed386fe855c1eff2f843b910923dd8846e45c5a4'
    gasToken: '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c'
    executorAddress: '0x41684b361557E9282E0373CA51260D9331e518C9'
    routerAddress: '0x617Dee16B86534a5d792A4d7A62FB491B544111E'
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
enableDexes: &enableDexes
  - kyberswap
  - kyberswap-static
  - kyberswapv2
  - sushiswap
  - oneswap
  - ellipsis
  - nerve
  - apeswap
  - jetswap
  - mdex
  - pancake
  - wault
  - biswap
  - pancake-legacy
  - synapse
  - pantherswap
  - dodo
  - fraxswap
  - kyberswap-limit-order
dexes:
  - id: fraxswap
    handler: fraxswap
    properties:
      factoryAddress: 0xf89e6CA06121B6d4370f4B196Ae458e8b969A011
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 10
      updateReserveBulk: 10
  - id: kyberswap
    handler: dmm
    properties:
      factoryAddress: 0x878dfe971d44e9122048308301f540910bbd934c
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: kyberswap-static
    handler: dmm
    properties:
      factoryAddress: 0x1c758aF0688502e49140230F6b0EBd376d429be5
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: kyberswapv2
    handler: promm
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/kybernetwork/kyberswap-elastic-bsc"
      factoryAddress: 0x5F1dddbf348aC2fbe22a163e30F99F9ECE3DD50a
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      reserveJobInterval: 2s
      updateReserveBulk: 200
  - id: sushiswap
    handler: uniswap
    properties:
      factoryAddress: 0xc35DADB65012eC5796536bD9864eD8773aBc74C4
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: oneswap
    handler: oneswap
    properties:
      factoryAddress: 0xD2891F9a9fDBFfC2DB3Ec9D4194409a7678CBc51
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: ellipsis
    handler: curve
    properties:
      poolPath: "ellipsis/pools.json"
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
  - id: nerve
    handler: nerve
    properties:
      poolPath: "nerve/pools.json"
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
  - id: apeswap
    handler: uniswap
    properties:
      subgraphAPI: "https://graph2.apeswap.finance/subgraphs/name/ape-swap/apeswap-subgraph"
      factoryAddress: "0x0841BD0B734E4F5853f0dD8d7Ea041c241fb0Da6"
      swapFee: 0.002
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: jetswap
    handler: uniswap
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/smartcookie0501/jetswap-subgraph"
      factoryAddress: "0x0eb58e5c8aa63314ff5547289185cc4583dfcbd5"
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: mdex
    handler: uniswap
    properties:
      subgraphAPI: "https://bsc-lite-graph.mdex.one/subgraphs/name/chain/bsc"
      factoryAddress: 0x3CD1C46068dAEa5Ebb0d3f55F6915B10648062B8
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: pancake
    handler: uniswap
    properties:
      subgraphAPI: "https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2"
      factoryAddress: 0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73
      swapFee: 0.0025
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      updateReserveBulk: 200
      trackedReserveKey: "trackedReserveBNB"
  - id: pancake-legacy
    handler: uniswap
    properties:
      factoryAddress: 0xbcfccbde45ce874adcb698cc183debcf17952812
      swapFee: 0.0025
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      updateReserveBulk: 200
      trackedReserveKey: "trackedReserveBNB"
  - id: wault
    handler: uniswap
    properties:
      subgraphAPI: "https://polyinfo.wault.finance/subgraphs/name/WaultFinance/waultswap-subgraph"
      factoryAddress: 0xb42e3fe71b7e0673335b3331b3e1053bd9822570
      swapFee: 0.002
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: biswap
    handler: biswap
    properties:
      swapFee: 0.002
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolBulk: 500
      updateReserveBulk: 200
      factoryAddress: 0x858e3312ed3a876947ea49d572a7c42de08af7ee
  - id: synapse
    handler: synapse
    properties:
      poolPath: "synapse/pools.json"
      reserveJobInterval: 1s
      newPoolJobIntervalSec: 500
      updateReserveBulk: 200
  - id: pantherswap
    handler: uniswap
    properties:
      factoryAddress: "0x670f55c6284c629c23bae99f585e3f17e8b9fc31"
      swapFee: 0.002
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: dodo
    handler: dodo
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/dodoex/dodoex-v2-bsc"
      dodoV1SellHelper: "0x0f859706aee7fcf61d5a8939e8cb9dbb6c1eda33"
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      reserveJobInterval: 2s
      updateReserveBulk: 50
  - id: kyberswap-limit-order
    handler: limit-order
    properties:
      limitOrderHTTPUrl: https://limit-order.stg.kyberengineering.io
      reserveJobInterval: 3s
      newPoolJobIntervalSec: 10
      predefineSupportedPairs:
epsilon: 0.005
cachePoints:
  - amount: 1
    ttl: 30
  - amount: 2
    ttl: 10
  - amount: 5
    ttl: 10
  - amount: 10
    ttl: 10
  - amount: 11
    ttl: 30
  - amount: 15
    ttl: 10
  - amount: 20
    ttl: 10
  - amount: 22
    ttl: 30
  - amount: 25
    ttl: 10
  - amount: 30
    ttl: 10
  - amount: 33
    ttl: 30
  - amount: 35
    ttl: 10
  - amount: 40
    ttl: 10
  - amount: 44
    ttl: 30
  - amount: 45
    ttl: 10
  - amount: 50
    ttl: 10
  - amount: 55
    ttl: 30
  - amount: 60
    ttl: 10
  - amount: 66
    ttl: 30
  - amount: 70
    ttl: 10
  - amount: 77
    ttl: 30
  - amount: 80
    ttl: 10
  - amount: 88
    ttl: 30
  - amount: 90
    ttl: 10
  - amount: 99
    ttl: 30
  - amount: 100
    ttl: 10
  - amount: 500
    ttl: 10
  - amount: 1000
    ttl: 10
  - amount: 10000
    ttl: 10
  - amount: 100000
    ttl: 10
cacheRanges:
  - fromUSD: 0
    toUSD: 100
    ttl: 10
  - fromUSD: 101
    toUSD: 500
    ttl: 10
  - fromUSD: 500
    toUSD: 1000
    ttl: 10
  - fromUSD: 1001
    toUSD: 2000
    ttl: 10
  - fromUSD: 2000
    toUSD: 5000
    ttl: 10
  - fromUSD: 5000
    toUSD: 10000
    ttl: 10
  - fromUSD: 10000
    toUSD: -1
    ttl: 10
redis:
  addresses: localhost:6379
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: "bsc"
  readTimeout: 3s
  writeTimeout: 3s
ddAgentHost: ""
featureFlags:
  useOptimizedSPFA: false
enableGRPC: false
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
tokenCatalog:
  httpUrl: ""
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: 56
whitelistedTokens:
  - name: "Wrapped BNB"
    symbol: "WBNB"
    address: "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"
    decimals: 18
    cgkId: "wbnb"
  - name: "Tether USD"
    symbol: "USDT"
    address: "0x55d398326f99059ff775485246999027b3197955"
    decimals: 18
    cgkId: "tether"
  - name: "Dai Stablecoin"
    symbol: "DAI"
    address: "0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3"
    decimals: 18
    cgkId: "dai"
  - name: "Binance-Peg USD Coin"
    symbol: "USDC"
    address: "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d"
    decimals: 18
    cgkId: "usd-coin"
  - name: "Binance USD"
    symbol: "BUSD"
    address: "0xe9e7cea3dedca5984780bafc599bd69add087d56"
    decimals: 18
    cgkId: "binance-usd"
  - name: "Ethereum Token"
    symbol: "ETH"
    address: "0x2170ed0880ac9a755fd29b2688956bd959f933f8"
    decimals: 18
    cgkId: "ethereum"
  - name: "BTCB Token"
    symbol: "BTCB"
    address: "0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c"
    decimals: 18
  - name: "PancakeSwap Token"
    symbol: "CAKE"
    address: "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82"
    decimals: 18
  - name: "Kyber Network Crystal"
    symbol: "KNC"
    address: "0xfe56d5892bdffc7bf58f2e84be1b2c32d21c308b"
    decimals: 18
    cgkId: "kyber-network-crystal"
  - name: "VersaGames"
    symbol: "VERSA"
    address: "0x0aCfc95A193009F1EA45b7fAEEF2d5e4a47c21b4"
    decimals: 18
    cgkId: "versagames"
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
blacklistedPools:
encoder:
  chainId: 56
  executorAddress:
  routerAddress:
  kyberLOAddress: 0x26279604204aa9D3B530bcd8514fc4276bf0962C
useCase:
  poolFactory:
  cacheRoute:
  getRoutes:
    chainId: 56
    gasTokenAddress: 0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c
    routerAddress:
    epsilon: 0.005
    baseGas: 125000
    getBestPoolsOptions:
      directPoolsCount: 100
      whitelistPoolsCount: 500
      tokenInPoolsCount: 200
      tokenOutPoolCount: 200
      amplifiedTvlDirectPoolsCount: 50
      amplifiedTvlWhitelistPoolsCount: 200
      amplifiedTvlTokenInPoolsCount: 100
      amplifiedTvlTokenOutPoolCount: 100
    spfaFinderOptions:
      maxHops: 3
      distributionPercent: 5
      maxPathsInRoute: 20
      maxPathsToGenerate: 5
      maxPathsToReturn: 200
      minPartUSD: 500
      minThresholdAmountInUSD: 0
      maxThresholdAmountInUSD: 100000000
    enabledDexes: *enableDexes
    blacklistedPools:
    featureFlags:
      useOptimizedSPFA: false
api:
  defaultTTL: 1s
  getRoutes:
    isCacheEnabled: true
    ttl: 3s
    isTimeoutEnabled: true
    timeout: 10s
  buildRoute:
    isCacheEnabled: false
    isTimeoutEnabled: false
  getPools:
    isCacheEnabled: false
    isTimeoutEnabled: false
  getTokens:
    isCacheEnabled: false
    isTimeoutEnabled: false
indexPoolsChunkSize: 3000
indexPoolsJobIntervalSec: 2
