env: "develop"
http:
  bindAddress: ":8080"
  mode: release #(debug,release,test)
  prefix: /polygon
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainID: 137
  dataFolder: internal/pkg/data/chain/polygon
  publicRPC: "https://rpc-mainnet.maticvigil.com"
  rpcs:
    - "https://polygon.kyberengineering.io/v1/mainnet/geth?appId=prod-dmm"
  rpc: "https://polygon.kyberengineering.io/v1/mainnet/geth?appId=prod-dmm"
  address:
    multicall: '0xed386fe855c1eff2f843b910923dd8846e45c5a4'
    gasToken: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270'
    executorAddress: '0x7F92d949185cD8ceebeBAD89876Ab3e90D1CE3b5'
    routerAddress: '0x617Dee16B86534a5d792A4d7A62FB491B544111E'
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
enableDexes: &enableDexes
  - kyberswap
  - kyberswap-static
  - kyberswapv2
  - uniswapv3
  - sushiswap
  - quickswap
  - jetswap
  - wault
  - polycat
  - dfyn
  - polydex
  - oneswap
  - iron-stable
  - curve
  - synapse
  - balancer
  - gravity
  - cometh
  - apeswap
  - dinoswap
  - dodo
  - dystopia
  - mmf
  - madmex
  - metavault
  - fraxswap
  - kyberswap-limit-order
cachePoints:
  - amount: 1
    ttl: 30
  - amount: 2
    ttl: 10
  - amount: 5
    ttl: 10
  - amount: 10
    ttl: 10
  - amount: 11
    ttl: 30
  - amount: 15
    ttl: 10
  - amount: 20
    ttl: 10
  - amount: 22
    ttl: 30
  - amount: 25
    ttl: 10
  - amount: 30
    ttl: 10
  - amount: 33
    ttl: 30
  - amount: 35
    ttl: 10
  - amount: 40
    ttl: 10
  - amount: 44
    ttl: 30
  - amount: 45
    ttl: 10
  - amount: 50
    ttl: 10
  - amount: 55
    ttl: 30
  - amount: 60
    ttl: 10
  - amount: 66
    ttl: 30
  - amount: 70
    ttl: 10
  - amount: 77
    ttl: 30
  - amount: 80
    ttl: 10
  - amount: 88
    ttl: 30
  - amount: 90
    ttl: 10
  - amount: 99
    ttl: 30
  - amount: 100
    ttl: 10
  - amount: 500
    ttl: 10
  - amount: 1000
    ttl: 10
  - amount: 10000
    ttl: 10
  - amount: 100000
    ttl: 10
cacheRanges:
  - fromUSD: 0
    toUSD: 100
    ttl: 10
  - fromUSD: 101
    toUSD: 500
    ttl: 10
  - fromUSD: 500
    toUSD: 1000
    ttl: 10
  - fromUSD: 1001
    toUSD: 2000
    ttl: 10
  - fromUSD: 2000
    toUSD: 5000
    ttl: 10
  - fromUSD: 5000
    toUSD: 10000
    ttl: 10
  - fromUSD: 10000
    toUSD: -1
    ttl: 10
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: "polygon"
  readTimeout: 3s
  writeTimeout: 3s
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: "polygon"
  readTimeout: 3s
  writeTimeout: 3s
ddAgentHost: ""
featureFlags:
  useOptimizedSPFA: false
enableGRPC: false
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
tokenCatalog:
  httpUrl: ""
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: 137
whitelistedTokens:
  - name: "Wrapped Matic"
    symbol: "WMATIC"
    address: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270"
    decimals: 18
    cgkId: "wmatic"
  - name: "Tether USD"
    symbol: "USDT"
    address: "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"
    decimals: 6
    cgkId: "tether"
  - name: "Dai Stablecoin"
    symbol: "DAI"
    address: "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063"
    decimals: 18
    cgkId: "dai"
  - name: "USD Coin"
    symbol: "USDC"
    address: "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"
    decimals: 6
    cgkId: "usd-coin"
  - name: "Wrapped Ether"
    symbol: "WETH"
    address: "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
    decimals: 18
    cgkId: "ethereum"
  - name: "Wrapped BTC"
    symbol: "WBTC"
    address: "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6"
    decimals: 8
  - name: "Quickswap"
    symbol: "QUICK"
    address: "0xB5C064F955D8e7F38fE0460C556a72987494eE17"
    decimals: 18
  - name: "Kyber Network Crystal"
    symbol: "KNC"
    address: "0x1c954e8fe737f99f68fa1ccda3e51ebdb291948c"
    decimals: 18
    cgkId: "kyber-network-crystal"
  - name: "Staked MATIC (PoS)"
    symbol: "stMATIC"
    address: "0x3a58a54c066fdc0f2d55fc9c89f0415c92ebf3c4"
    decimals: 18
    cgkId: "lido-staked-matic"
  - name: "miMATIC (miMATIC)"
    symbol: "MIMATIC"
    address: "0xa3Fa99A148fA48D14Ed51d610c367C61876997F1"
    decimals: 18
    cgkId: "mimatic"
  - name: "VersaGames"
    symbol: "VERSA"
    address: "0x8497842420cFdbc97896C2353D75d89Fc8D5Be5D"
    decimals: 18
    cgkId: "versagames"
  - name: "MMFinance (MMF)"
    symbol: "MMF"
    address: "0x22a31bd4cb694433b6de19e0acc2899e553e9481"
    decimals: 18
    cgkId: "mmfinance-polygon"
  - name: "ChainLink"
    symbol: "LINK"
    address: "0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39"
    decimals: 18
    cgkId: "chainlink"
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
blacklistedPools:
  - 0x7cC19f8c258D7F489BC1074437e25A46e397688F
encoder:
  chainId: 137
  executorAddress: 0x1d5702C6D7eB30E42A8c94B8Db7eA2E8444a37FD
  routerAddress: 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5
  kyberLOAddress: 0x3C2E9227A6d3779e5b469E425CAa7067b40Ff124
useCase:
  poolFactory:
  cacheRoute:
  getRoutes:
    chainId: 137
    gasTokenAddress: 0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270
    routerAddress: 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5
    epsilon: 0.005
    baseGas: 125000
    getBestPoolsOptions:
      directPoolsCount: 100
      whitelistPoolsCount: 500
      tokenInPoolsCount: 200
      tokenOutPoolCount: 200
      amplifiedTvlDirectPoolsCount: 50
      amplifiedTvlWhitelistPoolsCount: 200
      amplifiedTvlTokenInPoolsCount: 100
      amplifiedTvlTokenOutPoolCount: 100
    spfaFinderOptions:
      maxHops: 3
      distributionPercent: 5
      maxPathsInRoute: 20
      maxPathsToGenerate: 5
      maxPathsToReturn: 200
      minPartUSD: 500
      minThresholdAmountInUSD: 0
      maxThresholdAmountInUSD: 100000000
    enabledDexes: *enableDexes
    blacklistedPools:
    featureFlags:
      useOptimizedSPFA: false
  indexPools:
    whitelistedTokenSet:
    chunkSize: 3000
job:
  indexPools:
    interval: 2s
  updateSuggestedGasPrice:
    interval: 2s
api:
  defaultTTL: 1s
  getRoutes:
    isCacheEnabled: true
    ttl: 2s
    isTimeoutEnabled: false
    timeout: 10s
  buildRoute:
    isCacheEnabled: false
    isTimeoutEnabled: false
  getPools:
    isCacheEnabled: false
    isTimeoutEnabled: false
  getTokens:
    isCacheEnabled: false
    isTimeoutEnabled: false
repository:
  gas:
    redis:
      prefix: polygon
  pool:
    redis:
      prefix: polygon
  price:
    redis:
      prefix: polygon
  token:
    redis:
      prefix: polygon
    goCache:
      expiration: -1
      cleanupInterval: -1
  poolRank:
    redis:
      prefix: polygon
  route:
    redisCache:
      prefix: polygon
      localCacheSize: 1000
      localCacheTtl: 30s
