// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KyberNetwork/router-service/internal/pkg/usecase/buildroute (interfaces: IEthereumGasEstimator)
//
// Generated by this command:
//
//	mockgen -destination ../../mocks/usecase/buildroute/ethereum_gas_estimator.go -package buildroute github.com/KyberNetwork/router-service/internal/pkg/usecase/buildroute IEthereumGasEstimator
//

// Package buildroute is a generated GoMock package.
package buildroute

import (
	context "context"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	gomock "go.uber.org/mock/gomock"
)

// MockIEthereumGasEstimator is a mock of IEthereumGasEstimator interface.
type MockIEthereumGasEstimator struct {
	ctrl     *gomock.Controller
	recorder *MockIEthereumGasEstimatorMockRecorder
}

// MockIEthereumGasEstimatorMockRecorder is the mock recorder for MockIEthereumGasEstimator.
type MockIEthereumGasEstimatorMockRecorder struct {
	mock *MockIEthereumGasEstimator
}

// NewMockIEthereumGasEstimator creates a new mock instance.
func NewMockIEthereumGasEstimator(ctrl *gomock.Controller) *MockIEthereumGasEstimator {
	mock := &MockIEthereumGasEstimator{ctrl: ctrl}
	mock.recorder = &MockIEthereumGasEstimatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEthereumGasEstimator) EXPECT() *MockIEthereumGasEstimatorMockRecorder {
	return m.recorder
}

// EstimateGas mocks base method.
func (m *MockIEthereumGasEstimator) EstimateGas(arg0 context.Context, arg1 ethereum.CallMsg) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockIEthereumGasEstimatorMockRecorder) EstimateGas(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*MockIEthereumGasEstimator)(nil).EstimateGas), arg0, arg1)
}
