// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KyberNetwork/router-service/internal/pkg/usecase/buildroute (interfaces: IPoolRepository)
//
// Generated by this command:
//
//	mockgen -destination ../../mocks/usecase/buildroute/pool_repository.go -package buildroute github.com/KyberNetwork/router-service/internal/pkg/usecase/buildroute IPoolRepository
//

// Package buildroute is a generated GoMock package.
package buildroute

import (
	context "context"
	reflect "reflect"

	entity "github.com/KyberNetwork/router-service/internal/pkg/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockIPoolRepository is a mock of IPoolRepository interface.
type MockIPoolRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPoolRepositoryMockRecorder
	isgomock struct{}
}

// MockIPoolRepositoryMockRecorder is the mock recorder for MockIPoolRepository.
type MockIPoolRepositoryMockRecorder struct {
	mock *MockIPoolRepository
}

// NewMockIPoolRepository creates a new mock instance.
func NewMockIPoolRepository(ctrl *gomock.Controller) *MockIPoolRepository {
	mock := &MockIPoolRepository{ctrl: ctrl}
	mock.recorder = &MockIPoolRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPoolRepository) EXPECT() *MockIPoolRepositoryMockRecorder {
	return m.recorder
}

// GetFaultyPools mocks base method.
func (m *MockIPoolRepository) GetFaultyPools(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFaultyPools", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFaultyPools indicates an expected call of GetFaultyPools.
func (mr *MockIPoolRepositoryMockRecorder) GetFaultyPools(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFaultyPools", reflect.TypeOf((*MockIPoolRepository)(nil).GetFaultyPools), ctx)
}

// TrackFaultyPools mocks base method.
func (m *MockIPoolRepository) TrackFaultyPools(ctx context.Context, trackers []entity.FaultyPoolTracker) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackFaultyPools", ctx, trackers)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackFaultyPools indicates an expected call of TrackFaultyPools.
func (mr *MockIPoolRepositoryMockRecorder) TrackFaultyPools(ctx, trackers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackFaultyPools", reflect.TypeOf((*MockIPoolRepository)(nil).TrackFaultyPools), ctx, trackers)
}
