// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KyberNetwork/kyberswap-dex-lib/pkg/source/pool (interfaces: IPoolRFQ)

// Package buildroute is a generated GoMock package.
package buildroute

import (
	context "context"
	reflect "reflect"

	pool "github.com/KyberNetwork/kyberswap-dex-lib/pkg/source/pool"
	gomock "github.com/golang/mock/gomock"
)

// MockIPoolRFQ is a mock of IPoolRFQ interface.
type MockIPoolRFQ struct {
	ctrl     *gomock.Controller
	recorder *MockIPoolRFQMockRecorder
}

// MockIPoolRFQMockRecorder is the mock recorder for MockIPoolRFQ.
type MockIPoolRFQMockRecorder struct {
	mock *MockIPoolRFQ
}

// NewMockIPoolRFQ creates a new mock instance.
func NewMockIPoolRFQ(ctrl *gomock.Controller) *MockIPoolRFQ {
	mock := &MockIPoolRFQ{ctrl: ctrl}
	mock.recorder = &MockIPoolRFQMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPoolRFQ) EXPECT() *MockIPoolRFQMockRecorder {
	return m.recorder
}

// BatchRFQ mocks base method.
func (m *MockIPoolRFQ) BatchRFQ(arg0 context.Context, arg1 []pool.RFQParams) ([]*pool.RFQResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchRFQ", arg0, arg1)
	ret0, _ := ret[0].([]*pool.RFQResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchRFQ indicates an expected call of BatchRFQ.
func (mr *MockIPoolRFQMockRecorder) BatchRFQ(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchRFQ", reflect.TypeOf((*MockIPoolRFQ)(nil).BatchRFQ), arg0, arg1)
}

// RFQ mocks base method.
func (m *MockIPoolRFQ) RFQ(arg0 context.Context, arg1 pool.RFQParams) (*pool.RFQResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RFQ", arg0, arg1)
	ret0, _ := ret[0].(*pool.RFQResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RFQ indicates an expected call of RFQ.
func (mr *MockIPoolRFQMockRecorder) RFQ(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RFQ", reflect.TypeOf((*MockIPoolRFQ)(nil).RFQ), arg0, arg1)
}

// SupportBatch mocks base method.
func (m *MockIPoolRFQ) SupportBatch() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportBatch")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportBatch indicates an expected call of SupportBatch.
func (mr *MockIPoolRFQMockRecorder) SupportBatch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportBatch", reflect.TypeOf((*MockIPoolRFQ)(nil).SupportBatch))
}
