package everlongcvamm

import (
	"github.com/holiman/uint256"

	"github.com/KyberNetwork/kyberswap-dex-lib/pkg/util/big256"
)

// Wei-exact port of CvammCurve.sol (EverlongLabs/blockend @ feat/virtual-ladder-curve,
// 33c303d): the closed-form reservation curve the CvammALM venue trades on. Normalized
// inventory (x volatile, y stable) sits on the level set of y^2 + (x+c)y - k/x = 0 with
// c = 1/(2A) - 1 and 4k = 1/(2A); the venue holds a band of it (Support) scaled by kappa
// and located by an anchor sqrt price. Validated wei-exact against the shipped-semantics
// library bytecode over 774 fixture cases (testdata/cvamm_fixtures.csv, generated by a
// forge script running the via_ir-pinned CvammCurve).
//
// Every symbol is the WAD-scaled integer of the same name, every division floors and
// sqrt is floor-sqrt, exactly as on-chain. Two properties are load-bearing at the wei
// scale and must survive any edit:
//   - yAtX computes the radicand as ONE sum before the square root. Two independently
//     floored terms move in opposite directions in x, so their sum can step UP as x
//     increases — a non-monotone y, which the stable-in bisection brackets on.
//   - c is negative for every valid A (A > WAD/2), so b = x + c is carried as a
//     magnitude plus sign to avoid the catastrophic cancellation of the naive form.

var (
	uWad        = big256.BONE          // 1e18
	uWadSquared = big256.TenPow(36)    // WAD*WAD
	uQ96        = big256.U2Pow96       // 2**96
	uMinXWad    = uint256.NewInt(1e15) // curve domain floor (precision bound)
	uMaxXWad    = uint256.NewInt(1999e15)
	uMinAWad    = uint256.NewInt(5e17 + 1)
	uMaxAWad    = big256.TenPow(21) // 1000e18
)

// seedWindow brackets the stable-in bisection around the x<->y symmetry seed
// (~140x the worst seed error over the domain).
const seedWindow = 1 << 16

// yAtX solves the stable leg y at volatile coordinate x: the positive root of
// y^2 + (x+c)y - k/x = 0, as (root -/+ |b|)/2 branching on sign(b).
func yAtX(y, x, aWad *uint256.Int) error {
	if x.Lt(uMinXWad) || x.Gt(uMaxXWad) {
		return ErrCurveDomain
	}
	if aWad.Lt(uMinAWad) || aWad.Gt(uMaxAWad) {
		return ErrCurveAmplification
	}
	// fourK = 4k = 1/(2A); c = fourK - WAD is negative for every valid A, so carry |c|.
	var twoA, fourK, negC uint256.Int
	twoA.Lsh(aWad, 1)
	fourK.Div(uWadSquared, &twoA)
	negC.Sub(uWad, &fourK)

	// b = x + c = x - |c|
	var absB uint256.Int
	bNeg := x.Lt(&negC)
	if bNeg {
		absB.Sub(&negC, x)
	} else {
		absB.Sub(x, &negC)
	}

	// ONE floor in the radicand: absB^2 is exact (<= 4e36), the k-term floors once.
	var rad, term uint256.Int
	big256.MulDivDown(&term, &fourK, uWadSquared, x)
	rad.Mul(&absB, &absB)
	rad.Add(&rad, &term)

	y.Sqrt(&rad)
	if bNeg {
		y.Add(y, &absB)
	} else {
		y.Sub(y, &absB)
	}
	y.Rsh(y, 1)
	return nil
}

// normSwapExactIn is CvammCurve.swapExactIn: an exact-input fill in normalized units.
// Volatile-in (price falls, x rises) is closed form; stable-in inverts y -> x with the
// contract's seeded bisection (bit-identical to unseeded — the seed narrows the search,
// never the answer). inputUnused is non-zero only where the funded band truncates the
// fill; the caller charges a partial fill rather than erroring.
func normSwapExactIn(amountOut, xAfter, inputUnused *uint256.Int, sup *Support, xWad *uint256.Int,
	volatileIn bool, amountInWad *uint256.Int) error {
	// A no-input fill MUST be a no-op: the stable-in bisection lands on the LEFTMOST
	// coordinate of a floored-y tread, so without this guard a zero input would move the
	// coordinate.
	if amountInWad.IsZero() {
		amountOut.Clear()
		xAfter.Set(xWad)
		inputUnused.Clear()
		return nil
	}
	var y uint256.Int
	if err := yAtX(&y, xWad, sup.AWad); err != nil {
		return err
	}

	if volatileIn {
		var room, used uint256.Int
		if sup.XHi.Gt(xWad) {
			room.Sub(sup.XHi, xWad)
		}
		used.Set(amountInWad)
		if used.Gt(&room) {
			used.Set(&room)
		}
		inputUnused.Sub(amountInWad, &used)
		xAfter.Add(xWad, &used)
		var yAfter uint256.Int
		if err := yAtX(&yAfter, xAfter, sup.AWad); err != nil {
			return err
		}
		amountOut.Clear()
		if y.Gt(&yAfter) {
			amountOut.Sub(&y, &yAfter)
		}
		return nil
	}
	return stableIn(amountOut, xAfter, inputUnused, sup, xWad, &y, amountInWad)
}

// stableIn is CvammCurve._stableIn: paying the stable leg raises y and lowers x, and
// inverting y -> x needs a bisection, seeded off the invariant's x <-> y symmetry.
func stableIn(amountOut, xAfter, inputUnused *uint256.Int, sup *Support, xWad, y,
	amountInWad *uint256.Int) error {
	var yMax, reachable, used uint256.Int
	if err := yAtX(&yMax, sup.XLo, sup.AWad); err != nil {
		return err
	}
	if yMax.Gt(y) {
		reachable.Sub(&yMax, y)
	}
	used.Set(amountInWad)
	if used.Gt(&reachable) {
		used.Set(&reachable)
	}
	inputUnused.Sub(amountInWad, &used)
	if used.IsZero() {
		amountOut.Clear()
		xAfter.Set(xWad)
		inputUnused.Set(amountInWad)
		return nil
	}

	var lo, hi, yTarget uint256.Int
	lo.Set(sup.XLo)
	hi.Set(xWad)
	yTarget.Add(y, &used)
	if err := seedBracket(&lo, &hi, sup, &yTarget); err != nil {
		return err
	}
	var mid, yMid uint256.Int
	for i := 0; i < 128; i++ {
		mid.Add(&lo, &hi)
		mid.Rsh(&mid, 1)
		if mid.Eq(&lo) {
			break
		}
		if err := yAtX(&yMid, &mid, sup.AWad); err != nil {
			return err
		}
		if yMid.Gt(&yTarget) {
			lo.Set(&mid)
		} else {
			hi.Set(&mid)
		}
	}
	xAfter.Set(&hi)
	amountOut.Clear()
	if xWad.Gt(xAfter) {
		amountOut.Sub(xWad, xAfter)
	}
	return nil
}

// seedBracket is CvammCurve._seedBracket: narrow [lo, hi] around yAtX(yTarget) — valid
// because the level set is symmetric under swapping the coordinates — and adopt the
// window ONLY if it brackets the root under the same predicate the bisection uses.
func seedBracket(lo, hi *uint256.Int, sup *Support, yTarget *uint256.Int) error {
	if yTarget.Lt(uMinXWad) || yTarget.Gt(uMaxXWad) {
		return nil
	}
	var seed, loSeed, hiSeed, tmp uint256.Int
	if err := yAtX(&seed, yTarget, sup.AWad); err != nil {
		return err
	}
	tmp.AddUint64(lo, seedWindow)
	if seed.Gt(&tmp) {
		loSeed.SubUint64(&seed, seedWindow)
	} else {
		loSeed.Set(lo)
	}
	tmp.AddUint64(&seed, seedWindow)
	if tmp.Lt(hi) {
		hiSeed.Set(&tmp)
	} else {
		hiSeed.Set(hi)
	}
	if !loSeed.Lt(&hiSeed) {
		return nil
	}
	var yEdge uint256.Int
	if err := yAtX(&yEdge, &loSeed, sup.AWad); err != nil {
		return err
	}
	if !yEdge.Gt(yTarget) {
		return nil
	}
	if err := yAtX(&yEdge, &hiSeed, sup.AWad); err != nil {
		return err
	}
	if yEdge.Gt(yTarget) {
		return nil
	}
	lo.Set(&loSeed)
	hi.Set(&hiSeed)
	return nil
}

// toNormalized converts a token amount to normalized inventory, FLOORING — two mulDivs
// in this exact order, one factor of the anchor sqrt per leg.
func toNormalized(res, amount, anchorSqrtX96, kappa *uint256.Int, stable bool) *uint256.Int {
	var t uint256.Int
	big256.MulDivDown(&t, amount, uWad, kappa)
	if stable {
		return big256.MulDivDown(res, &t, uQ96, anchorSqrtX96)
	}
	return big256.MulDivDown(res, &t, anchorSqrtX96, uQ96)
}

// toToken converts normalized inventory to a token amount, FLOORING (protocol-favourable).
func toToken(res, norm, anchorSqrtX96, kappa *uint256.Int, stable bool) *uint256.Int {
	var t uint256.Int
	big256.MulDivDown(&t, kappa, norm, uWad)
	if stable {
		return big256.MulDivDown(res, &t, anchorSqrtX96, uQ96)
	}
	return big256.MulDivDown(res, &t, uQ96, anchorSqrtX96)
}

// toTokenCeil is toToken, CEILING — used only to price a truncated fill's charge.
func toTokenCeil(res, norm, anchorSqrtX96, kappa *uint256.Int, stable bool) *uint256.Int {
	var t uint256.Int
	big256.MulDivUp(&t, kappa, norm, uWad)
	if stable {
		return big256.MulDivUp(res, &t, anchorSqrtX96, uQ96)
	}
	return big256.MulDivUp(res, &t, uQ96, anchorSqrtX96)
}

// swapExactInX96 is CvammCurve.swapExactInX96: the exact-input fill in TOKEN units.
// amountOut is the GROSS output before the fee haircut. An input below normalized
// resolution (~kappa/WAD in the leg's own units — it grows with the book) is reported
// entirely unspent; a fill truncated by the band rounds its charge UP and caps at
// amountIn.
func swapExactInX96(amountOut, xAfter, amountInUnspent *uint256.Int, sup *Support,
	anchorSqrtX96, kappa, xWad *uint256.Int, stableIn bool, amountIn *uint256.Int) error {
	if anchorSqrtX96.IsZero() || kappa.IsZero() {
		return ErrRetractedBook
	}
	var inNorm uint256.Int
	toNormalized(&inNorm, amountIn, anchorSqrtX96, kappa, stableIn)
	if inNorm.IsZero() {
		amountOut.Clear()
		xAfter.Set(xWad)
		amountInUnspent.Set(amountIn)
		return nil
	}
	// The curve's flag is VOLATILE-in; this one is STABLE-in — opposites, as are the legs.
	var outNorm, unusedNorm uint256.Int
	if err := normSwapExactIn(&outNorm, xAfter, &unusedNorm, sup, xWad, !stableIn, &inNorm); err != nil {
		return err
	}
	toToken(amountOut, &outNorm, anchorSqrtX96, kappa, !stableIn)
	if unusedNorm.IsZero() {
		amountInUnspent.Clear()
		return nil
	}
	var usedNorm, usedTok uint256.Int
	usedNorm.Sub(&inNorm, &unusedNorm)
	toTokenCeil(&usedTok, &usedNorm, anchorSqrtX96, kappa, stableIn)
	amountInUnspent.Clear()
	if amountIn.Gt(&usedTok) {
		amountInUnspent.Sub(amountIn, &usedTok)
	}
	return nil
}
