// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KyberNetwork/kyberswap-aggregator/internal/pkg/api (interfaces: IGetPoolsParamsValidator)

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	params "github.com/KyberNetwork/kyberswap-aggregator/internal/pkg/api/params"
	gomock "github.com/golang/mock/gomock"
)

// MockIGetPoolsParamsValidator is a mock of IGetPoolsParamsValidator interface.
type MockIGetPoolsParamsValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIGetPoolsParamsValidatorMockRecorder
}

// MockIGetPoolsParamsValidatorMockRecorder is the mock recorder for MockIGetPoolsParamsValidator.
type MockIGetPoolsParamsValidatorMockRecorder struct {
	mock *MockIGetPoolsParamsValidator
}

// NewMockIGetPoolsParamsValidator creates a new mock instance.
func NewMockIGetPoolsParamsValidator(ctrl *gomock.Controller) *MockIGetPoolsParamsValidator {
	mock := &MockIGetPoolsParamsValidator{ctrl: ctrl}
	mock.recorder = &MockIGetPoolsParamsValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetPoolsParamsValidator) EXPECT() *MockIGetPoolsParamsValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockIGetPoolsParamsValidator) Validate(arg0 params.GetPoolsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockIGetPoolsParamsValidatorMockRecorder) Validate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockIGetPoolsParamsValidator)(nil).Validate), arg0)
}
