// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KyberNetwork/router-service/internal/pkg/api (interfaces: IGetTokensParamsValidator)
//
// Generated by this command:
//
//	mockgen -destination ../mocks/api/get_tokens_params_validator.go -package api github.com/KyberNetwork/router-service/internal/pkg/api IGetTokensParamsValidator
//

// Package api is a generated GoMock package.
package api

import (
	reflect "reflect"

	params "github.com/KyberNetwork/router-service/internal/pkg/api/params"
	gomock "go.uber.org/mock/gomock"
)

// MockIGetTokensParamsValidator is a mock of IGetTokensParamsValidator interface.
type MockIGetTokensParamsValidator struct {
	ctrl     *gomock.Controller
	recorder *MockIGetTokensParamsValidatorMockRecorder
	isgomock struct{}
}

// MockIGetTokensParamsValidatorMockRecorder is the mock recorder for MockIGetTokensParamsValidator.
type MockIGetTokensParamsValidatorMockRecorder struct {
	mock *MockIGetTokensParamsValidator
}

// NewMockIGetTokensParamsValidator creates a new mock instance.
func NewMockIGetTokensParamsValidator(ctrl *gomock.Controller) *MockIGetTokensParamsValidator {
	mock := &MockIGetTokensParamsValidator{ctrl: ctrl}
	mock.recorder = &MockIGetTokensParamsValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGetTokensParamsValidator) EXPECT() *MockIGetTokensParamsValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockIGetTokensParamsValidator) Validate(arg0 params.GetTokensParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockIGetTokensParamsValidatorMockRecorder) Validate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockIGetTokensParamsValidator)(nil).Validate), arg0)
}
