package ilyris

import (
	"encoding/json"
	"math/big"
	"os"
	"path/filepath"
	"testing"
)

// The oracle is generated by sdk/typescript/test/gen_oracle.py, which deploys the REAL
// BinPool on an in-process EVM and records the contract's own quoteExactIn / quoteExactOut /
// priceFromId outputs. So these assertions compare this Go port against the CONTRACT.
//
// That distinction is the whole point. Checking Go against the TypeScript port would pass
// happily if both misread the same line of Solidity, and a bit-exact port is exactly the
// place where two independent readings of the same spec drift.
const oracleRelPath = "testdata/oracle.json"

type oracleVector struct {
	BinStepBps            int                  `json:"binStepBps"`
	SwapFeeBps            int                  `json:"swapFeeBps"`
	ActiveID              int                  `json:"activeId"`
	DecimalsX             int                  `json:"decimalsX"`
	DecimalsY             int                  `json:"decimalsY"`
	VariableFeeControl    int                  `json:"variableFeeControl"`
	VolatilityAccumulator int                  `json:"volatilityAccumulator"`
	BaseFeeRate           string               `json:"baseFeeRate"`
	TotalFeeRate          string               `json:"totalFeeRate"`
	Bins                  [][3]json.RawMessage `json:"bins"`
	Prices                map[string]string    `json:"prices"`
	ExactIn               []struct {
		XForY     bool   `json:"xForY"`
		AmountIn  string `json:"amountIn"`
		AmountOut string `json:"amountOut"`
		FeeAmount string `json:"feeAmount"`
		FinalID   int    `json:"finalId"`
	} `json:"exactIn"`
	ExactOut []struct {
		XForY     bool   `json:"xForY"`
		AmountOut string `json:"amountOut"`
		AmountIn  string `json:"amountIn"`
		FeeAmount string `json:"feeAmount"`
		FinalID   int    `json:"finalId"`
	} `json:"exactOut"`
}

func mustBig(t *testing.T, s string) *big.Int {
	t.Helper()
	v, ok := new(big.Int).SetString(s, 10)
	if !ok {
		t.Fatalf("not a base-10 integer: %q", s)
	}
	return v
}

func loadOracle(t *testing.T) []oracleVector {
	t.Helper()
	raw, err := os.ReadFile(filepath.FromSlash(oracleRelPath))
	if err != nil {
		t.Fatalf("read oracle: %v (run sdk/typescript/test/gen_oracle.py)", err)
	}
	var vectors []oracleVector
	if err := json.Unmarshal(raw, &vectors); err != nil {
		t.Fatalf("parse oracle: %v", err)
	}
	if len(vectors) == 0 {
		t.Fatal("oracle is empty")
	}
	return vectors
}

func simulatorFor(t *testing.T, v oracleVector) *binSimulator {
	t.Helper()
	bins := make(map[int]BinReserves, len(v.Bins))
	for _, b := range v.Bins {
		var id int
		if err := json.Unmarshal(b[0], &id); err != nil {
			t.Fatalf("bin id: %v", err)
		}
		var xs, ys string
		if err := json.Unmarshal(b[1], &xs); err != nil {
			t.Fatalf("bin reserveX: %v", err)
		}
		if err := json.Unmarshal(b[2], &ys); err != nil {
			t.Fatalf("bin reserveY: %v", err)
		}
		bins[id] = BinReserves{ReserveX: mustBig(t, xs), ReserveY: mustBig(t, ys)}
	}
	sim, err := newBinSimulator(PoolParams{
		BinStepBps:            v.BinStepBps,
		SwapFeeBps:            v.SwapFeeBps,
		ActiveID:              v.ActiveID,
		DecimalsX:             v.DecimalsX,
		DecimalsY:             v.DecimalsY,
		VariableFeeControl:    v.VariableFeeControl,
		VolatilityAccumulator: v.VolatilityAccumulator,
	}, bins)
	if err != nil {
		t.Fatalf("build simulator: %v", err)
	}
	return sim
}

func TestPriceFromIDMatchesContract(t *testing.T) {
	for i, v := range loadOracle(t) {
		for idStr, want := range v.Prices {
			var id int
			if _, err := parseInt(idStr, &id); err != nil {
				t.Fatalf("vector[%d]: bad bin id key %q", i, idStr)
			}
			got, err := PriceFromID(v.BinStepBps, id)
			if err != nil {
				t.Fatalf("vector[%d] priceFromId(%d): %v", i, id, err)
			}
			if got.Cmp(mustBig(t, want)) != 0 {
				t.Errorf("vector[%d] binStep=%d priceFromId(%d) = %s, contract says %s",
					i, v.BinStepBps, id, got, want)
			}
		}
	}
}

func TestFeeRatesMatchContract(t *testing.T) {
	for i, v := range loadOracle(t) {
		sim := simulatorFor(t, v)
		if v.BaseFeeRate != "" {
			if got := sim.BaseFeeRate(); got.Cmp(mustBig(t, v.BaseFeeRate)) != 0 {
				t.Errorf("vector[%d] baseFeeRate = %s, contract says %s", i, got, v.BaseFeeRate)
			}
		}
		if v.TotalFeeRate != "" {
			if got := sim.TotalFeeRate(); got.Cmp(mustBig(t, v.TotalFeeRate)) != 0 {
				t.Errorf("vector[%d] totalFeeRate = %s, contract says %s", i, got, v.TotalFeeRate)
			}
		}
	}
}

func TestQuoteExactInMatchesContract(t *testing.T) {
	for i, v := range loadOracle(t) {
		sim := simulatorFor(t, v)
		for j, c := range v.ExactIn {
			got, err := sim.QuoteExactIn(c.XForY, mustBig(t, c.AmountIn))
			if err != nil {
				t.Fatalf("vector[%d].exactIn[%d] (binStep=%d xForY=%v in=%s): %v",
					i, j, v.BinStepBps, c.XForY, c.AmountIn, err)
			}
			if got.AmountOut.Cmp(mustBig(t, c.AmountOut)) != 0 {
				t.Errorf("vector[%d].exactIn[%d] binStep=%d amountOut = %s, contract says %s",
					i, j, v.BinStepBps, got.AmountOut, c.AmountOut)
			}
			if got.FeeAmount.Cmp(mustBig(t, c.FeeAmount)) != 0 {
				t.Errorf("vector[%d].exactIn[%d] feeAmount = %s, contract says %s",
					i, j, got.FeeAmount, c.FeeAmount)
			}
			if got.FinalID != c.FinalID {
				t.Errorf("vector[%d].exactIn[%d] finalId = %d, contract says %d",
					i, j, got.FinalID, c.FinalID)
			}
		}
	}
}

func TestQuoteExactOutMatchesContract(t *testing.T) {
	for i, v := range loadOracle(t) {
		sim := simulatorFor(t, v)
		for j, c := range v.ExactOut {
			got, err := sim.QuoteExactOut(c.XForY, mustBig(t, c.AmountOut))
			if err != nil {
				t.Fatalf("vector[%d].exactOut[%d] (binStep=%d xForY=%v out=%s): %v",
					i, j, v.BinStepBps, c.XForY, c.AmountOut, err)
			}
			if got.AmountIn.Cmp(mustBig(t, c.AmountIn)) != 0 {
				t.Errorf("vector[%d].exactOut[%d] binStep=%d amountIn = %s, contract says %s",
					i, j, v.BinStepBps, got.AmountIn, c.AmountIn)
			}
			if got.FeeAmount.Cmp(mustBig(t, c.FeeAmount)) != 0 {
				t.Errorf("vector[%d].exactOut[%d] feeAmount = %s, contract says %s",
					i, j, got.FeeAmount, c.FeeAmount)
			}
			if got.FinalID != c.FinalID {
				t.Errorf("vector[%d].exactOut[%d] finalId = %d, contract says %d",
					i, j, got.FinalID, c.FinalID)
			}
		}
	}
}

// A book that cannot fill must error, never return a zero quote. KyberSwap treats a returned
// amount as executable; a silent zero becomes a route that reverts on chain.
func TestInsufficientLiquidityIsAnErrorNotAZero(t *testing.T) {
	v := loadOracle(t)[0]
	sim := simulatorFor(t, v)
	huge := new(big.Int).Exp(big.NewInt(10), big.NewInt(40), nil)
	if _, err := sim.QuoteExactIn(true, huge); err == nil {
		t.Fatal("expected ErrInsufficientLiquidity for an unfillable size, got a quote")
	}
	if _, err := sim.QuoteExactOut(true, huge); err == nil {
		t.Fatal("expected ErrInsufficientLiquidity for an unfillable size, got a quote")
	}
}

func TestZeroAmountStaysInTheActiveBin(t *testing.T) {
	v := loadOracle(t)[0]
	sim := simulatorFor(t, v)
	in, err := sim.QuoteExactIn(true, new(big.Int))
	if err != nil {
		t.Fatalf("zero exact-in: %v", err)
	}
	if in.AmountOut.Sign() != 0 || in.FinalID != v.ActiveID {
		t.Errorf("zero exact-in = out %s finalId %d, want 0 and activeId %d",
			in.AmountOut, in.FinalID, v.ActiveID)
	}
	out, err := sim.QuoteExactOut(true, new(big.Int))
	if err != nil {
		t.Fatalf("zero exact-out: %v", err)
	}
	if out.AmountIn.Sign() != 0 || out.FinalID != v.ActiveID {
		t.Errorf("zero exact-out = in %s finalId %d, want 0 and activeId %d",
			out.AmountIn, out.FinalID, v.ActiveID)
	}
}

// Quoting must not mutate the book: KyberSwap prices an ARRAY of amounts against one
// simulator, so a quote that consumed reserves would make every amount after the first wrong.
func TestQuotingIsNonMutating(t *testing.T) {
	v := loadOracle(t)[0]
	sim := simulatorFor(t, v)
	if len(v.ExactIn) == 0 {
		t.Skip("vector has no exact-in cases")
	}
	c := v.ExactIn[0]
	first, err := sim.QuoteExactIn(c.XForY, mustBig(t, c.AmountIn))
	if err != nil {
		t.Fatalf("first quote: %v", err)
	}
	for i := 0; i < 3; i++ {
		again, err := sim.QuoteExactIn(c.XForY, mustBig(t, c.AmountIn))
		if err != nil {
			t.Fatalf("repeat quote %d: %v", i, err)
		}
		if again.AmountOut.Cmp(first.AmountOut) != 0 {
			t.Fatalf("repeat quote %d = %s, first was %s: quoting mutated the book",
				i, again.AmountOut, first.AmountOut)
		}
	}
}

// parseInt avoids pulling in strconv at the top for one call site.
func parseInt(s string, out *int) (int, error) {
	var v int
	neg := false
	i := 0
	if len(s) > 0 && (s[0] == '-' || s[0] == '+') {
		neg = s[0] == '-'
		i = 1
	}
	if i >= len(s) {
		return 0, errBadInt
	}
	for ; i < len(s); i++ {
		if s[i] < '0' || s[i] > '9' {
			return 0, errBadInt
		}
		v = v*10 + int(s[i]-'0')
	}
	if neg {
		v = -v
	}
	*out = v
	return v, nil
}

var errBadInt = &parseError{}

type parseError struct{}

func (*parseError) Error() string { return "not an integer" }

// Live pool (chain 4663, binStep 10) sits at activeId 7796, ~650× outside the oracle's
// priced-id range. want values are BinPool.priceFromId on
// 0x90D0950065C567B9324A08A9AaE8a28890fBab16, re-checked 2026-08-26 via the edge RPC
// cache; they match the Go kernel.
func TestPriceFromIDAtLiveActiveId(t *testing.T) {
	cases := []struct {
		id   int
		want string
	}{
		{7796, "2421408311338001783650"},
		{7800, "2431108482721276470964"},
		{-7796, "412982806459199"},
	}
	for _, c := range cases {
		got, err := PriceFromID(10, c.id)
		if err != nil {
			t.Fatalf("PriceFromID(10, %d): %v", c.id, err)
		}
		if got.Cmp(mustBig(t, c.want)) != 0 {
			t.Errorf("PriceFromID(10, %d) = %s, live contract says %s", c.id, got, c.want)
		}
	}
}

func TestTotalFeeRateClampsAtMax(t *testing.T) {
	// Huge control + accumulator must hit MaxFeeRate (1e8), not overflow past it.
	sim, err := newBinSimulator(PoolParams{
		BinStepBps: 10, SwapFeeBps: 30, ActiveID: 7796,
		DecimalsX: 18, DecimalsY: 6,
		VariableFeeControl:    1_000_000,
		VolatilityAccumulator: 1_000_000,
	}, map[int]BinReserves{
		7796: {ReserveX: big.NewInt(1e18), ReserveY: big.NewInt(1_000_000)},
	})
	if err != nil {
		t.Fatal(err)
	}
	got := sim.TotalFeeRate()
	if got.Cmp(MaxFeeRate) != 0 {
		t.Errorf("TotalFeeRate() = %s, want clamp at MaxFeeRate %s", got, MaxFeeRate)
	}
}

func TestVariableFeeControlNonZeroDoesNotVanish(t *testing.T) {
	// A second non-zero control case besides oracle vector 8. Small surcharge must
	// still be strictly above the flat 30 bps base (3e7 at 1e9 precision).
	sim, err := newBinSimulator(PoolParams{
		BinStepBps: 10, SwapFeeBps: 30, ActiveID: 7796,
		DecimalsX: 18, DecimalsY: 6,
		VariableFeeControl:    5000,
		VolatilityAccumulator: 20_000,
	}, map[int]BinReserves{
		7796: {ReserveX: big.NewInt(1e18), ReserveY: big.NewInt(1_000_000)},
	})
	if err != nil {
		t.Fatal(err)
	}
	base := sim.BaseFeeRate()
	total := sim.TotalFeeRate()
	if total.Cmp(base) <= 0 {
		t.Errorf("variable fee vanished: total %s <= base %s", total, base)
	}
	if total.Cmp(MaxFeeRate) > 0 {
		t.Errorf("total %s exceeded MaxFeeRate", total)
	}
}

func TestGasConstantsMatchLens(t *testing.T) {
	if BaseSwapGas != 130_000 || PerExtraBinGas != 41_500 {
		t.Fatalf("gas constants drifted: %d + %d", BaseSwapGas, PerExtraBinGas)
	}
}
