package stablestable

import (
	"testing"

	"github.com/holiman/uint256"

	u256 "github.com/KyberNetwork/kyberswap-dex-lib/pkg/util/big256"
)

// q96U returns 2**96 as a fresh *uint256.Int (the package-level q96 is shared,
// and we want each test to start from independent inputs).
func q96U() *uint256.Int { return new(uint256.Int).Lsh(u256.U1, 96) }

// All expected values below were generated by mirroring FeeCalculation.sol
// in Python (see commit message / context file for the script). They are
// frozen so any drift in the Go port shows up immediately.
func TestCalculatePriceRatioX96_Symmetric(t *testing.T) {
	a := q96U()
	b := new(uint256.Int).Mul(u256.U2, q96U())
	r1 := CalculatePriceRatioX96(a, b)
	r2 := CalculatePriceRatioX96(b, a)
	if r1.Cmp(r2) != 0 {
		t.Fatalf("price ratio not symmetric: %s vs %s", r1, r2)
	}
}

// Reference: USDC/USDT pool, sqrtPrice = 2**96 (1:1), optimalFeeE6 = 7 (0.0007%).
const usdcUsdtOptimalFeeE6 uint64 = 7

func TestCalculateAtPeg(t *testing.T) {
	ref := q96U()
	amm := q96U() // exactly at peg

	p := CalculatePriceRatioX96(amm, ref)
	wantP := uint256.MustFromDecimal("79228162514264337593543950336")
	if p.Cmp(wantP) != 0 {
		t.Fatalf("priceRatio: got %s want %s", p, wantP)
	}

	_, isOutside := CalculateCloseBoundaryFee(p, usdcUsdtOptimalFeeE6)
	if isOutside {
		t.Fatalf("at peg should be inside optimal range")
	}

	far := CalculateFarBoundaryFee(p, usdcUsdtOptimalFeeE6)
	if far.Cmp(uint256.NewInt(7_000_000)) != 0 {
		t.Fatalf("far fee at peg: got %s want 7000000", far)
	}

	// At peg, both buy and sell pre-impact prices coincide with ±optimalFee.
	fee, err := CalculateInsideOptimalRangeFee(p, usdcUsdtOptimalFeeE6, false, true)
	if err != nil {
		t.Fatalf("inside fee err: %v", err)
	}
	if fee.Cmp(uint256.NewInt(7_000_000)) != 0 {
		t.Fatalf("inside fee at peg: got %s want 7000000", fee)
	}
}

func TestCalculateInsideRangeBelowPeg(t *testing.T) {
	// AMM ~0.00005% below peg in price space (sqrtPrice * sqrt(0.9999995)).
	ref := q96U()
	amm := new(uint256.Int).Mul(ref, uint256.NewInt(9_999_995))
	amm.Div(amm, uint256.NewInt(10_000_000))

	p := CalculatePriceRatioX96(amm, ref)
	wantP := uint256.MustFromDecimal("79228083286121267451944009889")
	if p.Cmp(wantP) != 0 {
		t.Fatalf("priceRatio: got %s want %s", p, wantP)
	}

	_, isOutside := CalculateCloseBoundaryFee(p, usdcUsdtOptimalFeeE6)
	if isOutside {
		t.Fatalf("expected inside optimal range")
	}

	// Sell-side fee (zeroForOne=true, ammBelowRP=true): the close branch.
	feeSell, err := CalculateInsideOptimalRangeFee(p, usdcUsdtOptimalFeeE6, true, true)
	if err != nil {
		t.Fatal(err)
	}
	if feeSell.Cmp(uint256.NewInt(6_000_007)) != 0 {
		t.Fatalf("inside sell fee: got %s want 6000007", feeSell)
	}

	// Buy-side fee (zeroForOne=false): the far branch.
	feeBuy, err := CalculateInsideOptimalRangeFee(p, usdcUsdtOptimalFeeE6, true, false)
	if err != nil {
		t.Fatal(err)
	}
	if feeBuy.Cmp(uint256.NewInt(7_999_993)) != 0 {
		t.Fatalf("inside buy fee: got %s want 7999993", feeBuy)
	}
}

func TestCalculateOutsideRange(t *testing.T) {
	// AMM 1% below peg in linear price (well outside the 0.0007% optimal band).
	ref := q96U()
	amm := new(uint256.Int).Mul(ref, uint256.NewInt(99))
	amm.Div(amm, uint256.NewInt(100))

	p := CalculatePriceRatioX96(amm, ref)
	mag, isOutside := CalculateCloseBoundaryFee(p, usdcUsdtOptimalFeeE6)
	if !isOutside {
		t.Fatalf("expected outside optimal range")
	}
	if mag.Cmp(uint256.NewInt(19_893_139_252)) != 0 {
		t.Fatalf("close fee: got %s want 19893139252", mag)
	}

	far := CalculateFarBoundaryFee(p, usdcUsdtOptimalFeeE6)
	if far.Cmp(uint256.NewInt(19_906_860_701)) != 0 {
		t.Fatalf("far fee: got %s want 19906860701", far)
	}
}

func TestFastPowQ24(t *testing.T) {
	// k = 0.99 in Q24 = 16_609_443. Verifies the fast-path branches against
	// the exact integer arithmetic from the Solidity assembly block.
	const k uint64 = 16_609_443
	cases := []struct {
		n    uint64
		want uint64
	}{
		{0, 1 << 24},
		{1, k},
		{2, 16_443_347},
		{3, 16_278_913},
		{4, 16_116_123},
	}
	for _, tc := range cases {
		got, err := fastPowQ24(k, tc.n)
		if err != nil {
			t.Fatalf("fastPow(%d): %v", tc.n, err)
		}
		if got.Uint64() != tc.want {
			t.Fatalf("fastPow(%d): got %s want %d", tc.n, got, tc.want)
		}
	}
}

func TestCalculateDecayingFee_FastPath(t *testing.T) {
	// k = 0.99 in Q24. previous = 1_000_000_000_000 (1 in E12), target = 0,
	// blocksPassed = 2 → expected fee ≈ 0.99^2 = 0.9801.
	const k uint64 = 16_609_443
	target := new(uint256.Int)
	prev := new(uint256.Int).Set(oneE12)

	// We don't need a real logK for fast-path (n<=4); pass a sentinel.
	got, err := CalculateDecayingFee(target, prev, k, 1, 2)
	if err != nil {
		t.Fatal(err)
	}

	// fastPow returns 16_443_347 (Q24) for k^2; decay = 0 + 16_443_347 * 1e12 >> 24.
	want := new(uint256.Int).Mul(uint256.NewInt(16_443_347), oneE12)
	want.Rsh(want, 24)
	if got.Cmp(want) != 0 {
		t.Fatalf("decaying fee: got %s want %s", got, want)
	}
}

func TestCalculateDecayingFee_PrevBelowTarget(t *testing.T) {
	target := uint256.NewInt(13_995_487)
	prev := uint256.NewInt(13_995_060)

	got, err := CalculateDecayingFee(target, prev, 167_772, 4_188_378, 96_255)
	if err == nil {
		t.Fatalf("expected error for prev<target, got fee=%s", got)
	}
}

func TestAdjustPreviousFeeForPriceMovement_Identity(t *testing.T) {
	// movementRatio = Q96 (i.e. price unchanged) → adjustedFee == prev.
	prev := uint256.NewInt(123_456_789)
	got := AdjustPreviousFeeForPriceMovement(q96U(), prev)
	if got.Cmp(prev) != 0 {
		t.Fatalf("identity adjust: got %s want %s", got, prev)
	}
}
