env: "develop"
http:
  bindAddress: ":8080"
  mode: debug #(debug,release,test)
  prefix: /bsc
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainId: &chainId 56
  chainName: &chainName bsc
  rpc: "https://bsc.kyberengineering.io"
  executorAddress: &executorAddress "0xd250aF9a5c439294b1B4baba2EBE4308382d1a41"
  routerAddress: &routerAddress "0x09917437898D7378C41Fdc4e8AdA531e7b360fe8"
  gasTokenAddress: &gasTokenAddress "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c"
  whitelistedTokenSet: &whitelistedTokenSet
    0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c: true # WBNB
    0x55d398326f99059ff775485246999027b3197955: true # USDT
    0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3: true # DAI
    0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d: true # USDC
    0xe9e7cea3dedca5984780bafc599bd69add087d56: true # BUSD
    0x2170ed0880ac9a755fd29b2688956bd959f933f8: true # ETH
    0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c: true # BTCB
    0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82: true # CAKE
    0xfe56d5892bdffc7bf58f2e84be1b2c32d21c308b: true # KNC
    0x0aCfc95A193009F1EA45b7fAEEF2d5e4a47c21b4: true # VERSA
  blacklistedPoolSet: &blacklistedPoolSet
    - "0xfeafe253802b77456b4627f8c2306a9cebb5d681"
    - "0xffe166ceabef3af31977fb76b93892e8c4c504e6"
  availableSources: &availableSources
    - "kyberswap"
    - "kyberswap-static"
    - "kyberswapv2"
    - "sushiswap"
    - "oneswap"
    - "ellipsis"
    - "nerve"
    - "apeswap"
    - "jetswap"
    - "mdex"
    - "pancake"
    - "wault"
    - "pancake-legacy"
    - "synapse"
    - "pantherswap"
    - "dodo"
    - "biswap"
    - "fraxswap"
    - "kyberswap-limit-order"
  featureFlags: &featureFlags
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
ddAgentHost: ""
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: *chainId
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
encoder:
  chainId: *chainId
  executorAddress: *executorAddress
  routerAddress: *routerAddress
  kyberLOAddress:
useCase:
  getRoute:
    chainId: *chainId
    gasTokenAddress: *gasTokenAddress
    routerAddress: *routerAddress
    availableSources: *availableSources
    ammAggregator:
      whitelistedTokenSet: *whitelistedTokenSet
      getBestPoolsOptions:
        directPoolsCount: 100
        whitelistPoolsCount: 500
        tokenInPoolsCount: 200
        tokenOutPoolCount: 200
        amplifiedTvlDirectPoolsCount: 50
        amplifiedTvlWhitelistPoolsCount: 200
        amplifiedTvlTokenInPoolsCount: 100
        amplifiedTvlTokenOutPoolCount: 100
      finderOptions:
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: 100000000
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30
        - amount: 2
          ttl: 10
        - amount: 5
          ttl: 10
        - amount: 10
          ttl: 10
        - amount: 11
          ttl: 30
        - amount: 15
          ttl: 10
        - amount: 20
          ttl: 10
        - amount: 22
          ttl: 30
        - amount: 25
          ttl: 10
        - amount: 30
          ttl: 10
        - amount: 33
          ttl: 30
        - amount: 35
          ttl: 10
        - amount: 40
          ttl: 10
        - amount: 44
          ttl: 30
        - amount: 45
          ttl: 10
        - amount: 50
          ttl: 10
        - amount: 55
          ttl: 30
        - amount: 60
          ttl: 10
        - amount: 66
          ttl: 30
        - amount: 70
          ttl: 10
        - amount: 77
          ttl: 30
        - amount: 80
          ttl: 10
        - amount: 88
          ttl: 30
        - amount: 90
          ttl: 10
        - amount: 99
          ttl: 30
        - amount: 100
          ttl: 10
        - amount: 500
          ttl: 10
        - amount: 1000
          ttl: 10
        - amount: 10000
          ttl: 10
        - amount: 100000
          ttl: 10
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10
        - amountUSDLowerBound: 101
          ttl: 10
        - amountUSDLowerBound: 500
          ttl: 10
        - amountUSDLowerBound: 1001
          ttl: 10
        - amountUSDLowerBound: 2000
          ttl: 10
        - amountUSDLowerBound: 5000
          ttl: 10
        - amountUSDLowerBound: 10000
          ttl: 10
      priceImpactThreshold: 0.005
      shrinkFuncName: "round"
      shrinkFuncPowExp: 0.7
  buildRoute:
    chainId: *chainId
  poolFactory:
    chainId: *chainId
  poolManager:
    blacklistedPoolSet: *blacklistedPoolSet
  indexPools:
    whitelistedTokenSet: *whitelistedTokenSet
    chunkSize: 3000
job:
  indexPools:
    interval: 2s
  updateSuggestedGasPrice:
    interval: 2s
repository:
  gas:
    redis:
      prefix: *chainName
  pool:
    redis:
      prefix: *chainName
  price:
    redis:
      prefix: *chainName
  token:
    redis:
      prefix: *chainName
    goCache:
      expiration: -1
      cleanupInterval: -1
  poolRank:
    redis:
      prefix: *chainName
  route:
    redisCache:
      prefix: *chainName
      localCacheSize: 1000
      localCacheTtl: 30s
