env: "develop"
http:
  bindAddress: ":8080"
  mode: debug #(debug,release,test)
  prefix: /ethereum
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainID: 1
  dataFolder: internal/pkg/data/chain/ethereum
  publicRPC: "https://ethereum.kyberengineering.io"
  rpcs:
    - "https://ethereum.kyberengineering.io"
  address:
    multicall: '0x5ba1e12693dc8f9c48aad8770482f4739beed696'
    gasToken: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    executorAddress: '0x4Fe5b965E3BD76eFf36280471030ef9b0E6e2C1D'
    routerAddress: '0x617Dee16B86534a5d792A4d7A62FB491B544111E'
  whitelistToken: "tokens.json"
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: false
enableDexes: &enableDexes
  - kyberswap
  - kyberswap-static
  - kyberswapv2
  - uniswap
  - uniswapv3
  - sushiswap
  - curve
  - balancer
  - synapse
  - shibaswap
  - defiswap
  - saddle
  - dodo
  - synthetix
  - maker-psm
  - lido
  - fraxswap
  - kyberswap-limit-order
dexes:
  - id: fraxswap
    handler: fraxswap
    properties:
      factoryAddress: 0x43eC799eAdd63848443E2347C49f5f52e8Fe0F6f
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 10
      updateReserveBulk: 10
  - id: maker-psm
    handler: maker-psm
    properties:
      configPath: "makerpsm/config.json"
      reserveJobInterval: 2s
  - id: kyberswap
    handler: dmm
    properties:
      factoryAddress: 0x833e4083b7ae46cea85695c4f7ed25cdad8886de
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: kyberswap-static
    handler: dmm
    properties:
      factoryAddress: 0x1c758aF0688502e49140230F6b0EBd376d429be5
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: kyberswapv2
    handler: promm
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/kybernetwork/kyberswap-elastic-mainnet"
      factoryAddress: 0x5F1dddbf348aC2fbe22a163e30F99F9ECE3DD50a
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      reserveJobInterval: 100ms
      updateReserveBulk: 10
      concurrentBatches: 100
  - id: uniswap
    handler: uniswap
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/ianlapham/uniswapv2"
      factoryAddress: 0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      updateReserveBulk: 500
  - id: uniswapv3
    handler: uniswapv3
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
      factoryAddress: 0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      reserveJobInterval: 100ms
      updateReserveBulk: 10
      concurrentBatches: 400
  - id: sushiswap
    handler: uniswap
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/sushiswap/exchange"
      factoryAddress: 0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      updateReserveBulk: 500
  - id: curve
    handler: curve
    properties:
      poolPath: "curve/pools.json"
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 500
  - id: balancer
    handler: balancer
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2"
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 1000
      updateReserveBulk: 200
  - id: synapse
    handler: synapse
    properties:
      poolPath: "synapse/pools.json"
      reserveJobInterval: 1s
      newPoolJobIntervalSec: 500
      updateReserveBulk: 200
  - id: shibaswap
    handler: uniswap
    properties:
      factoryAddress: 0x115934131916c8b277dd010ee02de363c09d037c
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      updateReserveBulk: 500
  - id: defiswap
    handler: uniswap
    properties:
      factoryAddress: 0x9deb29c9a4c7a88a3c0257393b7f3335338d9a9d
      swapFee: 0.003
      reserveJobInterval: 2s
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      updateReserveBulk: 500
  - id: saddle
    handler: synapse
    properties:
      poolPath: "saddle/pools.json"
      reserveJobInterval: 1s
      newPoolJobIntervalSec: 500
      updateReserveBulk: 200
  - id: dodo
    handler: dodo
    properties:
      subgraphAPI: "https://api.thegraph.com/subgraphs/name/dodoex/dodoex-v2"
      dodoV1SellHelper: "0x533da777aedce766ceae696bf90f8541a4ba80eb"
      newPoolJobIntervalSec: 10
      newPoolLimit: 3000
      reserveJobInterval: 2s
      updateReserveBulk: 50
  - id: synthetix
    handler: synthetix
    properties:
      addressesPath: "synthetix/addresses.json"
      reserveJobInterval: 1s
  - id: lido
    handler: lido
    properties:
      poolPath: "lido/pools.json"
      reserveJobInterval: 10s
  - id: kyberswap-limit-order
    handler: limit-order
    properties:
      limitOrderHTTPUrl: https://limit-order.dev.kyberengineering.io
      reserveJobInterval: 3s
      newPoolJobIntervalSec: 10
      predefineSupportedPairs:
epsilon: 0.005
cachePoints:
  - amount: 1
    ttl: 30
  - amount: 2
    ttl: 30
  - amount: 5
    ttl: 30
  - amount: 10
    ttl: 30
  - amount: 11
    ttl: 30
  - amount: 12
    ttl: 30
  - amount: 15
    ttl: 30
  - amount: 20
  - amount: 21
    ttl: 30
  - amount: 22
    ttl: 30
  - amount: 25
    ttl: 30
  - amount: 30
    ttl: 30
  - amount: 33
    ttl: 30
  - amount: 35
    ttl: 30
  - amount: 40
    ttl: 30
  - amount: 44
    ttl: 30
  - amount: 45
    ttl: 30
  - amount: 50
    ttl: 30
  - amount: 55
    ttl: 30
  - amount: 60
    ttl: 30
  - amount: 66
    ttl: 30
  - amount: 70
    ttl: 30
  - amount: 77
    ttl: 30
  - amount: 80
    ttl: 30
  - amount: 88
    ttl: 30
  - amount: 90
    ttl: 30
  - amount: 99
    ttl: 30
  - amount: 100
    ttl: 10
  - amount: 500
    ttl: 10
  - amount: 1000
    ttl: 10
  - amount: 10000
    ttl: 10
  - amount: 100000
    ttl: 5
cacheRanges:
  - fromUSD: 0
    toUSD: 100
    ttl: 10
  - fromUSD: 101
    toUSD: 500
    ttl: 10
  - fromUSD: 500
    toUSD: 1000
    ttl: 10
  - fromUSD: 1001
    toUSD: 2000
    ttl: 10
  - fromUSD: 2000
    toUSD: 5000
    ttl: 10
  - fromUSD: 5000
    toUSD: 10000
    ttl: 10
  - fromUSD: 10000
    toUSD: -1
    ttl: 5
redis:
  host: localhost
  port: 6379
  dbNumber: 0
  password: ''
  prefix: ''
  readTimeout: 3
  writeTimeout: 3
readOnlyRedis:
  host: localhost
  port: 6379
  dbNumber: 0
  password: ''
  prefix: ''
redisSentinel:
  masterName: ""
  sentinelPort: 26379
  dbNumber: 0
  password: ""
  prefix: ""
  readTimeout: 3
  writeTimeout: 3
ddAgentHost: ""
featureFlags:
  useOptimizedSPFA: false
enableGRPC: false
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
tokenCatalog:
  httpUrl: ""
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: 1
whitelistedTokens: &whitelistedTokens
  - name: "Wrapped Ether"
    symbol: "WETH"
    address: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
    decimals: 18
    cgkId: "ethereum"
  - name: "Tether USD"
    symbol: "USDT"
    address: "0xdac17f958d2ee523a2206206994597c13d831ec7"
    decimals: 6
    cgkId: "tether"
  - name: "Dai Stablecoin"
    symbol: "DAI"
    address: "0x6b175474e89094c44da98b954eedeac495271d0f"
    decimals: 18
    cgkId: "dai"
  - name: "USD Coin"
    symbol: "USDC"
    address: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
    decimals: 6
    cgkId: "usd-coin"
  - name: "Wrapped BTC"
    symbol: "WBTC"
    address: "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
    decimals: 8
    cgkId: "bitcoin"
  - name: "Kyber Network Crystal"
    symbol: "KNC"
    address: "0xdefa4e8a7bcba345f687a2f1456f5edd9ce97202"
    decimals: 18
    cgkId: "kyber-network-crystal"
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
blacklistedPools:
encoder:
  chainId: 1
  executorAddress: 0x555B6eE8faB3DfdBcCa9121721c435FD4C7a1fd1
  routerAddress: 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5
  kyberLOAddress:
useCase:
  poolFactory:
  cacheRoute:
  getRoutes:
    chainId: 1
    gasTokenAddress: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
    routerAddress: 0x6131B5fae19EA4f9D964eAc0408E4408b66337b5
    epsilon: 0.005
    baseGas: 125000
    getBestPoolsOptions:
      directPoolsCount: 100
      whitelistPoolsCount: 500
      tokenInPoolsCount: 200
      tokenOutPoolCount: 200
      amplifiedTvlDirectPoolsCount: 50
      amplifiedTvlWhitelistPoolsCount: 200
      amplifiedTvlTokenInPoolsCount: 100
      amplifiedTvlTokenOutPoolCount: 100
    spfaFinderOptions:
      maxHops: 3
      minPartUsd: 500
    enabledDexes: *enableDexes
    whitelistedTokens: *whitelistedTokens
    blacklistedPools:
    featureFlags:
      useOptimizedSPFA: false
api:
  defaultTTL: 1s
  getRoutes:
    isCacheEnabled: true
    ttl: 10s
    isTimeoutEnabled: true
    timeout: 10s
  buildRoute:
    isCacheEnabled: false
    isTimeoutEnabled: false
  getPools:
    isCacheEnabled: false
    isTimeoutEnabled: false
  getTokens:
    isCacheEnabled: false
    isTimeoutEnabled: false
indexPoolsChunkSize: 3000
indexPoolsJobIntervalSec: 2
