env: "develop"
http:
  bindAddress: ":8080"
  mode: debug #(debug,release,test)
  prefix: /velas
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainId: &chainId 106
  chainName: &chainName velas
  rpc: "https://evmexplorer.velas.com/rpc"
  executorAddress: &executorAddress "0x363Ef7806B3Fd17531D72e762cC82688E928D106"
  routerAddress: &routerAddress "0x92CbfC3F9466e9d0A65ED63aF277d1eeD69558e7"
  gasTokenAddress: &gasTokenAddress "0xc579D1f3CF86749E05CD06f7ADe17856c2CE3126"
  whitelistedTokenSet: &whitelistedTokenSet
    0xc579D1f3CF86749E05CD06f7ADe17856c2CE3126: true # WVLX
    0x01445C31581c354b7338AC35693AB2001B50b9aE: true # USDT
    0xe2C120f188eBd5389F71Cf4d9C16d05b62A58993: true # USDC
    0x3611Fbfb06ffBcEf9Afb210f6Ace86742e6c14a4: true # ADA
  blacklistedPoolSet: &blacklistedPoolSet
  availableSources: &availableSources
    - "kyberswap"
    - "kyberswap-static"
    - "wagyuswap"
    - "astroswap"
  featureFlags: &featureFlags
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
ddAgentHost: ""
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: *chainId
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
encoder:
  chainId: *chainId
  executorAddress: *executorAddress
  routerAddress: *routerAddress
useCase:
  getRoute:
    chainId: *chainId
    gasTokenAddress: *gasTokenAddress
    routerAddress: *routerAddress
    availableSources: *availableSources
    ammAggregator:
      whitelistedTokenSet: *whitelistedTokenSet
      getBestPoolsOptions:
        directPoolsCount: 100
        whitelistPoolsCount: 500
        tokenInPoolsCount: 200
        tokenOutPoolCount: 200
        amplifiedTvlDirectPoolsCount: 50
        amplifiedTvlWhitelistPoolsCount: 200
        amplifiedTvlTokenInPoolsCount: 100
        amplifiedTvlTokenOutPoolCount: 100
      finderOptions:
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: 100000000
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30
        - amount: 2
          ttl: 10
        - amount: 5
          ttl: 10
        - amount: 10
          ttl: 10
        - amount: 11
          ttl: 30
        - amount: 15
          ttl: 10
        - amount: 20
          ttl: 10
        - amount: 22
          ttl: 30
        - amount: 25
          ttl: 10
        - amount: 30
          ttl: 10
        - amount: 33
          ttl: 30
        - amount: 35
          ttl: 10
        - amount: 40
          ttl: 10
        - amount: 44
          ttl: 30
        - amount: 45
          ttl: 10
        - amount: 50
          ttl: 10
        - amount: 55
          ttl: 30
        - amount: 60
          ttl: 10
        - amount: 66
          ttl: 30
        - amount: 70
          ttl: 10
        - amount: 77
          ttl: 30
        - amount: 80
          ttl: 10
        - amount: 88
          ttl: 30
        - amount: 90
          ttl: 10
        - amount: 99
          ttl: 30
        - amount: 100
          ttl: 10
        - amount: 500
          ttl: 10
        - amount: 1000
          ttl: 10
        - amount: 10000
          ttl: 10
        - amount: 100000
          ttl: 10
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10
        - amountUSDLowerBound: 101
          ttl: 10
        - amountUSDLowerBound: 500
          ttl: 10
        - amountUSDLowerBound: 1001
          ttl: 10
        - amountUSDLowerBound: 2000
          ttl: 10
        - amountUSDLowerBound: 5000
          ttl: 10
        - amountUSDLowerBound: 10000
          ttl: 10
      priceImpactThreshold: 0.005
      shrinkFuncName: "round"
      shrinkFuncPowExp: 0.7
  buildRoute:
    chainId: *chainId
  poolFactory:
    chainId: *chainId
  poolManager:
    blacklistedPoolSet: *blacklistedPoolSet
  indexPools:
    whitelistedTokenSet: *whitelistedTokenSet
    chunkSize: 3000
job:
  indexPools:
    interval: 2s
  updateSuggestedGasPrice:
    interval: 2s
repository:
  gas:
    redis:
      prefix: *chainName
  pool:
    redis:
      prefix: *chainName
  price:
    redis:
      prefix: *chainName
  token:
    redis:
      prefix: *chainName
    goCache:
      expiration: -1
      cleanupInterval: -1
  poolRank:
    redis:
      prefix: *chainName
  route:
    redisCache:
      prefix: *chainName
      localCacheSize: 1000
      localCacheTtl: 30s
