env: "develop"
pprof: true
http:
  bindAddress: ":8080"
  mode: debug #(debug,release,test)
  prefix: /velas
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainId: &chainId 106
  chainName: &chainName velas
  rpc: "https://evmexplorer.velas.com/rpc"
  executorAddress: &executorAddress "0xd1B47490209CcB7A806E8a45d9479490C040ABf4"
  routerAddress: &routerAddress "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5"
  gasTokenAddress: &gasTokenAddress "0xc579d1f3cf86749e05cd06f7ade17856c2ce3126"
  whitelistedTokenSet: &whitelistedTokenSet
    0xc579d1f3cf86749e05cd06f7ade17856c2ce3126: true # WVLX
    0x01445c31581c354b7338ac35693ab2001b50b9ae: true # USDT
    0xe2c120f188ebd5389f71cf4d9c16d05b62a58993: true # USDC
    0x3611fbfb06ffbcef9afb210f6ace86742e6c14a4: true # ADA
  blacklistedPoolSet: &blacklistedPoolSet
  availableSources: &availableSources
    - "kyberswap"
    - "kyberswap-static"
    - "wagyuswap"
    - "astroswap"
  featureFlags: &featureFlags
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
pregenRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolEventRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
ddAgentHost: ""
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: *chainId
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
encoder:
  chainId: *chainId
  executorAddress: *executorAddress
  routerAddress: *routerAddress
  isPositiveSlippageEnabled: true
  minimumPSThreshold: 1000000
useCase:
  getRoute:
    chainId: *chainId
    gasTokenAddress: *gasTokenAddress
    routerAddress: *routerAddress
    availableSources: *availableSources
    aggregator:
      whitelistedTokenSet: *whitelistedTokenSet
      getBestPoolsOptions:
        directPoolsCount: 100
        whitelistPoolsCount: 500
        tokenInPoolsCount: 200
        tokenOutPoolCount: 200
        amplifiedTvlDirectPoolsCount: 50
        amplifiedTvlWhitelistPoolsCount: 200
        amplifiedTvlTokenInPoolsCount: 100
        amplifiedTvlTokenOutPoolCount: 100
      finderOptions:
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: 100000000
        isHillClimbEnabled: false
        hillClimbDistributionPercent: 1
        hillClimbIteration: 2
        hillClimbMinPartUSD: 500
        isPathGeneratorEnabled: false
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30s
        - amount: 2
          ttl: 10s
        - amount: 5
          ttl: 10s
        - amount: 10
          ttl: 10s
        - amount: 11
          ttl: 30s
        - amount: 15
          ttl: 10s
        - amount: 20
          ttl: 10s
        - amount: 22
          ttl: 30s
        - amount: 25
          ttl: 10s
        - amount: 30
          ttl: 10s
        - amount: 33
          ttl: 30s
        - amount: 35
          ttl: 10s
        - amount: 40
          ttl: 10s
        - amount: 44
          ttl: 30s
        - amount: 45
          ttl: 10s
        - amount: 50
          ttl: 10s
        - amount: 55
          ttl: 30s
        - amount: 60
          ttl: 10s
        - amount: 66
          ttl: 30s
        - amount: 70
          ttl: 10s
        - amount: 77
          ttl: 30s
        - amount: 80
          ttl: 10s
        - amount: 88
          ttl: 30s
        - amount: 90
          ttl: 10s
        - amount: 99
          ttl: 30s
        - amount: 100
          ttl: 10s
        - amount: 500
          ttl: 10s
        - amount: 1000
          ttl: 10s
        - amount: 10000
          ttl: 10s
        - amount: 100000
          ttl: 10s
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10s
        - amountUSDLowerBound: 101
          ttl: 10s
        - amountUSDLowerBound: 500
          ttl: 10s
        - amountUSDLowerBound: 1001
          ttl: 10s
        - amountUSDLowerBound: 2000
          ttl: 10s
        - amountUSDLowerBound: 5000
          ttl: 10s
        - amountUSDLowerBound: 10000
          ttl: 10s
      priceImpactThreshold: 0.005
      shrinkFuncName: "round"
      shrinkDecimalBase: 10
      shrinkFuncPowExp: 0.7
      shrinkFuncLogPercent: 1.01
  buildRoute:
    chainId: *chainId
    faultyPools:
      windowSize: 15m
      faultyExpiredTime: 3m
  poolFactory:
    chainId: *chainId
  poolManager:
    blacklistedPoolSet: *blacklistedPoolSet
    capacity: 100000
    poolRenewalInterval: 3s
    faultyPoolsExpireThreshold: 3s
    maxFaultyPoolSize: 10
  indexPools:
    whitelistedTokenSet: *whitelistedTokenSet
    chunkSize: 3000
job:
  indexPools:
    interval: 2s
    poolEvent:
      consumerConfig:
        prefix: *chainName
        stream: "pool_event"
        group: "router_indexPools"
        key: "message"
        block: 300ms
        count: 100
        bufferSize: 20
        ackBufferSize: 10
      batchRate: 700ms
      batchSize: 100
      retryInterval: 5s
  updateSuggestedGasPrice:
    interval: 15s
repository:
  gas:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 5000
      maxCost: 500
      bufferItems: 64
      suggestedGasPrice:
        cost: 1
        ttl: 2m
  pool:
    redis:
      prefix: *chainName
  price:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 10000
      maxCost: 1000
      bufferItems: 64
      price:
        cost: 1
        ttl: 1m
  token:
    redis:
      prefix: *chainName
    goCache:
      expiration: -1
      cleanupInterval: -1
  poolRank:
    redis:
      prefix: *chainName
  route:
    redisCache:
      prefix: *chainName
      localCacheSize: 5000
      localCacheTtl: 30s
  erc20balanceslot:
    redis:
      prefix: *chainName
validator:
  buildRouteParams:
    slippageToleranceGte: 0
    slippageToleranceLte: 5000
    blacklistedRecipientSet:
  getRouteEncodeParams:
    slippageToleranceGte: 0
    slippageToleranceLte: 5000
    blacklistedRecipientSet:
