version: '3'

services:
  router-service:
    build: 
      context: .
      args:
        - GH_PAT=${GH_PAT}
    command:
      - /app/server
      - '--config'
      - internal/pkg/config/files/prod/ethereum.yaml
      - api
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          # cpus: '8'
          # memory: 4G
          cpus: '4'
          memory: 2G
        reservations:
          # cpus: '4'
          # memory: 200M
          cpus: '2'
          memory: 200M
    environment:
      - ENV=production
      - COMMON__RPC=https://ethereum.kyberengineering.io

      - PREGENREDIS__ADDRESSES=host.docker.internal:6379 #TODO change this
      # - PREGENREDIS__MASTERNAME=path-generator-master #TODO change this

      - REDIS__ADDRESSES=host.docker.internal:6379 #TODO change this
      # - REDIS__PASSWORD= #TODO change this
      - REDIS__DBNUMBER=0
      - REDIS__PREFIX=ethereum
      - REDIS__READTIMEOUT=300s
      - REDIS__WRITETIMEOUT=300s
      - REDIS__READONLY=true

      - POOLREDIS__ADDRESSES=host.docker.internal:6379 #TODO change this
      # - POOLREDIS__PASSWORD= #TODO change this
      - POOLREDIS__DBNUMBER=0
      - POOLREDIS__PREFIX=ethereum
      - POOLREDIS__READTIMEOUT=300s
      - POOLREDIS__WRITETIMEOUT=300s
      - POOLREDIS__READONLY=true

      - REPOSITORY__ROUTE__REDISCACHE__LOCALCACHESIZE=10000
      - REPOSITORY__ROUTE__REDISCACHE__LOCALCACHETTL=30s

      - USECASE__POOLMANAGER__POOLRENEWALINTERVAL=2s
      - USECASE__POOLMANAGER__CAPACITY=20000

      - KEYPAIR__KEYIDFORSEALINGDATA__CLIENTDATA=1
      # - KEYPAIR__STORAGEFILEPATH= #TODO change this
      # - SECRETKEY= #TODO change this
      # - RELOADCONFIG__HTTPURL #TODO change this

      - ENCODER__ROUTERADDRESS=0x6131B5fae19EA4f9D964eAc0408E4408b66337b5
      - ENCODER__EXECUTORADDRESS=0xf081470f5C6FBCCF48cC4e5B82Dd926409DcdD67
      - ENCODER__EXECUTORADDRESSBYCLIENTID__UNIBOT-TG=0x1BC5cF80f308518f000dDE4c8f8139268aA014DB
      - ENCODER__KYBERLOADDRESS=0x227B0c196eA8db17A665EA6824D972A64202E936
      - USECASE__GETROUTE__ROUTERADDRESS=0x6131B5fae19EA4f9D964eAc0408E4408b66337b5

      # The following configs make router-service connect to AEVM server, but do not use AEVM yet
      - AEVMENABLED=true
      - AEVM__SERVERURL="localhost:8247,localhost:18247"
      - AEVM__RPC="http://localhost:63501"
      - AEVM__USEHOLDERSLISTASFALLBACK=true
      - AEVM__TOKENHOLDERSREDIS__ADDRESSES=aevm-token-holders.redis.shared-cluster.gke.production.internal.:6379 # TODO change this
      - AEVM__TOKENHOLDERSREDIS__PASSWORD= # TODO change this
      - AEVM__TOKENHOLDERSREDIS__DBNUMBER=0
      - AEVM__TOKENHOLDERSREDIS__PREFIX=ethereum

      # Explicitly disable AEVM. We'll enable AEVM via remote configs.
      - USECASE__POOLFACTORY__USEAEVM=false
      - USECASE__POOLMANAGER__USEAEVM=false

      - RELOADCONFIG__SERVICENAME=aggregator-aevm-mirrored

      # TODO change this
      # - PYROSCOPE_ENABLED=true
      # - PYROSCOPE_HOST=http://10.240.0.65:4040

      - OTEL_ENABLED=true
      - OTEL_ENV=production
      - OTEL_SERVICE_NAME=router-service-ethereum-aevm-mirrored-api
      - OTEL_SERVICE_VERSION=aevm-mirrored_eth-lab.1
      - OTEL_AGENT_HOST=34.124.180.228
      - OTEL_METRIC_AGENT_GRPC_PORT=4315
      - OTEL_METRIC_AGENT_HTTP_PORT=4316
      - OTEL_TRACE_AGENT_GRPC_PORT=4317
      - OTEL_TRACE_AGENT_HTTP_PORT=4318
      - OTEL_INSECURE=true
      - OTEL_TRACE_SAMPLE_RATE=0.1

  proxy:
    image: nginx:1.25.4-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf