package everlongflamm

import "errors"

// Sentinel errors, one per custom error the deployed c104 contracts can revert with: the 139 `error` signatures
// declared under src/core, src/factory, src/hooks, src/interfaces and src/libraries of c104 @ 80abd43 -- the pool
// implementation and its linked libraries, the factory, the hooks, the Router, the financing account, the PriceFeed
// and the interfaces they share -- plus the eight OpenZeppelin ERC20 and Initializable errors their code can raise,
// 147 in all. The c104 periphery (FLAMMAssetRouter, FLAMMEntryMarket, FLAMMTychoSwapAdapter, MultiDexAggregator,
// PoolSwapAdapter and the tranche contracts) declares 44 more and is left out: none of it is on a path a quote or a
// refresh reaches.
//
// Each message carries the Solidity signature so a simulator refusal maps 1:1 onto the revert a real fill would
// hit; revertSelectors indexes them by 4-byte selector, which is how a probe's revert is classified (attest.go) and
// how the parity tests compare a chain revert. A selector with no sentinel decodes to nil, which fails a refresh
// closed rather than reading it as agreement.
var (
	ErrAccountCodeMismatch        = errors.New("everlong-flamm: AccountCodeMismatch()")
	ErrAlreadyBootstrapped        = errors.New("everlong-flamm: AlreadyBootstrapped()")
	ErrAlreadyInitialized         = errors.New("everlong-flamm: AlreadyInitialized()")
	ErrAlreadyRegistered          = errors.New("everlong-flamm: AlreadyRegistered()")
	ErrAnchorOutOfBounds          = errors.New("everlong-flamm: AnchorOutOfBounds()")
	ErrBadKind                    = errors.New("everlong-flamm: BadKind()")
	ErrBadLoanIndex               = errors.New("everlong-flamm: BadLoanIndex()")
	ErrBadPriorities              = errors.New("everlong-flamm: BadPriorities()")
	ErrBadReceiver                = errors.New("everlong-flamm: BadReceiver()")
	ErrBadVenueId                 = errors.New("everlong-flamm: BadVenueId()")
	ErrBelowMinimumShares         = errors.New("everlong-flamm: BelowMinimumShares()")
	ErrConservation               = errors.New("everlong-flamm: Conservation()")
	ErrContextMismatch            = errors.New("everlong-flamm: ContextMismatch()")
	ErrCreateFailed               = errors.New("everlong-flamm: CreateFailed()")
	ErrCurveAmplification         = errors.New("everlong-flamm: CurveAmplification()")
	ErrCurveDomain                = errors.New("everlong-flamm: CurveDomain()")
	ErrCurvePriceOutOfDomain      = errors.New("everlong-flamm: CurvePriceOutOfDomain()")
	ErrCurveReprices              = errors.New("everlong-flamm: CurveReprices()")
	ErrCurveSpan                  = errors.New("everlong-flamm: CurveSpan()")
	ErrCustodyMismatch            = errors.New("everlong-flamm: CustodyMismatch()")
	ErrDebtCapExceeded            = errors.New("everlong-flamm: DebtCapExceeded()")
	ErrDebtOutstanding            = errors.New("everlong-flamm: DebtOutstanding()")
	ErrDeployerInvalid            = errors.New("everlong-flamm: DeployerInvalid(uint8,address)")
	ErrDeployerNotReady           = errors.New("everlong-flamm: DeployerNotReady(uint8)")
	ErrDepositCapExceeded         = errors.New("everlong-flamm: DepositCapExceeded()")
	ErrDepositNotPermitted        = errors.New("everlong-flamm: DepositNotPermitted()")
	ErrDialCooldown               = errors.New("everlong-flamm: DialCooldown()")
	ErrDialOutOfEnvelope          = errors.New("everlong-flamm: DialOutOfEnvelope()")
	ErrDrawOutsideDrawnSet        = errors.New("everlong-flamm: DrawOutsideDrawnSet()")
	ErrDuplicateLoanAsset         = errors.New("everlong-flamm: DuplicateLoanAsset()")
	ErrDuplicateVenue             = errors.New("everlong-flamm: DuplicateVenue()")
	ErrERC20InsufficientAllowance = errors.New("everlong-flamm: ERC20InsufficientAllowance(address,uint256,uint256)")
	ErrERC20InsufficientBalance   = errors.New("everlong-flamm: ERC20InsufficientBalance(address,uint256,uint256)")
	ErrERC20InvalidApprover       = errors.New("everlong-flamm: ERC20InvalidApprover(address)")
	ErrERC20InvalidReceiver       = errors.New("everlong-flamm: ERC20InvalidReceiver(address)")
	ErrERC20InvalidSender         = errors.New("everlong-flamm: ERC20InvalidSender(address)")
	ErrERC20InvalidSpender        = errors.New("everlong-flamm: ERC20InvalidSpender(address)")
	ErrExactDelta                 = errors.New("everlong-flamm: ExactDelta()")
	ErrExitWorsensLedger          = errors.New("everlong-flamm: ExitWorsensLedger()")
	ErrExpired                    = errors.New("everlong-flamm: Expired()")
	ErrFeatureDisabled            = errors.New("everlong-flamm: FeatureDisabled(uint8)")
	ErrFeeMismatch                = errors.New("everlong-flamm: FeeMismatch()")
	ErrFeeOutOfBounds             = errors.New("everlong-flamm: FeeOutOfBounds()")
	ErrFillInvalid                = errors.New("everlong-flamm: FillInvalid()")
	ErrFillMismatch               = errors.New("everlong-flamm: FillMismatch()")
	ErrFillPriceBand              = errors.New("everlong-flamm: FillPriceBand()")
	ErrFillValueDrop              = errors.New("everlong-flamm: FillValueDrop()")
	ErrFrameUnquotable            = errors.New("everlong-flamm: FrameUnquotable()")
	ErrGlobalPaused               = errors.New("everlong-flamm: GlobalPaused()")
	ErrGuardianMayOnlyTighten     = errors.New("everlong-flamm: GuardianMayOnlyTighten()")
	ErrHookInvalid                = errors.New("everlong-flamm: HookInvalid()")
	ErrHookInvalidAddress         = errors.New("everlong-flamm: HookInvalid(address)")
	ErrHookSetNotReady            = errors.New("everlong-flamm: HookSetNotReady()")
	ErrImplementationCodeChanged  = errors.New("everlong-flamm: ImplementationCodeChanged()")
	ErrImplementationNotReady     = errors.New("everlong-flamm: ImplementationNotReady()")
	ErrImplementationVersion      = errors.New("everlong-flamm: ImplementationVersion(uint32,uint32)")
	ErrInsufficientBridge         = errors.New("everlong-flamm: InsufficientBridge(uint256)")
	ErrInsufficientCollateral     = errors.New("everlong-flamm: InsufficientCollateral(uint256)")
	ErrInsufficientLiquidity      = errors.New("everlong-flamm: InsufficientLiquidity(uint256)")
	ErrInvalidAmount              = errors.New("everlong-flamm: InvalidAmount()")
	ErrInvalidBounds              = errors.New("everlong-flamm: InvalidBounds()")
	ErrInvalidConfig              = errors.New("everlong-flamm: InvalidConfig()")
	ErrInvalidInitialization      = errors.New("everlong-flamm: InvalidInitialization()")
	ErrInvalidPair                = errors.New("everlong-flamm: InvalidPair()")
	ErrInvalidPrice               = errors.New("everlong-flamm: InvalidPrice(address)")
	ErrIrmUnreadable              = errors.New("everlong-flamm: IrmUnreadable()")
	ErrKindUnknown                = errors.New("everlong-flamm: KindUnknown()")
	ErrLedgerBoundBreached        = errors.New("everlong-flamm: LedgerBoundBreached()")
	ErrLevBelowFloor              = errors.New("everlong-flamm: LevBelowFloor()")
	ErrLevPaused                  = errors.New("everlong-flamm: LevPaused()")
	ErrLevValueLeak               = errors.New("everlong-flamm: LevValueLeak()")
	ErrLeverageDisabled           = errors.New("everlong-flamm: LeverageDisabled()")
	ErrLoanAssetInExceeded        = errors.New("everlong-flamm: LoanAssetInExceeded()")
	ErrLoanAssetKnown             = errors.New("everlong-flamm: LoanAssetKnown()")
	ErrLoanAssetOutBelowMin       = errors.New("everlong-flamm: LoanAssetOutBelowMin()")
	ErrLoanLegRequired            = errors.New("everlong-flamm: LoanLegRequired()")
	ErrLoanNotEmpty               = errors.New("everlong-flamm: LoanNotEmpty()")
	ErrLoanRetired                = errors.New("everlong-flamm: LoanRetired()")
	ErrLoanSwapDisabled           = errors.New("everlong-flamm: LoanSwapDisabled()")
	ErrLtvFloorBreached           = errors.New("everlong-flamm: LtvFloorBreached()")
	ErrLtvLltvGap                 = errors.New("everlong-flamm: LtvLltvGap()")
	ErrLtvStepTooLarge            = errors.New("everlong-flamm: LtvStepTooLarge()")
	ErrMarketUnknown              = errors.New("everlong-flamm: MarketUnknown()")
	ErrNestedCallback             = errors.New("everlong-flamm: NestedCallback()")
	ErrNoDebt                     = errors.New("everlong-flamm: NoDebt()")
	ErrNoDeployerScheduled        = errors.New("everlong-flamm: NoDeployerScheduled(uint8)")
	ErrNoHookSetScheduled         = errors.New("everlong-flamm: NoHookSetScheduled()")
	ErrNoImplementationScheduled  = errors.New("everlong-flamm: NoImplementationScheduled()")
	ErrNoLoanAssetScheduled       = errors.New("everlong-flamm: NoLoanAssetScheduled()")
	ErrNoNewObservation           = errors.New("everlong-flamm: NoNewObservation()")
	ErrNoRepaySnapshot            = errors.New("everlong-flamm: NoRepaySnapshot()")
	ErrNoVenueScheduled           = errors.New("everlong-flamm: NoVenueScheduled()")
	ErrNotBootstrapped            = errors.New("everlong-flamm: NotBootstrapped()")
	ErrNotCurator                 = errors.New("everlong-flamm: NotCurator()")
	ErrNotFactory                 = errors.New("everlong-flamm: NotFactory()")
	ErrNotGuardianOrCurator       = errors.New("everlong-flamm: NotGuardianOrCurator()")
	ErrNotInitialized             = errors.New("everlong-flamm: NotInitialized()")
	ErrNotInitializing            = errors.New("everlong-flamm: NotInitializing()")
	ErrNotKeeper                  = errors.New("everlong-flamm: NotKeeper()")
	ErrNotKeeperOrCurator         = errors.New("everlong-flamm: NotKeeperOrCurator()")
	ErrNotMorpho                  = errors.New("everlong-flamm: NotMorpho()")
	ErrNotOwner                   = errors.New("everlong-flamm: NotOwner()")
	ErrNotPaused                  = errors.New("everlong-flamm: NotPaused()")
	ErrNotPool                    = errors.New("everlong-flamm: NotPool()")
	ErrNotProtocolSafe            = errors.New("everlong-flamm: NotProtocolSafe()")
	ErrNotRegistered              = errors.New("everlong-flamm: NotRegistered()")
	ErrNotRouter                  = errors.New("everlong-flamm: NotRouter()")
	ErrNothingToFill              = errors.New("everlong-flamm: NothingToFill()")
	ErrNothingToMaintain          = errors.New("everlong-flamm: NothingToMaintain()")
	ErrNothingToMove              = errors.New("everlong-flamm: NothingToMove()")
	ErrNotionalCap                = errors.New("everlong-flamm: NotionalCap()")
	ErrOracleBand                 = errors.New("everlong-flamm: OracleBand()")
	ErrOutputAboveCeiling         = errors.New("everlong-flamm: OutputAboveCeiling()")
	ErrOwnershipCannotBeRenounced = errors.New("everlong-flamm: OwnershipCannotBeRenounced()")
	ErrPaused                     = errors.New("everlong-flamm: Paused()")
	ErrPegBroken                  = errors.New("everlong-flamm: PegBroken()")
	ErrPoolBindingMismatch        = errors.New("everlong-flamm: PoolBindingMismatch()")
	ErrPredictionMismatch         = errors.New("everlong-flamm: PredictionMismatch()")
	ErrPriceBand                  = errors.New("everlong-flamm: PriceBand()")
	ErrPriceFeedMismatch          = errors.New("everlong-flamm: PriceFeedMismatch()")
	ErrPriceUnchecked             = errors.New("everlong-flamm: PriceUnchecked()")
	ErrRateCeiling                = errors.New("everlong-flamm: RateCeiling()")
	ErrReentrant                  = errors.New("everlong-flamm: Reentrant()")
	ErrRoomExceeded               = errors.New("everlong-flamm: RoomExceeded()")
	ErrRoomExhausted              = errors.New("everlong-flamm: RoomExhausted()")
	ErrSequencerDown              = errors.New("everlong-flamm: SequencerDown()")
	ErrSequencerGrace             = errors.New("everlong-flamm: SequencerGrace()")
	ErrSlippage                   = errors.New("everlong-flamm: Slippage()")
	ErrSpreadOutOfBounds          = errors.New("everlong-flamm: SpreadOutOfBounds()")
	ErrSpreadUnavailable          = errors.New("everlong-flamm: SpreadUnavailable()")
	ErrStalePair                  = errors.New("everlong-flamm: StalePair()")
	ErrStalePrice                 = errors.New("everlong-flamm: StalePrice(address)")
	ErrSupplyCapExceeded          = errors.New("everlong-flamm: SupplyCapExceeded()")
	ErrTooManyLoanAssets          = errors.New("everlong-flamm: TooManyLoanAssets()")
	ErrTooManyVenues              = errors.New("everlong-flamm: TooManyVenues()")
	ErrUnhealthy                  = errors.New("everlong-flamm: Unhealthy()")
	ErrUnknownToken               = errors.New("everlong-flamm: UnknownToken(address)")
	ErrUnsupported                = errors.New("everlong-flamm: Unsupported()")
	ErrVenueDisabled              = errors.New("everlong-flamm: VenueDisabled()")
	ErrVenueIsRetired             = errors.New("everlong-flamm: VenueIsRetired()")
	ErrVenueMismatch              = errors.New("everlong-flamm: VenueMismatch()")
	ErrVenueNotEmpty              = errors.New("everlong-flamm: VenueNotEmpty()")
	ErrVenueQuarantined           = errors.New("everlong-flamm: VenueQuarantined()")
	ErrVenueUnknown               = errors.New("everlong-flamm: VenueUnknown()")
	ErrZeroAddress                = errors.New("everlong-flamm: ZeroAddress()")
	ErrZeroPrice                  = errors.New("everlong-flamm: ZeroPrice()")
	ErrZeroShares                 = errors.New("everlong-flamm: ZeroShares()")
)

// Reverts that are not custom errors, one sentinel per on-chain revert whichever library raises it:
// OpenZeppelin 4.8 Math.mulDiv's bare `require(denominator > prod1)` (empty revert data; a zero denominator under a
// product wider than 256 bits lands here too) and Solidity's panics for checked arithmetic (0x11), division by
// zero (0x12) and an array index out of bounds (0x32).
var (
	errMulDivOverflow  = errors.New("everlong-flamm: Math.mulDiv overflow (empty revert)")
	errPanicArithmetic = errors.New("everlong-flamm: Panic(0x11)")
	errPanicDivZero    = errors.New("everlong-flamm: Panic(0x12)")
	errPanicIndex      = errors.New("everlong-flamm: Panic(0x32)")
)

// revertSelectors maps each 4-byte custom-error selector to its sentinel.
var revertSelectors = map[[4]byte]error{
	{0xfc, 0x4b, 0x9e, 0x6c}: ErrAccountCodeMismatch,        // AccountCodeMismatch()
	{0xb8, 0x07, 0xa0, 0xea}: ErrAlreadyBootstrapped,        // AlreadyBootstrapped()
	{0x0d, 0xc1, 0x49, 0xf0}: ErrAlreadyInitialized,         // AlreadyInitialized()
	{0x3a, 0x81, 0xd6, 0xfc}: ErrAlreadyRegistered,          // AlreadyRegistered()
	{0xfc, 0x57, 0xeb, 0xae}: ErrAnchorOutOfBounds,          // AnchorOutOfBounds()
	{0x2b, 0x43, 0x4c, 0x20}: ErrBadKind,                    // BadKind()
	{0x04, 0xa2, 0x4d, 0x00}: ErrBadLoanIndex,               // BadLoanIndex()
	{0xdc, 0x22, 0x89, 0x8f}: ErrBadPriorities,              // BadPriorities()
	{0xe2, 0x90, 0x48, 0x6f}: ErrBadReceiver,                // BadReceiver()
	{0x4c, 0x85, 0x66, 0xdd}: ErrBadVenueId,                 // BadVenueId()
	{0xce, 0xfb, 0x77, 0x38}: ErrBelowMinimumShares,         // BelowMinimumShares()
	{0x81, 0x2d, 0x2c, 0x18}: ErrConservation,               // Conservation()
	{0xef, 0x6d, 0xae, 0xb0}: ErrContextMismatch,            // ContextMismatch()
	{0x7e, 0x16, 0xb8, 0xcd}: ErrCreateFailed,               // CreateFailed()
	{0xfb, 0x62, 0x0e, 0x8c}: ErrCurveAmplification,         // CurveAmplification()
	{0xe3, 0x92, 0x2b, 0x5c}: ErrCurveDomain,                // CurveDomain()
	{0xd4, 0x7a, 0xb8, 0x82}: ErrCurvePriceOutOfDomain,      // CurvePriceOutOfDomain()
	{0x3b, 0xc0, 0x6a, 0x54}: ErrCurveReprices,              // CurveReprices()
	{0xb7, 0x9f, 0x5c, 0xa9}: ErrCurveSpan,                  // CurveSpan()
	{0xb4, 0x0f, 0x79, 0x2e}: ErrCustodyMismatch,            // CustodyMismatch()
	{0x7d, 0xb9, 0x10, 0x6f}: ErrDebtCapExceeded,            // DebtCapExceeded()
	{0x56, 0x8d, 0x5a, 0x84}: ErrDebtOutstanding,            // DebtOutstanding()
	{0x63, 0x80, 0x7a, 0xd1}: ErrDeployerInvalid,            // DeployerInvalid(uint8,address)
	{0x3d, 0x9c, 0x05, 0x8e}: ErrDeployerNotReady,           // DeployerNotReady(uint8)
	{0x93, 0x5d, 0x63, 0x0c}: ErrDepositCapExceeded,         // DepositCapExceeded()
	{0x98, 0xe8, 0x45, 0xfa}: ErrDepositNotPermitted,        // DepositNotPermitted()
	{0x45, 0x3b, 0xc6, 0x65}: ErrDialCooldown,               // DialCooldown()
	{0x82, 0x33, 0xef, 0xb5}: ErrDialOutOfEnvelope,          // DialOutOfEnvelope()
	{0x8c, 0xdb, 0xe7, 0x66}: ErrDrawOutsideDrawnSet,        // DrawOutsideDrawnSet()
	{0x52, 0x8d, 0x16, 0x67}: ErrDuplicateLoanAsset,         // DuplicateLoanAsset()
	{0x8c, 0xce, 0x95, 0xa1}: ErrDuplicateVenue,             // DuplicateVenue()
	{0xfb, 0x8f, 0x41, 0xb2}: ErrERC20InsufficientAllowance, // ERC20InsufficientAllowance(address,uint256,uint256)
	{0xe4, 0x50, 0xd3, 0x8c}: ErrERC20InsufficientBalance,   // ERC20InsufficientBalance(address,uint256,uint256)
	{0xe6, 0x02, 0xdf, 0x05}: ErrERC20InvalidApprover,       // ERC20InvalidApprover(address)
	{0xec, 0x44, 0x2f, 0x05}: ErrERC20InvalidReceiver,       // ERC20InvalidReceiver(address)
	{0x96, 0xc6, 0xfd, 0x1e}: ErrERC20InvalidSender,         // ERC20InvalidSender(address)
	{0x94, 0x28, 0x0d, 0x62}: ErrERC20InvalidSpender,        // ERC20InvalidSpender(address)
	{0x9d, 0x8c, 0x40, 0x1b}: ErrExactDelta,                 // ExactDelta()
	{0x84, 0x36, 0x9e, 0xea}: ErrExitWorsensLedger,          // ExitWorsensLedger()
	{0x20, 0x3d, 0x82, 0xd8}: ErrExpired,                    // Expired()
	{0x6d, 0x2d, 0x9f, 0x49}: ErrFeatureDisabled,            // FeatureDisabled(uint8)
	{0x36, 0xa9, 0xd0, 0x11}: ErrFeeMismatch,                // FeeMismatch()
	{0x26, 0x36, 0x3b, 0x73}: ErrFeeOutOfBounds,             // FeeOutOfBounds()
	{0x77, 0x41, 0x74, 0x54}: ErrFillInvalid,                // FillInvalid()
	{0x02, 0x4a, 0x31, 0x9c}: ErrFillMismatch,               // FillMismatch()
	{0xf6, 0x4d, 0xc1, 0xcd}: ErrFillPriceBand,              // FillPriceBand()
	{0x88, 0x18, 0x22, 0x65}: ErrFillValueDrop,              // FillValueDrop()
	{0xd6, 0xba, 0x11, 0xd5}: ErrFrameUnquotable,            // FrameUnquotable()
	{0x8b, 0xee, 0x70, 0x4f}: ErrGlobalPaused,               // GlobalPaused()
	{0xd3, 0xb3, 0x8b, 0x4c}: ErrGuardianMayOnlyTighten,     // GuardianMayOnlyTighten()
	{0x4b, 0xdf, 0xed, 0x04}: ErrHookInvalid,                // HookInvalid()
	{0x31, 0xc1, 0x1a, 0x6e}: ErrHookInvalidAddress,         // HookInvalid(address)
	{0x5e, 0xcd, 0x35, 0xf4}: ErrHookSetNotReady,            // HookSetNotReady()
	{0x44, 0xab, 0x10, 0xa2}: ErrImplementationCodeChanged,  // ImplementationCodeChanged()
	{0x69, 0x53, 0x34, 0xe2}: ErrImplementationNotReady,     // ImplementationNotReady()
	{0x0b, 0x29, 0xcb, 0x79}: ErrImplementationVersion,      // ImplementationVersion(uint32,uint32)
	{0x10, 0x00, 0xbd, 0xe7}: ErrInsufficientBridge,         // InsufficientBridge(uint256)
	{0x2b, 0x3b, 0xc9, 0x85}: ErrInsufficientCollateral,     // InsufficientCollateral(uint256)
	{0xc7, 0x30, 0x33, 0x3f}: ErrInsufficientLiquidity,      // InsufficientLiquidity(uint256)
	{0x2c, 0x52, 0x11, 0xc6}: ErrInvalidAmount,              // InvalidAmount()
	{0xa8, 0x83, 0x43, 0x57}: ErrInvalidBounds,              // InvalidBounds()
	{0x35, 0xbe, 0x3a, 0xc8}: ErrInvalidConfig,              // InvalidConfig()
	{0xf9, 0x2e, 0xe8, 0xa9}: ErrInvalidInitialization,      // InvalidInitialization()
	{0x1e, 0x4f, 0x7d, 0x8c}: ErrInvalidPair,                // InvalidPair()
	{0xcd, 0x21, 0x50, 0x06}: ErrInvalidPrice,               // InvalidPrice(address)
	{0xa4, 0xfe, 0x5f, 0x8b}: ErrIrmUnreadable,              // IrmUnreadable()
	{0x65, 0xb4, 0x22, 0x9b}: ErrKindUnknown,                // KindUnknown()
	{0x52, 0xbf, 0x12, 0x35}: ErrLedgerBoundBreached,        // LedgerBoundBreached()
	{0x2e, 0xa2, 0xdc, 0xe8}: ErrLevBelowFloor,              // LevBelowFloor()
	{0x78, 0xd6, 0x12, 0xf2}: ErrLevPaused,                  // LevPaused()
	{0x28, 0x85, 0x17, 0x30}: ErrLevValueLeak,               // LevValueLeak()
	{0x27, 0x33, 0xd0, 0xd9}: ErrLeverageDisabled,           // LeverageDisabled()
	{0xdf, 0xab, 0x7f, 0xcc}: ErrLoanAssetInExceeded,        // LoanAssetInExceeded()
	{0xcd, 0x56, 0x76, 0x2d}: ErrLoanAssetKnown,             // LoanAssetKnown()
	{0x35, 0xaa, 0xe9, 0xa5}: ErrLoanAssetOutBelowMin,       // LoanAssetOutBelowMin()
	{0x81, 0xec, 0x41, 0xe2}: ErrLoanLegRequired,            // LoanLegRequired()
	{0x7f, 0x5c, 0xab, 0x2b}: ErrLoanNotEmpty,               // LoanNotEmpty()
	{0x95, 0x5d, 0x4b, 0x2f}: ErrLoanRetired,                // LoanRetired()
	{0x63, 0x2d, 0x8a, 0x7f}: ErrLoanSwapDisabled,           // LoanSwapDisabled()
	{0x77, 0xd4, 0x1c, 0x1e}: ErrLtvFloorBreached,           // LtvFloorBreached()
	{0xc0, 0xd0, 0xdb, 0xc5}: ErrLtvLltvGap,                 // LtvLltvGap()
	{0x20, 0xa3, 0x98, 0x3b}: ErrLtvStepTooLarge,            // LtvStepTooLarge()
	{0x73, 0x27, 0x82, 0x26}: ErrMarketUnknown,              // MarketUnknown()
	{0xba, 0x02, 0xf2, 0xb1}: ErrNestedCallback,             // NestedCallback()
	{0x11, 0xa3, 0xfb, 0xc6}: ErrNoDebt,                     // NoDebt()
	{0xa9, 0x75, 0xe0, 0x0e}: ErrNoDeployerScheduled,        // NoDeployerScheduled(uint8)
	{0x85, 0x8e, 0xe0, 0x47}: ErrNoHookSetScheduled,         // NoHookSetScheduled()
	{0x96, 0x4a, 0x1f, 0xe3}: ErrNoImplementationScheduled,  // NoImplementationScheduled()
	{0x9e, 0x31, 0x9a, 0xa4}: ErrNoLoanAssetScheduled,       // NoLoanAssetScheduled()
	{0xbf, 0x15, 0x21, 0x0d}: ErrNoNewObservation,           // NoNewObservation()
	{0x76, 0xa2, 0x3c, 0xbf}: ErrNoRepaySnapshot,            // NoRepaySnapshot()
	{0x1d, 0xdd, 0x47, 0x3b}: ErrNoVenueScheduled,           // NoVenueScheduled()
	{0x6e, 0x27, 0xae, 0x10}: ErrNotBootstrapped,            // NotBootstrapped()
	{0x56, 0xb3, 0x81, 0xa5}: ErrNotCurator,                 // NotCurator()
	{0x32, 0xcc, 0x72, 0x36}: ErrNotFactory,                 // NotFactory()
	{0x2c, 0x3b, 0xe8, 0x50}: ErrNotGuardianOrCurator,       // NotGuardianOrCurator()
	{0x87, 0x13, 0x8d, 0x5c}: ErrNotInitialized,             // NotInitialized()
	{0xd7, 0xe6, 0xbc, 0xf8}: ErrNotInitializing,            // NotInitializing()
	{0xf5, 0x12, 0xb2, 0x78}: ErrNotKeeper,                  // NotKeeper()
	{0xc1, 0xd8, 0xf9, 0x4b}: ErrNotKeeperOrCurator,         // NotKeeperOrCurator()
	{0xe5, 0x1b, 0x51, 0x23}: ErrNotMorpho,                  // NotMorpho()
	{0x30, 0xcd, 0x74, 0x71}: ErrNotOwner,                   // NotOwner()
	{0x6c, 0xd6, 0x02, 0x01}: ErrNotPaused,                  // NotPaused()
	{0x6f, 0x61, 0xf6, 0x41}: ErrNotPool,                    // NotPool()
	{0x1d, 0x6c, 0x5b, 0x13}: ErrNotProtocolSafe,            // NotProtocolSafe()
	{0xab, 0xa4, 0x73, 0x39}: ErrNotRegistered,              // NotRegistered()
	{0x91, 0x65, 0x52, 0x01}: ErrNotRouter,                  // NotRouter()
	{0x7c, 0x3f, 0xa3, 0xaf}: ErrNothingToFill,              // NothingToFill()
	{0x07, 0x9a, 0x93, 0xc0}: ErrNothingToMaintain,          // NothingToMaintain()
	{0xd7, 0x7d, 0x93, 0xd3}: ErrNothingToMove,              // NothingToMove()
	{0xf9, 0xb4, 0x67, 0x8a}: ErrNotionalCap,                // NotionalCap()
	{0xab, 0xa9, 0xac, 0x38}: ErrOracleBand,                 // OracleBand()
	{0xc6, 0x52, 0x0d, 0xe3}: ErrOutputAboveCeiling,         // OutputAboveCeiling()
	{0x2f, 0xab, 0x92, 0xca}: ErrOwnershipCannotBeRenounced, // OwnershipCannotBeRenounced()
	{0x9e, 0x87, 0xfa, 0xc8}: ErrPaused,                     // Paused()
	{0x85, 0xc2, 0xbe, 0x22}: ErrPegBroken,                  // PegBroken()
	{0x67, 0xbe, 0x49, 0xe5}: ErrPoolBindingMismatch,        // PoolBindingMismatch()
	{0xd5, 0x3c, 0x78, 0xd1}: ErrPredictionMismatch,         // PredictionMismatch()
	{0xfe, 0x85, 0xbb, 0x51}: ErrPriceBand,                  // PriceBand()
	{0x48, 0xe1, 0x48, 0x43}: ErrPriceFeedMismatch,          // PriceFeedMismatch()
	{0xc0, 0xfd, 0x97, 0x0f}: ErrPriceUnchecked,             // PriceUnchecked()
	{0xb2, 0xef, 0x0f, 0x93}: ErrRateCeiling,                // RateCeiling()
	{0xed, 0x3b, 0xa6, 0xa6}: ErrReentrant,                  // Reentrant()
	{0xd6, 0xf8, 0xf8, 0x9c}: ErrRoomExceeded,               // RoomExceeded()
	{0x84, 0xf5, 0x27, 0x0a}: ErrRoomExhausted,              // RoomExhausted()
	{0x03, 0x2b, 0x3d, 0x00}: ErrSequencerDown,              // SequencerDown()
	{0xc3, 0x73, 0x4d, 0xc2}: ErrSequencerGrace,             // SequencerGrace()
	{0x7d, 0xd3, 0x7f, 0x70}: ErrSlippage,                   // Slippage()
	{0x73, 0x1d, 0x22, 0x8a}: ErrSpreadOutOfBounds,          // SpreadOutOfBounds()
	{0xc8, 0x1f, 0x12, 0x09}: ErrSpreadUnavailable,          // SpreadUnavailable()
	{0x95, 0x34, 0xe2, 0xb0}: ErrStalePair,                  // StalePair()
	{0x81, 0x92, 0x79, 0x29}: ErrStalePrice,                 // StalePrice(address)
	{0xf5, 0x8f, 0x73, 0x3a}: ErrSupplyCapExceeded,          // SupplyCapExceeded()
	{0x0f, 0xcc, 0x23, 0x7b}: ErrTooManyLoanAssets,          // TooManyLoanAssets()
	{0x2a, 0xec, 0xb6, 0xac}: ErrTooManyVenues,              // TooManyVenues()
	{0x7d, 0xb7, 0xa0, 0x74}: ErrUnhealthy,                  // Unhealthy()
	{0x81, 0xa3, 0xb1, 0xbe}: ErrUnknownToken,               // UnknownToken(address)
	{0x90, 0xa2, 0xca, 0xf2}: ErrUnsupported,                // Unsupported()
	{0xc8, 0x07, 0x12, 0x40}: ErrVenueDisabled,              // VenueDisabled()
	{0x57, 0x4d, 0x7f, 0xff}: ErrVenueIsRetired,             // VenueIsRetired()
	{0xde, 0x7e, 0x3c, 0xb2}: ErrVenueMismatch,              // VenueMismatch()
	{0x8d, 0x13, 0xb1, 0xc8}: ErrVenueNotEmpty,              // VenueNotEmpty()
	{0xbf, 0x13, 0x9b, 0xcd}: ErrVenueQuarantined,           // VenueQuarantined()
	{0x43, 0x0d, 0x4a, 0x31}: ErrVenueUnknown,               // VenueUnknown()
	{0xd9, 0x2e, 0x23, 0x3d}: ErrZeroAddress,                // ZeroAddress()
	{0x4d, 0xfb, 0xa0, 0x23}: ErrZeroPrice,                  // ZeroPrice()
	{0x98, 0x11, 0xe0, 0xc7}: ErrZeroShares,                 // ZeroShares()
}
