package everlongflamm

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"testing"

	"github.com/holiman/uint256"
	"github.com/stretchr/testify/require"
)

// Edge fixtures for levcurve.go and levhook.go (testdata/edges/lev_{curve,hook}_edges.json.gz), generated by
// testdata/gen/LevCurveEdges.t.sol and LevHookEdges.t.sol on a Base fork. A row is [op, inputs, [status,
// words...]]: status 0 carries the ABI return words verbatim, status 1 the revert as [len, selector, first argument
// word]. Public curve ops ran on the deployed CollRebalancerMath and
// were asserted equal (in Solidity) to a verbatim internal-visibility copy that produced the internal-op rows;
// hook ops ran on the deployed EverlongLeverageHook with the swap hook's bookFor/reservationPriceWad mocked.

type levEdgeRow struct {
	Op   string
	In   []*uint256.Int
	Outs []*uint256.Int
	in   json.RawMessage
}

// inputs decodes the row's inputs (levEdgeLoad leaves them raw: a sampled replay decodes only the rows it keeps).
func (r *levEdgeRow) inputs(t *testing.T) {
	if r.In == nil {
		r.In = levEdgeWords(t, r.in)
	}
}

const (
	levEdgeCurveFixture       = "testdata/edges/lev_curve_edges.json.gz"
	levEdgeCurveFixtureSha256 = "12ac1f76ce0eb7b9d03d8440a738b23a18abb531b19866321db12eb01ca66cd4"
	levEdgeHookFixture        = "testdata/edges/lev_hook_edges.json.gz"
	levEdgeHookFixtureSha256  = "ef4a9141f4e6704cc84f14ebda69caccbc709fdda30762a76517cf384653f579"
)

func levEdgeLoad(t *testing.T, path, digest string) []levEdgeRow {
	t.Helper()
	raw, err := os.ReadFile(path)
	require.NoError(t, err)
	sum := sha256.Sum256(raw)
	require.Equal(t, digest, hex.EncodeToString(sum[:]), "%s is not the pinned fixture", path)
	gz, err := gzip.NewReader(bytes.NewReader(raw))
	require.NoError(t, err)
	data, err := io.ReadAll(gz)
	require.NoError(t, err)
	// The document is {"block":N,"rows":[[op,[inputs],[outs]],...,["end",[],[]]],"count":N}, one row per line. It is
	// scanned by hand rather than by encoding/json, which the race detector makes the slowest part of the replay;
	// the inputs stay raw until a row is replayed (levEdgeRow.inputs).
	start := bytes.Index(data, []byte(`"rows":[`))
	require.GreaterOrEqual(t, start, 0, "no rows")
	var count struct {
		Count int `json:"count"`
	}
	end := bytes.LastIndex(data, []byte(`]],"count":`))
	require.Positive(t, end, "no count")
	require.NoError(t, json.Unmarshal(append([]byte("{"), data[end+3:]...), &count))
	var rows []levEdgeRow
	for _, line := range bytes.Split(data[start+len(`"rows":[`):end+1], []byte("\n")) {
		line = bytes.TrimSuffix(bytes.TrimSpace(line), []byte(","))
		if len(line) == 0 {
			continue
		}
		// ["op",[inputs],[outs]]
		require.True(t, bytes.HasPrefix(line, []byte(`["`)) && bytes.HasSuffix(line, []byte("]]")), "row %q", line)
		q := bytes.IndexByte(line[2:], '"') + 2
		inEnd := bytes.IndexByte(line[q:], ']') + q
		require.True(t, bytes.HasPrefix(line[q:], []byte(`",[`)) && inEnd > q, "row %q", line)
		r := levEdgeRow{Op: string(line[2:q]), in: json.RawMessage(line[q+2 : inEnd+1])}
		outs := line[inEnd+1 : len(line)-1]
		require.True(t, bytes.HasPrefix(outs, []byte(",[")), "row %q", line)
		r.Outs = levEdgeWords(t, outs[1:])
		rows = append(rows, r)
	}
	require.Equal(t, count.Count+1, len(rows), "row count")
	require.Equal(t, "end", rows[count.Count].Op)
	for _, r := range rows[:count.Count] {
		require.NotEmpty(t, r.Outs)
	}
	return rows[:count.Count]
}

func levEdgeWords(t *testing.T, raw json.RawMessage) []*uint256.Int {
	body := bytes.TrimSuffix(bytes.TrimPrefix(bytes.TrimSpace(raw), []byte("[")), []byte("]"))
	if len(bytes.TrimSpace(body)) == 0 {
		return []*uint256.Int{}
	}
	parts := bytes.Split(body, []byte(","))
	out := make([]*uint256.Int, len(parts))
	for i, p := range parts {
		v, err := uint256.FromDecimal(string(bytes.TrimSpace(p)))
		require.NoError(t, err, "word %q", p)
		out[i] = v
	}
	return out
}

func levEdgeBool(b bool) *uint256.Int {
	if b {
		return uOne
	}
	return uZero
}

func levEdgeWordsOf(xs ...any) []*uint256.Int {
	out := make([]*uint256.Int, 0, len(xs))
	for _, x := range xs {
		switch v := x.(type) {
		case bool:
			out = append(out, levEdgeBool(v))
		case *uint256.Int:
			out = append(out, v)
		default:
			panic(fmt.Sprintf("unexpected %T", x))
		}
	}
	return out
}

// levEdgeCurveEval evaluates one curve op in Go and returns its ABI words. internal reports whether the op is a
// private library function (whose out-of-domain Solidity reverts are not reachable from any entrypoint).
func levEdgeCurveEval(op string, in []*uint256.Int) (words []*uint256.Int, internal bool) {
	switch op {
	case "fp":
		p := levCurveFrozenParams()
		words = append(words, p[:]...)
		return append(words, uZero, uZero, uZero, uZero), false
	case "ab":
		x, b := levAnchorAndBase(in[0], in[1], in[2], in[3])
		return levEdgeWordsOf(x, b), false
	case "lq":
		o, c, d := levLeverageQuote(in[0], in[1], in[2], in[3], in[4], in[5])
		return levEdgeWordsOf(o, c, d), false
	case "dq":
		o, c, d := levDeleverageQuote(in[0], in[1], in[2], in[3], in[4], in[5])
		return levEdgeWordsOf(o, c, d), false
	case "ss":
		return levEdgeWordsOf(levIsStateSafe(in[0], in[1], in[2], in[3], in[4])), false
	case "mv":
		cv, ok := levMarkedValue(in[0], in[1])
		return levEdgeWordsOf(ok, cv), true
	case "sa":
		ok, a, h, half := levStrictAnchor(in[0], in[1], in[2])
		return levEdgeWordsOf(ok, a, h, half), true
	case "hla":
		return levEdgeWordsOf(levHalfLawAnchor(in[0], in[1])), true
	case "ric":
		return levEdgeWordsOf(levRootIntervalContains(in[0], in[1], in[2])), true
	case "cvr":
		ok, cv := levCvRequiredOnAnchor(in[0], in[1])
		return levEdgeWordsOf(ok, cv), true
	case "dcap":
		ok, d := levDebtCapOnAnchor(in[0], in[1])
		return levEdgeWordsOf(ok, d), true
	case "rs":
		r := levRecoveryStateFor(in[0], in[1], in[2])
		if !r.ok {
			return levEdgeWordsOf(false), true
		}
		return levEdgeWordsOf(true, r.anchor, r.baseX, r.y, r.wallCv, r.wallDebt, r.stableToWall), true
	case "rdy":
		return levEdgeWordsOf(levRecoveryDebtAtY(in[0], in[1])), true
	case "dsp":
		return levEdgeWordsOf(levDeleverageSpread(in[0], in[1], in[2])), true
	case "pr":
		o, s := levDeleverageProRata(in[0], in[1], in[2], in[3], in[4], in[5], in[6])
		return levEdgeWordsOf(o, s), true
	case "rdl":
		o, c, d := levRecoveryDeleverage(in[0], in[1], in[2], in[3], in[4], in[5], in[6])
		return levEdgeWordsOf(o, c, d), true
	case "psa":
		return levEdgeWordsOf(levPostStrictAnchorAccepted(in[0], in[1], in[2], in[3], in[4], in[5])), true
	case "paa":
		return levEdgeWordsOf(levPostAnyAnchorAccepted(in[0], in[1], in[2], in[3], in[4], in[5])), true
	case "abe":
		return levEdgeWordsOf(levAnchorBestEffortCv(in[0], in[1], in[2])), true
	case "phi":
		return levEdgeWordsOf(levPhiWad(in[0])), true
	case "dn":
		return levEdgeWordsOf(levDebtNormWad(in[0])), true
	case "lerp":
		return levEdgeWordsOf(levLerpFloor(in[0], in[1], in[2])), true
	case "b3":
		return levEdgeWordsOf(levBezier3(in[0])), true
	case "b4":
		return levEdgeWordsOf(levBezier4(in[0])), true
	case "m512":
		hi, lo := levMul512(in[0], in[1])
		return levEdgeWordsOf(&hi, &lo), true
	case "pgt":
		return levEdgeWordsOf(levProductGt(in[0], in[1], in[2], in[3])), true
	}
	return nil, false
}

// levEdgeRowKey is a row's sampling stream (the op) and outcome class (sampleRows): the revert, or a success with
// its first answer word when that word is a flag or small count.
func levEdgeRowKey(r *levEdgeRow) (stream, class string) {
	stream = r.Op
	switch {
	case !r.Outs[0].IsZero() && len(r.Outs) > 2:
		return stream, "revert " + r.Outs[2].Hex()
	case !r.Outs[0].IsZero():
		return stream, "revert"
	case len(r.Outs) > 1 && r.Outs[1].LtUint64(4):
		return stream, "ok " + r.Outs[1].Dec()
	}
	return stream, "ok"
}

func TestLevCurveEdges(t *testing.T) {
	t.Parallel()
	rows := levEdgeLoad(t, levEdgeCurveFixture, levEdgeCurveFixtureSha256)
	keep := sampleRows(len(rows), rowSampling{stride: 16, rare: 128}, func(i int) (string, string) { return levEdgeRowKey(&rows[i]) })
	counts := map[string]int{}
	skipped := 0
	var mismatches []string
	for i := range rows {
		if !keep[i] {
			continue
		}
		r := &rows[i]
		r.inputs(t)
		want, internal := levEdgeCurveEval(r.Op, r.In)
		require.NotNil(t, want, "row %d: unknown op %q", i, r.Op)
		if !r.Outs[0].IsZero() {
			// Solidity reverted: only allowed for private helpers driven out of their callers' domain.
			require.True(t, internal, "row %d: public op %s reverted in Solidity", i, r.Op)
			skipped++
			continue
		}
		got := r.Outs[1:]
		if r.Op == "rs" && got[0].IsZero() {
			got = got[:1]
		}
		if len(got) != len(want) {
			mismatches = append(mismatches, fmt.Sprintf("row %d %s in=%v: word count sol=%d go=%d", i, r.Op, r.In, len(got), len(want)))
			continue
		}
		for k := range want {
			if !got[k].Eq(want[k]) {
				mismatches = append(mismatches, fmt.Sprintf("row %d %s in=%v word %d: sol=%s go=%s", i, r.Op, r.In, k, got[k].Dec(), want[k].Dec()))
				break
			}
		}
		counts[r.Op]++
	}
	t.Logf("compared %d of %d rows (%v), %d internal out-of-domain reverts skipped", kept(keep)-skipped, len(rows), counts,
		skipped)
	for j, m := range mismatches {
		if j == 50 {
			break
		}
		t.Error(m)
	}
	require.Empty(t, mismatches)
}

// levEdgeRevert maps a recorded [len, selector, arg] revert to the Go error the port must return.
func levEdgeRevert(outs []*uint256.Int) error {
	if outs[1].IsZero() {
		return errMulDivOverflow
	}
	sel := outs[2].Uint64()
	key := [4]byte{byte(sel >> 24), byte(sel >> 16), byte(sel >> 8), byte(sel)}
	if key == [4]byte{0x4e, 0x48, 0x7b, 0x71} {
		if outs[3].Uint64() == 0x11 {
			return errPanicArithmetic
		}
		return fmt.Errorf("unmodelled Panic(0x%x)", outs[3].Uint64())
	}
	if err, ok := revertSelectors[key]; ok {
		return err
	}
	return fmt.Errorf("unmapped revert selector %x", key)
}

func levEdgeHookInputs(in []*uint256.Int) (*leverContext, *levBook) {
	book := &levBook{Rs: in[1], Is: in[2], Rv: in[3], Iv: in[4], ReservationPriceWad: in[6]}
	ctx := &leverContext{
		Pool: poolContext{
			PhysicalPoolAsset: *in[7],
			PostedPoolAsset:   *in[8],
			LiquidLoanAsset:   *in[9],
			SuppliedLoanAsset: *in[10],
			DebtLoanAsset:     *in[11],
			ShareSupply:       *in[12],
			PriceWad:          *in[13],
			PriceTs:           in[14].Uint64(),
			LoanCount:         uint8(in[15].Uint64()),
		},
		Up:        !in[16].IsZero(),
		SpreadPpm: *in[17],
		AmountIn:  *in[18],
		MaxOut:    *in[19],
	}
	return ctx, book
}

func TestLevHookEdges(t *testing.T) {
	t.Parallel()
	rows := levEdgeLoad(t, levEdgeHookFixture, levEdgeHookFixtureSha256)
	keep := sampleRows(len(rows), rowSampling{stride: 16, rare: 600}, func(i int) (string, string) { return levEdgeRowKey(&rows[i]) })
	outcomes := map[string]int{}
	var mismatches []string
	for i := range rows {
		if !keep[i] {
			continue
		}
		r := &rows[i]
		r.inputs(t)
		var words []*uint256.Int
		var err error
		switch r.Op {
		case "hf":
			ctx, book := levEdgeHookInputs(r.In)
			var f *levFrame
			if f, err = levFrameFor(&ctx.Pool, book); err == nil {
				words = levEdgeWordsOf(f.Cv, (*uint256.Int)(f.D), f.V, f.S, f.XAnchor)
			}
		case "hq":
			ctx, book := levEdgeHookInputs(r.In)
			var fill *levFill
			if fill, err = levQuote(ctx, book); err == nil {
				words = levEdgeWordsOf(fill.AmountInUsed, fill.GrossOut, fill.VirtualLegL18, fill.CrAfterWad)
			}
		case "band":
			err = levAssertAnchorAndBand(r.In[0], r.In[1], r.In[2])
		default:
			t.Fatalf("row %d: unknown op %q", i, r.Op)
		}
		msg := fmt.Sprintf("row %d %s in=%v", i, r.Op, r.In)
		if !r.Outs[0].IsZero() {
			want := levEdgeRevert(r.Outs)
			outcomes[r.Op+":"+want.Error()]++
			if !errors.Is(err, want) {
				mismatches = append(mismatches, fmt.Sprintf("%s: sol revert %v, go err=%v words=%v", msg, want, err, words))
			}
			continue
		}
		outcomes[r.Op+":ok"]++
		if err != nil {
			mismatches = append(mismatches, fmt.Sprintf("%s: sol ok %v, go err=%v", msg, r.Outs[1:], err))
			continue
		}
		got := r.Outs[1:]
		if len(got) != len(words) {
			mismatches = append(mismatches, fmt.Sprintf("%s: word count sol=%d go=%d", msg, len(got), len(words)))
			continue
		}
		for k := range words {
			if !got[k].Eq(words[k]) {
				mismatches = append(mismatches, fmt.Sprintf("%s word %d: sol=%s go=%s", msg, k, got[k].Dec(), words[k].Dec()))
				break
			}
		}
	}
	t.Logf("compared %d of %d rows: %v", kept(keep), len(rows), outcomes)
	for j, m := range mismatches {
		if j == 50 {
			break
		}
		t.Error(m)
	}
	require.Empty(t, mismatches)
}
