package swaplimitmsgp

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	kyberpmm "github.com/KyberNetwork/kyberswap-dex-lib/pkg/source/kyber-pmm"
	"github.com/KyberNetwork/kyberswap-dex-lib/pkg/source/synthetix"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *SwapLimitEnum) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "Inventory")
			return
		}
		z.Inventory = nil
	} else {
		if z.Inventory == nil {
			z.Inventory = new(kyberpmm.Inventory)
		}
		err = z.Inventory.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "Inventory")
			return
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "AtomicLimits")
			return
		}
		z.AtomicLimits = nil
	} else {
		if z.AtomicLimits == nil {
			z.AtomicLimits = new(synthetix.AtomicLimits)
		}
		err = z.AtomicLimits.DecodeMsg(dc)
		if err != nil {
			err = msgp.WrapError(err, "AtomicLimits")
			return
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SwapLimitEnum) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	if z.Inventory == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Inventory.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Inventory")
			return
		}
	}
	if z.AtomicLimits == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.AtomicLimits.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "AtomicLimits")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SwapLimitEnum) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	if z.Inventory == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.Inventory.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Inventory")
			return
		}
	}
	if z.AtomicLimits == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.AtomicLimits.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "AtomicLimits")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SwapLimitEnum) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.Inventory = nil
	} else {
		if z.Inventory == nil {
			z.Inventory = new(kyberpmm.Inventory)
		}
		bts, err = z.Inventory.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "Inventory")
			return
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.AtomicLimits = nil
	} else {
		if z.AtomicLimits == nil {
			z.AtomicLimits = new(synthetix.AtomicLimits)
		}
		bts, err = z.AtomicLimits.UnmarshalMsg(bts)
		if err != nil {
			err = msgp.WrapError(err, "AtomicLimits")
			return
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SwapLimitEnum) Msgsize() (s int) {
	s = 1
	if z.Inventory == nil {
		s += msgp.NilSize
	} else {
		s += z.Inventory.Msgsize()
	}
	if z.AtomicLimits == nil {
		s += msgp.NilSize
	} else {
		s += z.AtomicLimits.Msgsize()
	}
	return
}
