env: "production"
pprof: false
http:
  bindAddress: ":8080"
  mode: release #(debug,release,test)
  prefix: /aurora
grpc:
  host: 0.0.0.0
  port: 10443
common:
  chainId: &chainId 1313161554
  chainName: &chainName aurora
  rpc: "https://mainnet.aurora.dev"
  multicallAddress: "0xcA11bde05977b3631167028862bE2a173976CA11"
  executorAddress: &executorAddress "0xd1B47490209CcB7A806E8a45d9479490C040ABf4"
  routerAddress: &routerAddress "0x6131B5fae19EA4f9D964eAc0408E4408b66337b5"
  gasTokenAddress: &gasTokenAddress "0xc9bdeed33cd01541e1eed10f90519d2c06fe3feb"
  whitelistedTokenSet: &whitelistedTokenSet
    0x8bec47865ade3b172a928df8f990bc7f2a3b9f79: true # AURORA
    0xc42c30ac6cc15fac9bd938618bcaa1a1fae8501d: true # NEAR
    0xc9bdeed33cd01541e1eed10f90519d2c06fe3feb: true # WETH
    0x4988a896b1227218e4a686fde5eabdcabd91571f: true # USDT
    0xe3520349f477a5f6eb06107066048508498a291b: true # DAI
    0xb12bfca5a55806aaf64e99521918a4bf0fc40802: true # USDC
    0xf4eb217ba2454613b15dbdea6e5f22276410e89e: true # WBTC
    0x885f8cf6e45bdd3fdcdc644efdcd0ac93880c781: true # PAD
  blacklistedPoolSet: &blacklistedPoolSet
  availableSources: &availableSources
    - "kyberswap"
    - "kyberswap-static"
    - "trisolaris"
    - "wannaswap"
    - "nearpad"
    - "dodo"
    - "curve"
    - "curve-stable-plain"
  featureFlags: &featureFlags
log:
  sentryDSN: "https://6cd398671bde455f8fadad6dbfe87a67@sentry-v2.knstats.com/48"
  consoleLevel: info
  enableConsole: true
  enableJSONFormat: true
redis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
pregenRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
poolEventRedis:
  addresses:
  masterName: ""
  dbNumber: 0
  password: ""
  prefix: *chainName
  readTimeout: 3s
  writeTimeout: 3s
  readOnly: false
  routeRandomly: false
ddAgentHost: ""
keyPair:
  storageFilePath: ""
  keyIDForSealingData:
    clientData: "1"
reloadConfig:
  httpUrl: ""
  interval: 10s
  serviceName: "aggregator"
  chainID: *chainId
secretKey:
metrics:
  host:
  port: 8125
  namespace: "kybernetwork."
encoder:
  chainId: *chainId
  executorAddress: *executorAddress
  routerAddress: *routerAddress
  isPositiveSlippageEnabled: true
  minimumPSThreshold: 1000000
useCase:
  getRoute:
    chainId: *chainId
    gasTokenAddress: *gasTokenAddress
    routerAddress: *routerAddress
    availableSources: *availableSources
    aggregator:
      whitelistedTokenSet: *whitelistedTokenSet
      getBestPoolsOptions:
        directPoolsCount: 100
        whitelistPoolsCount: 500
        tokenInPoolsCount: 200
        tokenOutPoolCount: 200
        amplifiedTvlDirectPoolsCount: 50
        amplifiedTvlWhitelistPoolsCount: 200
        amplifiedTvlTokenInPoolsCount: 100
        amplifiedTvlTokenOutPoolCount: 100
      finderOptions:
        maxHops: 3
        distributionPercent: 5
        maxPathsInRoute: 20
        maxPathsToGenerate: 5
        maxPathsToReturn: 200
        minPartUSD: 500
        minThresholdAmountInUSD: 0
        maxThresholdAmountInUSD: 100000000
        isHillClimbEnabled: false
        hillClimbDistributionPercent: 1
        hillClimbIteration: 2
        hillClimbMinPartUSD: 500
        isPathGeneratorEnabled: false
    cache:
      defaultTtl: 15s
      ttlByAmount:
        - amount: 1
          ttl: 30s
        - amount: 2
          ttl: 10s
        - amount: 5
          ttl: 10s
        - amount: 10
          ttl: 10s
        - amount: 11
          ttl: 30s
        - amount: 15
          ttl: 10s
        - amount: 20
          ttl: 10s
        - amount: 22
          ttl: 30s
        - amount: 25
          ttl: 10s
        - amount: 30
          ttl: 10s
        - amount: 33
          ttl: 30s
        - amount: 35
          ttl: 10s
        - amount: 40
          ttl: 10s
        - amount: 44
          ttl: 30s
        - amount: 45
          ttl: 10s
        - amount: 50
          ttl: 10s
        - amount: 55
          ttl: 30s
        - amount: 60
          ttl: 10s
        - amount: 66
          ttl: 30s
        - amount: 70
          ttl: 10s
        - amount: 77
          ttl: 30s
        - amount: 80
          ttl: 10s
        - amount: 88
          ttl: 30s
        - amount: 90
          ttl: 10s
        - amount: 99
          ttl: 30s
        - amount: 100
          ttl: 10s
        - amount: 500
          ttl: 10s
        - amount: 1000
          ttl: 10s
        - amount: 10000
          ttl: 10s
        - amount: 100000
          ttl: 10s
      ttlByAmountUsdRange:
        - amountUSDLowerBound: 0
          ttl: 10s
        - amountUSDLowerBound: 101
          ttl: 10s
        - amountUSDLowerBound: 500
          ttl: 10s
        - amountUSDLowerBound: 1001
          ttl: 10s
        - amountUSDLowerBound: 2000
          ttl: 10s
        - amountUSDLowerBound: 5000
          ttl: 10s
        - amountUSDLowerBound: 10000
          ttl: 10s
      ttlByAmountRange:
        - amountLowerBound: "0"
          ttl: 30s
        - amountLowerBound: "5e18"
          ttl: 10s
      priceImpactThreshold: 0.005
      shrinkFuncName: "round"
      shrinkDecimalBase: 10
      shrinkFuncPowExp: 0.7
      shrinkFuncLogPercent: 1.01
      enableNewCacheKeyGenerator: false
      shrinkAmountInConfig:
        shrinkFuncName: "decimal"
        shrinkDecimalBase: 100
        shrinkFuncPowExp: 0.7
        shrinkFuncLogPercent: 1.05
      shrinkAmountInThreshold: 100000
  buildRoute:
    chainId: *chainId
    faultyPools:
      windowSize: 15m
      faultyExpiredTime: 3m
  poolFactory:
    chainId: *chainId
  poolManager:
    blacklistedPoolSet: *blacklistedPoolSet
    blackListRenewalInterval: 30s
    capacity: 1000000
    poolRenewalInterval: 3s
    faultyPoolsExpireThreshold: 3s
    maxFaultyPoolSize: 500
  indexPools:
    whitelistedTokenSet: *whitelistedTokenSet
    chunkSize: 3000
    maxGoroutines: 0
    enableRankByNative: false
  trackExecutor:
    subgraphURL: https://api.thegraph.com/subgraphs/name/kybernetwork/kyberswap-aggregator-aurora
job:
  indexPools:
    forceScanAllEveryNth: 10
    interval: 2s
    poolEvent:
      consumerConfig:
        prefix: *chainName
        stream: "pool_events"
        group: "router_indexPools"
        key: "message"
        block: 300ms
        count: 100
        bufferSize: 20
        ackBufferSize: 10
      batchRate: 700ms
      batchSize: 100
      retryInterval: 5s
  updateSuggestedGasPrice:
    interval: 15s
  trackExecutorBalance:
    interval: 1h
repository:
  gas:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 5000
      maxCost: 500
      bufferItems: 64
      suggestedGasPrice:
        cost: 1
        ttl: 2m
  pool:
    redis:
      prefix: *chainName
  price:
    redis:
      prefix: *chainName
    ristretto:
      numCounters: 10000
      maxCost: 1000
      bufferItems: 64
      price:
        cost: 1
        ttl: 1m
  poolService:
    baseUrl: "0.0.0.0:10443"
    insecure: true
    timeout: 100ms
    chainId: *chainId
  token:
    redis:
      prefix: *chainName
    goCache:
      expiration: -1
      cleanupInterval: -1
  poolRank:
    redis:
      prefix: *chainName
  route:
    redisCache:
      prefix: *chainName
      localCacheSize: 5000
      localCacheTtl: 30s
  blackjack:
    grpcClient:
      baseURL: blackjack.core-cluster.gke.production.internal:80
      insecure: true
      timeout: 100ms
  erc20balanceslot:
    redis:
      prefix: *chainName
validator:
  buildRouteParams:
    slippageToleranceGte: 0
    slippageToleranceLte: 5000
    blacklistedRecipientSet:
  getRouteEncodeParams:
    slippageToleranceGte: 0
    slippageToleranceLte: 5000
    blacklistedRecipientSet:
