// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/KyberNetwork/kyberswap-dex-lib/pkg/source/gmx (interfaces: IUSDQReader)

// Package gmx is a generated GoMock package.
package quickperps

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUSDQReader is a mock of IUSDQReader interface.
type MockIUSDQReader struct {
	ctrl     *gomock.Controller
	recorder *MockIUSDQReaderMockRecorder
}

// MockIUSDQReaderMockRecorder is the mock recorder for MockIUSDQReader.
type MockIUSDQReaderMockRecorder struct {
	mock *MockIUSDQReader
}

// NewMockIUSDQReader creates a new mock instance.
func NewMockIUSDQReader(ctrl *gomock.Controller) *MockIUSDQReader {
	mock := &MockIUSDQReader{ctrl: ctrl}
	mock.recorder = &MockIUSDQReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUSDQReader) EXPECT() *MockIUSDQReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockIUSDQReader) Read(arg0 context.Context, arg1 string) (*USDQ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(*USDQ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockIUSDQReaderMockRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockIUSDQReader)(nil).Read), arg0, arg1)
}
