package valueobject

type Exchange string

const (
	ExchangeAlienBaseStableSwap        = "alien-base-stableswap"
	ExchangeAmbient                    = "ambient"
	ExchangeApeSwap                    = "apeswap"
	ExchangeArberaDen                  = "arbera-den"
	ExchangeArberaDenAmm               = "arbera-den-amm"
	ExchangeArberaStake                = "arbera-stake"
	ExchangeArberaZap                  = "arbera-zap"
	ExchangeArbiDex                    = "arbi-dex"
	ExchangeArenaBC                    = "arena-bc"
	ExchangeAstroSwap                  = "astroswap"
	ExchangeAxial                      = "axial"
	ExchangeAxima                      = "axima"
	ExchangeBabyDogeSwap               = "babydogeswap"
	ExchangeBakerySwap                 = "bakeryswap"
	ExchangeBalancerV1                 = "balancer-v1"
	ExchangeBalancerV2ComposableStable = "balancer-v2-composable-stable"
	ExchangeBalancerV2Stable           = "balancer-v2-stable"
	ExchangeBalancerV2Weighted         = "balancer-v2-weighted"
	ExchangeBalancerV3ECLP             = "balancer-v3-eclp"
	ExchangeBalancerV3QuantAMM         = "balancer-v3-quantamm"
	ExchangeBalancerV3ReCLAMM          = "balancer-v3-reclamm"
	ExchangeBalancerV3Stable           = "balancer-v3-stable"
	ExchangeBalancerV3Weighted         = "balancer-v3-weighted"
	ExchangeBancorV3                   = "bancor-v3"
	ExchangeBancorV21                  = "bancor-v21"
	ExchangeBebop                      = "bebop"
	ExchangeBedrockUniBTC              = "bedrock-unibtc"
	ExchangeBedrockUniETH              = "bedrock-unieth"
	ExchangeBeefySonic                 = "beefy-sonic"
	ExchangeBeethovenXComposableStable = "beethovenx-composable-stable"
	ExchangeBeethovenXStable           = "beethovenx-stable"
	ExchangeBeethovenXV3ECLP           = "beethovenx-v3-eclp"
	ExchangeBeethovenXV3QuantAMM       = "beethovenx-v3-quantamm"
	ExchangeBeethovenXV3ReCLAMM        = "beethovenx-v3-reclamm"
	ExchangeBeethovenXV3Stable         = "beethovenx-v3-stable"
	ExchangeBeethovenXV3Weighted       = "beethovenx-v3-weighted"
	ExchangeBeethovenXWeighted         = "beethovenx-weighted"
	ExchangeBeetsSS                    = "beets-ss"
	ExchangeBeracaine                  = "beracaine"
	ExchangeBeraSwapComposableStable   = "beraswap-composable-stable"
	ExchangeBeraSwapStable             = "beraswap-stable"
	ExchangeBeraSwapWeighted           = "beraswap-weighted"
	ExchangeBiSwap                     = "biswap"
	ExchangeBMX                        = "bmx"
	ExchangeBMXGLP                     = "bmx-glp"
	ExchangeBrownfi                    = "brownfi"
	ExchangeBrownfiV2                  = "brownfi-v2"
	ExchangeBurrBearComposableStable   = "burrbear-composable-stable"
	ExchangeBurrBearStable             = "burrbear-stable"
	ExchangeBurrBearWeighted           = "burrbear-weighted"
	ExchangeCarbon                     = "carbon"
	ExchangeClear                      = "clear"
	ExchangeClipper                    = "clipper"
	ExchangeCloberOB                   = "clober-ob"
	ExchangeCoinhaneV3ECLP             = "coinhane-v3-eclp"
	ExchangeCoinhaneV3ReCLAMM          = "coinhane-v3-reclamm"
	ExchangeCoinhaneV3Stable           = "coinhane-v3-stable"
	ExchangeCoinhaneV3Weighted         = "coinhane-v3-weighted"
	ExchangeCometh                     = "cometh"
	ExchangeCompoundV2                 = "compound-v2"
	ExchangeCronaSwap                  = "cronaswap"
	ExchangeCurve                      = "curve"
	ExchangeCurveLending               = "curve-lending"
	ExchangeCurveLlamma                = "curve-llamma"
	ExchangeCurveStableMetaNg          = "curve-stable-meta-ng"
	ExchangeCurveStableNg              = "curve-stable-ng"
	ExchangeCurveStablePlain           = "curve-stable-plain"
	ExchangeCurveTriCryptoNg           = "curve-tricrypto-ng"
	ExchangeCurveTwoCryptoNg           = "curve-twocrypto-ng"
	ExchangeCUSD                       = "cusd"
	ExchangeDaiUsds                    = "dai-usds"
	ExchangeDeltaSwapV1                = "deltaswap-v1"
	ExchangeDexalot                    = "dexalot"
	ExchangeDinoSwap                   = "dinoswap"
	ExchangeDodo                       = "dodo"
	ExchangeDodoClassical              = "dodo-classical"
	ExchangeDodoPrivatePool            = "dodo-dpp"
	ExchangeDodoStablePool             = "dodo-dsp"
	ExchangeDodoVendingMachine         = "dodo-dvm"
	ExchangeDystopia                   = "dystopia"
	ExchangeEkubo                      = "ekubo"
	ExchangeEkuboV3                    = "ekubo-v3"
	ExchangeElfomofi                   = "elfomofi"
	ExchangeEllipsis                   = "ellipsis"
	ExchangeERC4626                    = "erc4626"
	ExchangeEthenaSusde                = "ethena-susde"
	ExchangeEtherexV2                  = "etherex-v2"
	ExchangeEtherFieBTC                = "etherfi-ebtc"
	ExchangeEtherfiEETH                = "etherfi-eeth"
	ExchangeEtherfiLiquid              = "etherfi-liquid"
	ExchangeEtherfiVampire             = "etherfi-vampire"
	ExchangeEtherfiWEETH               = "etherfi-weeth"
	ExchangeEtherVista                 = "ether-vista"
	ExchangeEulerSwap                  = "euler-swap"
	ExchangeEulerSwapV2                = "euler-swap-v2"
	ExchangeFakePool                   = "fake-pool"
	ExchangeFluidDexLite               = "fluid-dex-lite"
	ExchangeFluidDexT1                 = "fluid-dex-t1"
	ExchangeFluidDexV2                 = "fluid-dex-v2"
	ExchangeFluidVaultT1               = "fluid-vault-t1"
	ExchangeFrxETH                     = "frxeth"
	ExchangeFrxUSD                     = "frxusd"
	ExchangeGenericArm                 = "generic-arm"
	ExchangeGravity                    = "gravity"
	ExchangeGsm4626                    = "gsm-4626"
	ExchangeGyroscope2CLP              = "gyroscope-2clp"
	ExchangeGyroscope3CLP              = "gyroscope-3clp"
	ExchangeGyroscopeECLP              = "gyroscope-eclp"
	ExchangeHashflowV3                 = "hashflow-v3"
	ExchangeHoney                      = "honey"
	ExchangeHyeth                      = "hyeth"
	ExchangeHyperpieV2                 = "hyperpie-v2"
	ExchangeInfinifi                   = "infinifi-gateway"
	ExchangeInfinityPools              = "infinitypools"
	ExchangeIntegral                   = "integral"
	ExchangeJetSwap                    = "jetswap"
	ExchangeKanseiV2                   = "kansei-v2"
	ExchangeKatanaV3                   = "katana-v3"
	ExchangeKelpRSETH                  = "kelp-rseth"
	ExchangeKelpRSETHL2                = "kelp-rseth-l2"
	ExchangeKodiakV2                   = "kodiak-v2"
	ExchangeKokonutCrypto              = "kokonut-crypto"
	ExchangeKrptoDex                   = "kryptodex"
	ExchangeKTX                        = "ktx"
	ExchangeKuruOB                     = "kuru-ob"
	ExchangeKyberPMM                   = "kyber-pmm"
	ExchangeKipseliProp                = "kipseli-prop"
	ExchangeKyberSwapLimitOrder        = "kyberswap-limit-order"
	ExchangeKyberSwapLimitOrderDS      = "kyberswap-limit-order-v2"
	ExchangeLiquidCore                 = "liquidcore"
	ExchangeListaStable                = "lista-stable"
	ExchangeLitePSM                    = "lite-psm"
	ExchangeLO1inch                    = "lo1inch"
	ExchangeMakerLido                  = "lido"
	ExchangeMakerLidoStETH             = "lido-steth"
	ExchangeMakerPSM                   = "maker-psm"
	ExchangeMakerSavingsDai            = "maker-savingsdai"
	ExchangeMantisSwap                 = "mantisswap"
	ExchangeMantleETH                  = "meth"
	ExchangeMapleSyrup                 = "maple-syrup"
	ExchangeMaverickV2                 = "maverick-v2"
	ExchangeMemeBox                    = "memebox"
	ExchangeMeshSwap                   = "meshswap"
	ExchangeMetropolis                 = "metropolis"
	ExchangeMidas                      = "midas"
	ExchangeMimSwap                    = "mimswap"
	ExchangeMiroMigrator               = "miro-migrator"
	ExchangeMkrSky                     = "mkr-sky"
	ExchangeMMF                        = "mmf"
	ExchangeMorpheus                   = "morpheus"
	ExchangeMuteSwitch                 = "muteswitch"
	ExchangeNabla                      = "nabla"
	ExchangeNadFun                     = "nad-fun"
	ExchangeNativeV1                   = "native-v1"
	ExchangeNativeV2                   = "native-v2"
	ExchangeNativeV3                   = "native-v3"
	ExchangeNomiswap                   = "nomiswap"
	ExchangeOETH                       = "oeth"
	ExchangeOmniBin                    = "omni-bin"
	ExchangeOmniCL                     = "omni-cl"
	ExchangeOndoUSDY                   = "ondo-usdy"
	ExchangeOneSwap                    = "oneswap"
	ExchangeOvernightUsdp              = "overnight-usdp"
	ExchangePancake                    = "pancake"
	ExchangePancakeInfinityBin         = "pancake-infinity-bin"
	ExchangePancakeInfinityBinBrevis   = "pancake-infinity-bin-brevis"
	ExchangePancakeInfinityBinFairflow = "pancake-infinity-bin-fairflow"
	ExchangePancakeInfinityCL          = "pancake-infinity-cl"
	ExchangePancakeInfinityCLAlpha     = "pancake-infinity-cl-alpha"
	ExchangePancakeInfinityCLBrevis    = "pancake-infinity-cl-brevis"
	ExchangePancakeInfinityCLDynamic   = "pancake-infinity-cl-dynamic"
	ExchangePancakeInfinityCLFairflow  = "pancake-infinity-cl-fairflow"
	ExchangePancakeInfinityCLLO        = "pancake-infinity-cl-lo"
	ExchangePancakeInfinityCLTax       = "pancake-infinity-cl-tax"
	ExchangePancakeLegacy              = "pancake-legacy"
	ExchangePancakeStable              = "pancake-stable"
	ExchangePandaFun                   = "panda-fun"
	ExchangePantherSwap                = "pantherswap"
	ExchangeParallelParallelizer       = "parallel-parallelizer"
	ExchangePharaoh2                   = "pharaoh-2"
	ExchangePlatypus                   = "platypus"
	ExchangePmm1                       = "pmm-1"
	ExchangePmm2                       = "pmm-2"
	ExchangePmm3                       = "pmm-3"
	ExchangePmm4                       = "pmm-4"
	ExchangePmm5                       = "pmm-5"
	ExchangePmm6                       = "pmm-6"
	ExchangePolMatic                   = "pol-matic"
	ExchangePolycat                    = "polycat"
	ExchangePolyDex                    = "polydex"
	ExchangePoolParty                  = "pool-party"
	ExchangePrimeETH                   = "primeeth"
	ExchangePufferPufETH               = "puffer-pufeth"
	ExchangeRamses                     = "ramses"
	ExchangeRenzoEZETH                 = "renzo-ezeth"
	ExchangeRingSwap                   = "ringswap"
	ExchangeRocketPoolRETH             = "rocketpool-reth"
	ExchangeSafeSwap                   = "safeswap"
	ExchangeSavingsUSDS                = "savings-usds"
	ExchangeSboom                      = "sboom"
	ExchangeSfrxETH                    = "sfrxeth"
	ExchangeSfrxETHConvertor           = "sfrxeth-convertor"
	ExchangeShadowLegacy               = "shadow-legacy"
	ExchangeSkyPSM                     = "sky-psm"
	ExchangeSmardex                    = "smardex"
	ExchangeSmoothy                    = "smoothy"
	ExchangeSolidlyV2                  = "solidly-v2"
	ExchangeSomeSwapV1                 = "someswap-v1"
	ExchangeSonicMarket                = "sonic-market"
	ExchangeSpookySwap                 = "spookyswap"
	ExchangeStaderETHx                 = "staderethx"
	ExchangeSuperlendV3                = "superlend-v3"
	ExchangeSushiSwap                  = "sushiswap"
	ExchangeSwaapV2                    = "swaap-v2"
	ExchangeSwapr                      = "swapr"
	ExchangeSwellRSWETH                = "swell-rsweth"
	ExchangeSwellSWETH                 = "swell-sweth"
	ExchangeSwyrlV2                    = "swyrl-v2"
	ExchangeSyncSwap                   = "syncswap"
	ExchangeSyncSwapV2Aqua             = "syncswapv2-aqua"
	ExchangeSyncSwapV2Classic          = "syncswapv2-classic"
	ExchangeSyncSwapV2Stable           = "syncswapv2-stable"
	ExchangeSynthetix                  = "synthetix"
	ExchangeTessera                    = "tessera"
	ExchangeThenaFusionV3              = "thena-fusion-v3"
	ExchangeUniSwap                    = "uniswap"
	ExchangeUniswapLO                  = "uniswap-lo"
	ExchangeUniSwapV1                  = "uniswap-v1"
	ExchangeUniSwapV3                  = "uniswapv3"
	ExchangeUniswapV4                  = "uniswap-v4"
	ExchangeUniswapV4Aegis             = "uniswap-v4-aegis"
	ExchangeUniswapV4Angstrom          = "uniswap-v4-angstrom"
	ExchangeUniswapV4Arena             = "uniswap-v4-arena"
	ExchangeUniswapV4Arrakis           = "uniswap-v4-arrakis"
	ExchangeUniswapV4BunniV2           = "uniswap-v4-bunni-v2"
	ExchangeUniswapV4Clanker           = "uniswap-v4-clanker"
	ExchangeUniswapV4Cult              = "uniswap-v4-cult"
	ExchangeUniswapV4Deli              = "uniswap-v4-deli"
	ExchangeUniswapV4Doppler           = "uniswap-v4-doppler"
	ExchangeUniswapV4Euler             = "uniswap-v4-euler"
	ExchangeUniswapV4EulerV2           = "uniswap-v4-euler-v2"
	ExchangeUniswapV4FairFlow          = "uniswap-v4-fairflow"
	ExchangeUniswapV4Flaunch           = "uniswap-v4-flaunch"
	ExchangeUniswapV4Kem               = "uniswap-v4-kem"
	ExchangeUniswapV4NftStrategy       = "uniswap-v4-nftstrat"
	ExchangeUniswapV4Renzo             = "uniswap-v4-renzo"
	ExchangeUniswapV4Zora              = "uniswap-v4-zora"
	ExchangeUsd0PP                     = "usd0pp"
	ExchangeUsdsLitePsm                = "usds-lite-psm"
	ExchangeValantisStex               = "valantis-stex"
	ExchangeVelocoreV2CPMM             = "velocore-v2-cpmm"
	ExchangeVelocoreV2WombatStable     = "velocore-v2-wombat-stable"
	ExchangeVelodromeV2                = "velodrome-v2"
	ExchangeVirtualFun                 = "virtual-fun"
	ExchangeVooi                       = "vooi"
	ExchangeWagyuSwap                  = "wagyuswap"
	ExchangeWault                      = "wault"
	ExchangeWBETH                      = "wbeth"
	ExchangeWildcard                   = "wildcard"
	ExchangeWombat                     = "wombat"
	ExchangeWooFiV2                    = "woofi-v2"
	ExchangeWooFiV3                    = "woofi-v3"
	ExchangeWrappedNative              = "wrapped-native"
	ExchangeWRSETH                     = "wrseth"
	ExchangeXSolvBTC                   = "xsolvbtc"
)

var RFQSourceSet = map[Exchange]struct{}{
	ExchangeKyberSwapLimitOrderDS: {},
	ExchangeLO1inch:               {},

	ExchangeBebop:      {},
	ExchangeClipper:    {},
	ExchangeDexalot:    {},
	ExchangeHashflowV3: {},
	ExchangeKyberPMM:   {},
	ExchangeNativeV1:   {},
	ExchangeNativeV2:   {},
	ExchangePmm1:       {},
	ExchangePmm2:       {},
	ExchangePmm3:       {},
	ExchangePmm4:       {},
	ExchangePmm5:       {},
	ExchangePmm6:       {},
	ExchangeSwaapV2:    {},
	ExchangeUniswapLO:  {},
}

func IsRFQSource(exchange Exchange) bool {
	_, ok := RFQSourceSet[exchange]
	return ok
}

// needFallbackSourceSet is a set of exchanges that
// need to have a fallback swap (in addition to RFQ sources).
var needFallbackSourceSet = map[Exchange]struct{}{
	ExchangeAxima: {},
}

func NeedsFallbackSource(exchange Exchange) bool {
	if _, ok := needFallbackSourceSet[exchange]; ok {
		return true
	}

	return IsRFQSource(exchange)
}

// SingleSwapSourceSet is a set of exchanges that
// only allow a single swap in a route.
var SingleSwapSourceSet = map[Exchange]struct{}{
	ExchangeBebop:          {},
	ExchangeClipper:        {},
	ExchangeOvernightUsdp:  {},
	ExchangeUniswapV4Euler: {},
	ExchangeEulerSwap:      {},
	ExchangeEulerSwapV2:    {},
	ExchangeWooFiV3:        {},
}

func IsSingleSwapSource(exchange Exchange) bool {
	_, ok := SingleSwapSourceSet[exchange]
	return ok
}
