package stable

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/KyberNetwork/kyberswap-dex-lib/pkg/msgpencode"
	"github.com/holiman/uint256"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PoolSimulator) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 10 {
		err = msgp.ArrayError{Wanted: 10, Got: zb0001}
		return
	}
	err = z.Pool.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	z.paused, err = dc.ReadBool()
	if err != nil {
		err = msgp.WrapError(err, "paused")
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "swapFeePercentage")
			return
		}
		z.swapFeePercentage = nil
	} else {
		{
			var zb0002 []byte
			zb0002, err = dc.ReadBytes(msgpencode.EncodeUint256(z.swapFeePercentage))
			if err != nil {
				err = msgp.WrapError(err, "swapFeePercentage")
				return
			}
			z.swapFeePercentage = msgpencode.DecodeUint256(zb0002)
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "amp")
			return
		}
		z.amp = nil
	} else {
		{
			var zb0003 []byte
			zb0003, err = dc.ReadBytes(msgpencode.EncodeUint256(z.amp))
			if err != nil {
				err = msgp.WrapError(err, "amp")
				return
			}
			z.amp = msgpencode.DecodeUint256(zb0003)
		}
	}
	var zb0004 uint32
	zb0004, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "scalingFactors")
		return
	}
	if cap(z.scalingFactors) >= int(zb0004) {
		z.scalingFactors = (z.scalingFactors)[:zb0004]
	} else {
		z.scalingFactors = make([]*uint256.Int, zb0004)
	}
	for za0001 := range z.scalingFactors {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, "scalingFactors", za0001)
				return
			}
			z.scalingFactors[za0001] = nil
		} else {
			{
				var zb0005 []byte
				zb0005, err = dc.ReadBytes(msgpencode.EncodeUint256(z.scalingFactors[za0001]))
				if err != nil {
					err = msgp.WrapError(err, "scalingFactors", za0001)
					return
				}
				z.scalingFactors[za0001] = msgpencode.DecodeUint256(zb0005)
			}
		}
	}
	z.vault, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "vault")
		return
	}
	z.poolID, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "poolID")
		return
	}
	z.poolSpec, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "poolSpec")
		return
	}
	z.poolType, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "poolType")
		return
	}
	z.poolTypeVer, err = dc.ReadInt()
	if err != nil {
		err = msgp.WrapError(err, "poolTypeVer")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PoolSimulator) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 10
	err = en.Append(0x9a)
	if err != nil {
		return
	}
	err = z.Pool.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	err = en.WriteBool(z.paused)
	if err != nil {
		err = msgp.WrapError(err, "paused")
		return
	}
	if z.swapFeePercentage == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(msgpencode.EncodeUint256(z.swapFeePercentage))
		if err != nil {
			err = msgp.WrapError(err, "swapFeePercentage")
			return
		}
	}
	if z.amp == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(msgpencode.EncodeUint256(z.amp))
		if err != nil {
			err = msgp.WrapError(err, "amp")
			return
		}
	}
	err = en.WriteArrayHeader(uint32(len(z.scalingFactors)))
	if err != nil {
		err = msgp.WrapError(err, "scalingFactors")
		return
	}
	for za0001 := range z.scalingFactors {
		if z.scalingFactors[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = en.WriteBytes(msgpencode.EncodeUint256(z.scalingFactors[za0001]))
			if err != nil {
				err = msgp.WrapError(err, "scalingFactors", za0001)
				return
			}
		}
	}
	err = en.WriteString(z.vault)
	if err != nil {
		err = msgp.WrapError(err, "vault")
		return
	}
	err = en.WriteString(z.poolID)
	if err != nil {
		err = msgp.WrapError(err, "poolID")
		return
	}
	err = en.WriteUint8(z.poolSpec)
	if err != nil {
		err = msgp.WrapError(err, "poolSpec")
		return
	}
	err = en.WriteString(z.poolType)
	if err != nil {
		err = msgp.WrapError(err, "poolType")
		return
	}
	err = en.WriteInt(z.poolTypeVer)
	if err != nil {
		err = msgp.WrapError(err, "poolTypeVer")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PoolSimulator) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 10
	o = append(o, 0x9a)
	o, err = z.Pool.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	o = msgp.AppendBool(o, z.paused)
	if z.swapFeePercentage == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, msgpencode.EncodeUint256(z.swapFeePercentage))
	}
	if z.amp == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, msgpencode.EncodeUint256(z.amp))
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.scalingFactors)))
	for za0001 := range z.scalingFactors {
		if z.scalingFactors[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o = msgp.AppendBytes(o, msgpencode.EncodeUint256(z.scalingFactors[za0001]))
		}
	}
	o = msgp.AppendString(o, z.vault)
	o = msgp.AppendString(o, z.poolID)
	o = msgp.AppendUint8(o, z.poolSpec)
	o = msgp.AppendString(o, z.poolType)
	o = msgp.AppendInt(o, z.poolTypeVer)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PoolSimulator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 10 {
		err = msgp.ArrayError{Wanted: 10, Got: zb0001}
		return
	}
	bts, err = z.Pool.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	z.paused, bts, err = msgp.ReadBoolBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "paused")
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.swapFeePercentage = nil
	} else {
		{
			var zb0002 []byte
			zb0002, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeUint256(z.swapFeePercentage))
			if err != nil {
				err = msgp.WrapError(err, "swapFeePercentage")
				return
			}
			z.swapFeePercentage = msgpencode.DecodeUint256(zb0002)
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.amp = nil
	} else {
		{
			var zb0003 []byte
			zb0003, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeUint256(z.amp))
			if err != nil {
				err = msgp.WrapError(err, "amp")
				return
			}
			z.amp = msgpencode.DecodeUint256(zb0003)
		}
	}
	var zb0004 uint32
	zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "scalingFactors")
		return
	}
	if cap(z.scalingFactors) >= int(zb0004) {
		z.scalingFactors = (z.scalingFactors)[:zb0004]
	} else {
		z.scalingFactors = make([]*uint256.Int, zb0004)
	}
	for za0001 := range z.scalingFactors {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.scalingFactors[za0001] = nil
		} else {
			{
				var zb0005 []byte
				zb0005, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeUint256(z.scalingFactors[za0001]))
				if err != nil {
					err = msgp.WrapError(err, "scalingFactors", za0001)
					return
				}
				z.scalingFactors[za0001] = msgpencode.DecodeUint256(zb0005)
			}
		}
	}
	z.vault, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "vault")
		return
	}
	z.poolID, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "poolID")
		return
	}
	z.poolSpec, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "poolSpec")
		return
	}
	z.poolType, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "poolType")
		return
	}
	z.poolTypeVer, bts, err = msgp.ReadIntBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "poolTypeVer")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PoolSimulator) Msgsize() (s int) {
	s = 1 + z.Pool.Msgsize() + msgp.BoolSize
	if z.swapFeePercentage == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BytesPrefixSize + len(msgpencode.EncodeUint256(z.swapFeePercentage))
	}
	if z.amp == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BytesPrefixSize + len(msgpencode.EncodeUint256(z.amp))
	}
	s += msgp.ArrayHeaderSize
	for za0001 := range z.scalingFactors {
		if z.scalingFactors[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += msgp.BytesPrefixSize + len(msgpencode.EncodeUint256(z.scalingFactors[za0001]))
		}
	}
	s += msgp.StringPrefixSize + len(z.vault) + msgp.StringPrefixSize + len(z.poolID) + msgp.Uint8Size + msgp.StringPrefixSize + len(z.poolType) + msgp.IntSize
	return
}
