package compound

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"math/big"

	"github.com/KyberNetwork/kyberswap-dex-lib/pkg/msgpencode"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CompoundPool) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 6 {
		err = msgp.ArrayError{Wanted: 6, Got: zb0001}
		return
	}
	err = z.Pool.DecodeMsg(dc)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "A")
			return
		}
		z.A = nil
	} else {
		{
			var zb0002 []byte
			zb0002, err = dc.ReadBytes(msgpencode.EncodeInt(z.A))
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
			z.A = msgpencode.DecodeInt(zb0002)
		}
	}
	var zb0003 uint32
	zb0003, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "Multipliers")
		return
	}
	if cap(z.Multipliers) >= int(zb0003) {
		z.Multipliers = (z.Multipliers)[:zb0003]
	} else {
		z.Multipliers = make([]*big.Int, zb0003)
	}
	for za0001 := range z.Multipliers {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, "Multipliers", za0001)
				return
			}
			z.Multipliers[za0001] = nil
		} else {
			{
				var zb0004 []byte
				zb0004, err = dc.ReadBytes(msgpencode.EncodeInt(z.Multipliers[za0001]))
				if err != nil {
					err = msgp.WrapError(err, "Multipliers", za0001)
					return
				}
				z.Multipliers[za0001] = msgpencode.DecodeInt(zb0004)
			}
		}
	}
	if dc.IsNil() {
		err = dc.ReadNil()
		if err != nil {
			err = msgp.WrapError(err, "AdminFee")
			return
		}
		z.AdminFee = nil
	} else {
		{
			var zb0005 []byte
			zb0005, err = dc.ReadBytes(msgpencode.EncodeInt(z.AdminFee))
			if err != nil {
				err = msgp.WrapError(err, "AdminFee")
				return
			}
			z.AdminFee = msgpencode.DecodeInt(zb0005)
		}
	}
	var zb0006 uint32
	zb0006, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "Rates")
		return
	}
	if cap(z.Rates) >= int(zb0006) {
		z.Rates = (z.Rates)[:zb0006]
	} else {
		z.Rates = make([]*big.Int, zb0006)
	}
	for za0002 := range z.Rates {
		if dc.IsNil() {
			err = dc.ReadNil()
			if err != nil {
				err = msgp.WrapError(err, "Rates", za0002)
				return
			}
			z.Rates[za0002] = nil
		} else {
			{
				var zb0007 []byte
				zb0007, err = dc.ReadBytes(msgpencode.EncodeInt(z.Rates[za0002]))
				if err != nil {
					err = msgp.WrapError(err, "Rates", za0002)
					return
				}
				z.Rates[za0002] = msgpencode.DecodeInt(zb0007)
			}
		}
	}
	var zb0008 uint32
	zb0008, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err, "gas")
		return
	}
	if zb0008 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0008}
		return
	}
	z.gas.Exchange, err = dc.ReadInt64()
	if err != nil {
		err = msgp.WrapError(err, "gas", "Exchange")
		return
	}
	z.gas.ExchangeUnderlying, err = dc.ReadInt64()
	if err != nil {
		err = msgp.WrapError(err, "gas", "ExchangeUnderlying")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CompoundPool) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 6
	err = en.Append(0x96)
	if err != nil {
		return
	}
	err = z.Pool.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if z.A == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(msgpencode.EncodeInt(z.A))
		if err != nil {
			err = msgp.WrapError(err, "A")
			return
		}
	}
	err = en.WriteArrayHeader(uint32(len(z.Multipliers)))
	if err != nil {
		err = msgp.WrapError(err, "Multipliers")
		return
	}
	for za0001 := range z.Multipliers {
		if z.Multipliers[za0001] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = en.WriteBytes(msgpencode.EncodeInt(z.Multipliers[za0001]))
			if err != nil {
				err = msgp.WrapError(err, "Multipliers", za0001)
				return
			}
		}
	}
	if z.AdminFee == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = en.WriteBytes(msgpencode.EncodeInt(z.AdminFee))
		if err != nil {
			err = msgp.WrapError(err, "AdminFee")
			return
		}
	}
	err = en.WriteArrayHeader(uint32(len(z.Rates)))
	if err != nil {
		err = msgp.WrapError(err, "Rates")
		return
	}
	for za0002 := range z.Rates {
		if z.Rates[za0002] == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = en.WriteBytes(msgpencode.EncodeInt(z.Rates[za0002]))
			if err != nil {
				err = msgp.WrapError(err, "Rates", za0002)
				return
			}
		}
	}
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.gas.Exchange)
	if err != nil {
		err = msgp.WrapError(err, "gas", "Exchange")
		return
	}
	err = en.WriteInt64(z.gas.ExchangeUnderlying)
	if err != nil {
		err = msgp.WrapError(err, "gas", "ExchangeUnderlying")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CompoundPool) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 6
	o = append(o, 0x96)
	o, err = z.Pool.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if z.A == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, msgpencode.EncodeInt(z.A))
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.Multipliers)))
	for za0001 := range z.Multipliers {
		if z.Multipliers[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			o = msgp.AppendBytes(o, msgpencode.EncodeInt(z.Multipliers[za0001]))
		}
	}
	if z.AdminFee == nil {
		o = msgp.AppendNil(o)
	} else {
		o = msgp.AppendBytes(o, msgpencode.EncodeInt(z.AdminFee))
	}
	o = msgp.AppendArrayHeader(o, uint32(len(z.Rates)))
	for za0002 := range z.Rates {
		if z.Rates[za0002] == nil {
			o = msgp.AppendNil(o)
		} else {
			o = msgp.AppendBytes(o, msgpencode.EncodeInt(z.Rates[za0002]))
		}
	}
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendInt64(o, z.gas.Exchange)
	o = msgp.AppendInt64(o, z.gas.ExchangeUnderlying)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CompoundPool) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 6 {
		err = msgp.ArrayError{Wanted: 6, Got: zb0001}
		return
	}
	bts, err = z.Pool.UnmarshalMsg(bts)
	if err != nil {
		err = msgp.WrapError(err, "Pool")
		return
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.A = nil
	} else {
		{
			var zb0002 []byte
			zb0002, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(z.A))
			if err != nil {
				err = msgp.WrapError(err, "A")
				return
			}
			z.A = msgpencode.DecodeInt(zb0002)
		}
	}
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Multipliers")
		return
	}
	if cap(z.Multipliers) >= int(zb0003) {
		z.Multipliers = (z.Multipliers)[:zb0003]
	} else {
		z.Multipliers = make([]*big.Int, zb0003)
	}
	for za0001 := range z.Multipliers {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.Multipliers[za0001] = nil
		} else {
			{
				var zb0004 []byte
				zb0004, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(z.Multipliers[za0001]))
				if err != nil {
					err = msgp.WrapError(err, "Multipliers", za0001)
					return
				}
				z.Multipliers[za0001] = msgpencode.DecodeInt(zb0004)
			}
		}
	}
	if msgp.IsNil(bts) {
		bts, err = msgp.ReadNilBytes(bts)
		if err != nil {
			return
		}
		z.AdminFee = nil
	} else {
		{
			var zb0005 []byte
			zb0005, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(z.AdminFee))
			if err != nil {
				err = msgp.WrapError(err, "AdminFee")
				return
			}
			z.AdminFee = msgpencode.DecodeInt(zb0005)
		}
	}
	var zb0006 uint32
	zb0006, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Rates")
		return
	}
	if cap(z.Rates) >= int(zb0006) {
		z.Rates = (z.Rates)[:zb0006]
	} else {
		z.Rates = make([]*big.Int, zb0006)
	}
	for za0002 := range z.Rates {
		if msgp.IsNil(bts) {
			bts, err = msgp.ReadNilBytes(bts)
			if err != nil {
				return
			}
			z.Rates[za0002] = nil
		} else {
			{
				var zb0007 []byte
				zb0007, bts, err = msgp.ReadBytesBytes(bts, msgpencode.EncodeInt(z.Rates[za0002]))
				if err != nil {
					err = msgp.WrapError(err, "Rates", za0002)
					return
				}
				z.Rates[za0002] = msgpencode.DecodeInt(zb0007)
			}
		}
	}
	var zb0008 uint32
	zb0008, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "gas")
		return
	}
	if zb0008 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0008}
		return
	}
	z.gas.Exchange, bts, err = msgp.ReadInt64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "gas", "Exchange")
		return
	}
	z.gas.ExchangeUnderlying, bts, err = msgp.ReadInt64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "gas", "ExchangeUnderlying")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CompoundPool) Msgsize() (s int) {
	s = 1 + z.Pool.Msgsize()
	if z.A == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(z.A))
	}
	s += msgp.ArrayHeaderSize
	for za0001 := range z.Multipliers {
		if z.Multipliers[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(z.Multipliers[za0001]))
		}
	}
	if z.AdminFee == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(z.AdminFee))
	}
	s += msgp.ArrayHeaderSize
	for za0002 := range z.Rates {
		if z.Rates[za0002] == nil {
			s += msgp.NilSize
		} else {
			s += msgp.BytesPrefixSize + len(msgpencode.EncodeInt(z.Rates[za0002]))
		}
	}
	s += 1 + msgp.Int64Size + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Gas) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Exchange, err = dc.ReadInt64()
	if err != nil {
		err = msgp.WrapError(err, "Exchange")
		return
	}
	z.ExchangeUnderlying, err = dc.ReadInt64()
	if err != nil {
		err = msgp.WrapError(err, "ExchangeUnderlying")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Gas) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 2
	err = en.Append(0x92)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Exchange)
	if err != nil {
		err = msgp.WrapError(err, "Exchange")
		return
	}
	err = en.WriteInt64(z.ExchangeUnderlying)
	if err != nil {
		err = msgp.WrapError(err, "ExchangeUnderlying")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Gas) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 2
	o = append(o, 0x92)
	o = msgp.AppendInt64(o, z.Exchange)
	o = msgp.AppendInt64(o, z.ExchangeUnderlying)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Gas) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 2 {
		err = msgp.ArrayError{Wanted: 2, Got: zb0001}
		return
	}
	z.Exchange, bts, err = msgp.ReadInt64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Exchange")
		return
	}
	z.ExchangeUnderlying, bts, err = msgp.ReadInt64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "ExchangeUnderlying")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Gas) Msgsize() (s int) {
	s = 1 + msgp.Int64Size + msgp.Int64Size
	return
}
