name: 'CI'

concurrency:
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release*'
  pull_request:

jobs:
  ci:
    uses: KyberNetwork/service-framework/.github/workflows/ci.yaml@main
    secrets: inherit
  build:
    uses: KyberNetwork/service-framework/.github/workflows/build.yaml@main
    with:
      service: ${{ github.event.repository.name }}
      file: docker/Dockerfile
    secrets: inherit
  build_liqIndexer:
    needs: build
    uses: KyberNetwork/service-framework/.github/workflows/build.yaml@main
    with:
      service: ${{ github.event.repository.name }}-liqindexer
      file: docker/liqIndexer.Dockerfile
    secrets: inherit
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    uses: KyberNetwork/service-framework/.github/workflows/deploy.yaml@main
    with:
      services: router-service/*/{api,indexer}
      tag: ${{ needs.build.outputs.tag }}
    secrets: inherit
  deploy_liqIndexer:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build_liqIndexer
    uses: KyberNetwork/service-framework/.github/workflows/deploy.yaml@main
    with:
      services: router-service/[^e]*/liquidity-score-indexer
      tag: ${{ needs.build_liqIndexer.outputs.tag }}
    secrets: inherit
