name: 'CI'

concurrency:
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release*'
  pull_request:

jobs:
  ci:
    uses: KyberNetwork/service-framework/.github/workflows/ci.yaml@main
    secrets: inherit
  build:
    uses: KyberNetwork/service-framework/.github/workflows/build.yaml@main
    with:
      service: ${{ github.event.repository.name }}
    secrets: inherit
