name: Check tinylib/msgp generate codes update-to-date

concurrency:
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-v**
  pull_request:

jobs:
  generate-check:
    name: Check tinylib/msgp generate codes update-to-date
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run "go generate"
        run: |
          # find all Go source files
          find . -name "*.go" |
          # filter files that contain a line starting with "//msgp" which is tinylib/msgp generating directive
          xargs -I % sh -c 'grep -m 1 "^//msgp" % > /dev/null && echo %' | 
          # get directory name aka package name of each file
          xargs -I % sh -c 'dirname %' | 
          # unique package names
          sort | uniq | 
          # run "go generate" in parallel for all packages
          xargs -P $(nproc) -I % sh -c 'go generate -run="go run github.com/tinylib/msgp.+" %'
      - name: Check working tree clean
        run: if [ -z "$(git status --porcelain)" ]; then exit 0; else exit 1; fi