name: 'Release'

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        type: string
        required: true

jobs:
  release:
    uses: KyberNetwork/service-framework/.github/workflows/release.yaml@main
    with:
      service: ${{ github.event.repository.name }}
      version: '${{ inputs.version }}'
    secrets: inherit
