name: 'Release'

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        type: string
        required: true
      create_tag:
        description: 'Create tag'
        type: boolean
        default: true

jobs:
  release:
    uses: KyberNetwork/service-framework/.github/workflows/release.yaml@main
    with:
      service: ${{ github.event.repository.name }}
      version: '${{ inputs.version }}'
      file: docker/Dockerfile
      create_tag: ${{ inputs.create_tag }}
    secrets: inherit
  release_liqIndexer:
    uses: KyberNetwork/service-framework/.github/workflows/release.yaml@main
    with:
      service: ${{ github.event.repository.name }}-liqindexer
      version: '${{ inputs.version }}'
      file: docker/liqIndexer.Dockerfile
      create_tag: false
    secrets: inherit
