package constant

type types struct {
	CurveBase                string
	CurvePlainOracle         string
	CurveMeta                string
	CurveAave                string
	CurveCompound            string
	CurveLending             string
	CurveTricrypto           string
	CurveTwo                 string
	Uni                      string
	UniV3                    string
	Biswap                   string
	CrowdswapV2              string
	Polydex                  string
	Firebird                 string
	Dmm                      string
	Elastic                  string
	Saddle                   string
	Nerve                    string
	OneSwap                  string
	IronStable               string
	BalancerWeighted         string
	BalancerStable           string
	BalancerMetaStable       string
	BalancerComposableStable string
	DodoClassical            string
	DodoVendingMachine       string
	DodoStable               string
	DodoPrivate              string
	Velodrome                string
	VelodromeV2              string
	Aerodrome                string
	Velocimeter              string
	Thena                    string
	Pearl                    string
	PearlV2                  string
	Ramses                   string
	Dystopia                 string
	PlatypusBase             string
	PlatypusPure             string
	PlatypusAvax             string
	WombatMain               string
	WombatLsd                string
	GMX                      string
	GMXGLP                   string
	MakerPSM                 string
	Synthetix                string
	MadMex                   string
	Metavault                string
	Lido                     string
	LidoStEth                string
	LimitOrder               string
	Fraxswap                 string
	Camelot                  string
	MuteSwitch               string
	SyncSwapClassic          string
	SyncSwapStable           string
	PancakeV3                string
	MaverickV1               string
	AlgebraV1                string
	TraderJoeV20             string
	KyberPMM                 string
	IZiSwap                  string
	WooFiV2                  string
	Equalizer                string
	SwapBasedPerp            string
	USDFi                    string
	ZkSwapFinance            string
	MantisSwap               string
	Vooi                     string
	PolMatic                 string
	KokonutCrypto            string
	LiquidityBookV21         string
	LiquidityBookV20         string
}

var (
	PoolTypes = types{
		CurveBase:                "curve-base",
		CurvePlainOracle:         "curve-plain-oracle",
		CurveMeta:                "curve-meta",
		CurveAave:                "curve-aave",
		CurveCompound:            "curve-compound",
		CurveLending:             "curve-lending",
		CurveTricrypto:           "curve-tricrypto",
		CurveTwo:                 "curve-two",
		Uni:                      "uniswap",
		UniV3:                    "uniswapv3",
		Biswap:                   "biswap",
		CrowdswapV2:              "crowdswap-v2",
		Polydex:                  "polydex",
		Firebird:                 "firebird",
		Dmm:                      "dmm",
		Elastic:                  "elastic",
		Saddle:                   "saddle",
		Nerve:                    "nerve",
		OneSwap:                  "oneswap",
		IronStable:               "iron-stable",
		BalancerWeighted:         "balancer-weighted",
		BalancerStable:           "balancer-stable",
		BalancerMetaStable:       "balancer-meta-stable",
		BalancerComposableStable: "balancer-composable-stable",
		DodoClassical:            "dodo-classical",
		DodoVendingMachine:       "dodo-dvm",
		DodoStable:               "dodo-dsp",
		DodoPrivate:              "dodo-dpp",
		Velodrome:                "velodrome",
		VelodromeV2:              "velodrome-v2",
		Aerodrome:                "aerodrome",
		Velocimeter:              "velocimeter",
		Thena:                    "thena",
		Pearl:                    "pearl",
		PearlV2:                  "pearl-v2",
		Ramses:                   "ramses",
		Dystopia:                 "dystopia",
		PlatypusBase:             "platypus-base",
		PlatypusPure:             "platypus-pure",
		PlatypusAvax:             "platypus-avax",
		WombatMain:               "wombat-main",
		WombatLsd:                "wombat-lsd",
		GMX:                      "gmx",
		GMXGLP:                   "gmx-glp",
		MakerPSM:                 "maker-psm",
		Synthetix:                "synthetix",
		MadMex:                   "madmex",
		Metavault:                "metavault",
		Lido:                     "lido",
		LidoStEth:                "lido-steth",
		LimitOrder:               "limit-order",
		Fraxswap:                 "fraxswap",
		Camelot:                  "camelot",
		MuteSwitch:               "muteswitch",
		SyncSwapClassic:          "syncswap-classic",
		SyncSwapStable:           "syncswap-stable",
		PancakeV3:                "pancake-v3",
		MaverickV1:               "maverick-v1",
		AlgebraV1:                "algebra-v1",
		TraderJoeV20:             "traderjoe-v20",
		KyberPMM:                 "kyber-pmm",
		IZiSwap:                  "iziswap",
		WooFiV2:                  "woofi-v2",
		Equalizer:                "equalizer",
		SwapBasedPerp:            "swapbased-perp",
		USDFi:                    "usdfi",
		ZkSwapFinance:            "zkswap-finance",
		MantisSwap:               "mantisswap",
		Vooi:                     "vooi",
		PolMatic:                 "pol-matic",
		KokonutCrypto:            "kokonut-crypto",
		LiquidityBookV21:         "liquiditybook-v21",
		LiquidityBookV20:         "liquiditybook-v20",
	}
)
