package constant

type types struct {
	CurveBase                  string
	CurvePlainOracle           string
	CurveMeta                  string
	CurveAave                  string
	CurveCompound              string
	CurveLending               string
	CurveTricrypto             string
	CurveTwo                   string
	Uni                        string
	UniV3                      string
	Biswap                     string
	CrowdswapV2                string
	Polydex                    string
	Firebird                   string
	Dmm                        string
	Elastic                    string
	Saddle                     string
	Nerve                      string
	OneSwap                    string
	IronStable                 string
	DodoClassical              string
	DodoVendingMachine         string
	DodoStable                 string
	DodoPrivate                string
	Velodrome                  string
	VelodromeV2                string
	Aerodrome                  string
	Velocimeter                string
	Thena                      string
	Pearl                      string
	PearlV2                    string
	Ramses                     string
	RamsesV2                   string
	Dystopia                   string
	PlatypusBase               string
	PlatypusPure               string
	PlatypusAvax               string
	WombatMain                 string
	WombatLsd                  string
	GMX                        string
	GMXGLP                     string
	MakerPSM                   string
	Synthetix                  string
	MadMex                     string
	Metavault                  string
	Lido                       string
	LidoStEth                  string
	LimitOrder                 string
	Fraxswap                   string
	Camelot                    string
	MuteSwitch                 string
	SyncSwapClassic            string
	SyncSwapStable             string
	PancakeV3                  string
	MaverickV1                 string
	AlgebraV1                  string
	TraderJoeV20               string
	KyberPMM                   string
	IZiSwap                    string
	WooFiV2                    string
	Equalizer                  string
	SwapBasedPerp              string
	USDFi                      string
	MantisSwap                 string
	Vooi                       string
	PolMatic                   string
	KokonutCrypto              string
	LiquidityBookV21           string
	LiquidityBookV20           string
	Smardex                    string
	Fxdx                       string
	UniswapV2                  string
	QuickPerps                 string
	BalancerV1                 string
	BalancerV2Weighted         string
	BalancerV2Stable           string
	BalancerV2ComposableStable string
	Gyroscope2CLP              string
	Gyroscope3CLP              string
	GyroscopeECLP              string
	VelocoreV2CPMM             string
	VelocoreV2WombatStable     string
	Fulcrom                    string
	SolidlyV3                  string
	ZkEraFinance               string
	SwaapV2                    string
}

var (
	PoolTypes = types{
		CurveBase:                  "curve-base",
		CurvePlainOracle:           "curve-plain-oracle",
		CurveMeta:                  "curve-meta",
		CurveAave:                  "curve-aave",
		CurveCompound:              "curve-compound",
		CurveLending:               "curve-lending",
		CurveTricrypto:             "curve-tricrypto",
		CurveTwo:                   "curve-two",
		Uni:                        "uniswap",
		UniV3:                      "uniswapv3",
		Biswap:                     "biswap",
		CrowdswapV2:                "crowdswap-v2",
		Polydex:                    "polydex",
		Firebird:                   "firebird",
		Dmm:                        "dmm",
		Elastic:                    "elastic",
		Saddle:                     "saddle",
		Nerve:                      "nerve",
		OneSwap:                    "oneswap",
		IronStable:                 "iron-stable",
		DodoClassical:              "dodo-classical",
		DodoVendingMachine:         "dodo-dvm",
		DodoStable:                 "dodo-dsp",
		DodoPrivate:                "dodo-dpp",
		Velodrome:                  "velodrome",
		VelodromeV2:                "velodrome-v2",
		Aerodrome:                  "aerodrome",
		Velocimeter:                "velocimeter",
		Thena:                      "thena",
		Pearl:                      "pearl",
		PearlV2:                    "pearl-v2",
		Ramses:                     "ramses",
		RamsesV2:                   "ramses-v2",
		Dystopia:                   "dystopia",
		PlatypusBase:               "platypus-base",
		PlatypusPure:               "platypus-pure",
		PlatypusAvax:               "platypus-avax",
		WombatMain:                 "wombat-main",
		WombatLsd:                  "wombat-lsd",
		GMX:                        "gmx",
		GMXGLP:                     "gmx-glp",
		MakerPSM:                   "maker-psm",
		Synthetix:                  "synthetix",
		MadMex:                     "madmex",
		Metavault:                  "metavault",
		Lido:                       "lido",
		LidoStEth:                  "lido-steth",
		LimitOrder:                 "limit-order",
		Fraxswap:                   "fraxswap",
		Camelot:                    "camelot",
		MuteSwitch:                 "muteswitch",
		SyncSwapClassic:            "syncswap-classic",
		SyncSwapStable:             "syncswap-stable",
		PancakeV3:                  "pancake-v3",
		MaverickV1:                 "maverick-v1",
		AlgebraV1:                  "algebra-v1",
		TraderJoeV20:               "traderjoe-v20",
		KyberPMM:                   "kyber-pmm",
		IZiSwap:                    "iziswap",
		WooFiV2:                    "woofi-v2",
		Equalizer:                  "equalizer",
		SwapBasedPerp:              "swapbased-perp",
		USDFi:                      "usdfi",
		MantisSwap:                 "mantisswap",
		Vooi:                       "vooi",
		PolMatic:                   "pol-matic",
		KokonutCrypto:              "kokonut-crypto",
		LiquidityBookV21:           "liquiditybook-v21",
		LiquidityBookV20:           "liquiditybook-v20",
		Smardex:                    "smardex",
		Fxdx:                       "fxdx",
		UniswapV2:                  "uniswap-v2",
		QuickPerps:                 "quickperps",
		BalancerV1:                 "balancer-v1",
		BalancerV2Weighted:         "balancer-v2-weighted",
		BalancerV2Stable:           "balancer-v2-stable",
		BalancerV2ComposableStable: "balancer-v2-composable-stable",
		VelocoreV2CPMM:             "velocore-v2-cpmm",
		VelocoreV2WombatStable:     "velocore-v2-wombat-stable",
		Fulcrom:                    "fulcrom",
		SolidlyV3:                  "solidly-v3",
		Gyroscope2CLP:              "gyroscope-2clp",
		Gyroscope3CLP:              "gyroscope-3clp",
		GyroscopeECLP:              "gyroscope-eclp",
		ZkEraFinance:               "zkera-finance",
		SwaapV2:                    "swaap-v2",
	}
)
