package constant

type types struct {
	CurveBase                 string
	CurvePlainOracle          string
	CurveMeta                 string
	CurveAave                 string
	CurveCompound             string
	CurveLending              string
	CurveTricrypto            string
	CurveTwo                  string
	Uni                       string
	UniV3                     string
	Biswap                    string
	Polydex                   string
	Firebird                  string
	Dmm                       string
	Elastic                   string
	Saddle                    string
	Nerve                     string
	OneSwap                   string
	IronStable                string
	BalancerWeighted          string
	BalancerStable            string
	BalancerMetaStable        string
	BalancerComposeableStable string
	DodoClassical             string
	DodoVendingMachine        string
	DodoStable                string
	DodoPrivate               string
	Velodrome                 string
	Ramses                    string
	Dystopia                  string
	PlatypusBase              string
	PlatypusPure              string
	PlatypusAvax              string
	GMX                       string
	MakerPSM                  string
	Synthetix                 string
	MadMex                    string
	Metavault                 string
	Lido                      string
	LidoStEth                 string
	LimitOrder                string
	Fraxswap                  string
	Camelot                   string
	MuteSwitch                string
	SyncSwapClassic           string
	SyncSwapStable            string
	PancakeV3                 string
}

var (
	PoolTypes = types{
		CurveBase:                 "curve-base",
		CurvePlainOracle:          "curve-plain-oracle",
		CurveMeta:                 "curve-meta",
		CurveAave:                 "curve-aave",
		CurveCompound:             "curve-compound",
		CurveLending:              "curve-lending",
		CurveTricrypto:            "curve-tricrypto",
		CurveTwo:                  "curve-two",
		Uni:                       "uniswap",
		UniV3:                     "uniswapv3",
		Biswap:                    "biswap",
		Polydex:                   "polydex",
		Firebird:                  "firebird",
		Dmm:                       "dmm",
		Elastic:                   "elastic",
		Saddle:                    "saddle",
		Nerve:                     "nerve",
		OneSwap:                   "oneswap",
		IronStable:                "iron-stable",
		BalancerWeighted:          "balancer-weighted",
		BalancerStable:            "balancer-stable",
		BalancerMetaStable:        "balancer-meta-stable",
		BalancerComposeableStable: "balancer-composable-stable",
		DodoClassical:             "dodo-classical",
		DodoVendingMachine:        "dodo-dvm",
		DodoStable:                "dodo-dsp",
		DodoPrivate:               "dodo-dpp",
		Velodrome:                 "velodrome",
		Ramses:                    "ramses",
		Dystopia:                  "dystopia",
		PlatypusBase:              "platypus-base",
		PlatypusPure:              "platypus-pure",
		PlatypusAvax:              "platypus-avax",
		GMX:                       "gmx",
		MakerPSM:                  "maker-psm",
		Synthetix:                 "synthetix",
		MadMex:                    "madmex",
		Metavault:                 "metavault",
		Lido:                      "lido",
		LidoStEth:                 "lido-steth",
		LimitOrder:                "limit-order",
		Fraxswap:                  "fraxswap",
		Camelot:                   "camelot",
		MuteSwitch:                "muteswitch",
		SyncSwapClassic:           "syncswap-classic",
		SyncSwapStable:            "syncswap-stable",
		PancakeV3:                 "pancake-v3",
	}
)
